server {
        listen 80;
        listen [::]:80;

        server_name localhost;

        # For back-end
        location /api/ {
                proxy_pass http://book-manage-backend:9001/;
                client_max_body_size 10M;
        }

        # All other locations go to frontend
        location / {
                proxy_pass http://book-manage-ui:3000;
        }
}



