// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSlkDeviceExtra = "slk_device_extra"

// SlkDeviceExtra mapped from table <slk_device_extra>
type SlkDeviceExtra struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:id" json:"id"` // id
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt   int64     `gorm:"column:deleted_at;not null" json:"deleted_at"`
	Application string    `gorm:"column:application;not null" json:"application"`
	Did         int64     `gorm:"column:did;not null;comment:deviceid" json:"did"`  // deviceid
	Key         string    `gorm:"column:key;not null;comment:key" json:"key"`       // key
	Value       string    `gorm:"column:value;not null;comment:value" json:"value"` // value
}

// TableName SlkDeviceExtra's table name
func (*SlkDeviceExtra) TableName() string {
	return TableNameSlkDeviceExtra
}
