// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSlkDevice = "slk_device"

// SlkDevice mapped from table <slk_device>
type SlkDevice struct {
	ID               int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:id" json:"id"` // id
	CreatedAt        time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt        time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt        int64     `gorm:"column:deleted_at;not null" json:"deleted_at"`
	DeviceID         string    `gorm:"column:device_id;not null;comment:ID" json:"device_id"` // ID
	Platform         string    `gorm:"column:platform;not null" json:"platform"`
	DeviceModel      string    `gorm:"column:device_model;not null" json:"device_model"`
	ResolutionWidth  int32     `gorm:"column:resolution_width;not null;comment: px" json:"resolution_width"`   //  px
	ResolutionHeight int32     `gorm:"column:resolution_height;not null;comment: px" json:"resolution_height"` //  px
	ScreenDensity    float32   `gorm:"column:screen_density;not null" json:"screen_density"`
	Rom              float32   `gorm:"column:rom;not null;comment:,gb" json:"rom"` // ,gb
	RAM              float32   `gorm:"column:ram;not null;comment:gb" json:"ram"`  // gb
}

// TableName SlkDevice's table name
func (*SlkDevice) TableName() string {
	return TableNameSlkDevice
}
