// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.28.0--dev
// source: api/alchemist.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AlchemistService_GetAppAccountToken_FullMethodName           = "/alchemist_api.AlchemistService/GetAppAccountToken"
	AlchemistService_JoinReferralProgram_FullMethodName          = "/alchemist_api.AlchemistService/JoinReferralProgram"
	AlchemistService_CheckReferralCode_FullMethodName            = "/alchemist_api.AlchemistService/CheckReferralCode"
	AlchemistService_BindReferralCode_FullMethodName             = "/alchemist_api.AlchemistService/BindReferralCode"
	AlchemistService_GetRewardPoints_FullMethodName              = "/alchemist_api.AlchemistService/GetRewardPoints"
	AlchemistService_GetNewUserDiscountState_FullMethodName      = "/alchemist_api.AlchemistService/GetNewUserDiscountState"
	AlchemistService_GetNewUserDiscountSignature_FullMethodName  = "/alchemist_api.AlchemistService/GetNewUserDiscountSignature"
	AlchemistService_UseNewUserDiscountOffer_FullMethodName      = "/alchemist_api.AlchemistService/UseNewUserDiscountOffer"
	AlchemistService_GetTrialState_FullMethodName                = "/alchemist_api.AlchemistService/GetTrialState"
	AlchemistService_GetRewardList_FullMethodName                = "/alchemist_api.AlchemistService/GetRewardList"
	AlchemistService_RedeemReward_FullMethodName                 = "/alchemist_api.AlchemistService/RedeemReward"
	AlchemistService_RedeemRewardOffer_FullMethodName            = "/alchemist_api.AlchemistService/RedeemRewardOffer"
	AlchemistService_FinishRewardOffer_FullMethodName            = "/alchemist_api.AlchemistService/FinishRewardOffer"
	AlchemistService_ConvertUnusedNewUserDiscount_FullMethodName = "/alchemist_api.AlchemistService/ConvertUnusedNewUserDiscount"
	AlchemistService_CheckReferralCodeAndDevice_FullMethodName   = "/alchemist_api.AlchemistService/CheckReferralCodeAndDevice"
	AlchemistService_MarkNewRegistration_FullMethodName          = "/alchemist_api.AlchemistService/MarkNewRegistration"
	AlchemistService_Unregister_FullMethodName                   = "/alchemist_api.AlchemistService/Unregister"
	AlchemistService_GetState_FullMethodName                     = "/alchemist_api.AlchemistService/GetState"
)

// AlchemistServiceClient is the client API for AlchemistService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AlchemistServiceClient interface {
	GetAppAccountToken(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAppAccountTokenResponse, error)
	JoinReferralProgram(ctx context.Context, in *JoinReferralProgramRequest, opts ...grpc.CallOption) (*JoinReferralProgramResponse, error)
	CheckReferralCode(ctx context.Context, in *CheckReferralCodeRequest, opts ...grpc.CallOption) (*CheckReferralCodeResponse, error)
	BindReferralCode(ctx context.Context, in *BindReferralCodeRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	GetRewardPoints(ctx context.Context, in *GetRewardPointsRequest, opts ...grpc.CallOption) (*GetRewardPointsResponse, error)
	GetNewUserDiscountState(ctx context.Context, in *GetNewUserDiscountStateRequest, opts ...grpc.CallOption) (*GetNewUserDiscountStateResponse, error)
	GetNewUserDiscountSignature(ctx context.Context, in *GetNewUserDiscountSignatureRequest, opts ...grpc.CallOption) (*GetNewUserDiscountSignatureResponse, error)
	UseNewUserDiscountOffer(ctx context.Context, in *UseNewUserDiscountOfferRequest, opts ...grpc.CallOption) (*UseNewUserDiscountOfferResponse, error)
	GetTrialState(ctx context.Context, in *GetTrialStateRequest, opts ...grpc.CallOption) (*GetTrialStateResponse, error)
	GetRewardList(ctx context.Context, in *GetRewardListRequest, opts ...grpc.CallOption) (*GetRewardListResponse, error)
	RedeemReward(ctx context.Context, in *RedeemRewardRequest, opts ...grpc.CallOption) (*RedeemRewardResponse, error)
	RedeemRewardOffer(ctx context.Context, in *RedeemRewardOfferRequest, opts ...grpc.CallOption) (*RedeemRewardOfferResponse, error)
	FinishRewardOffer(ctx context.Context, in *FinishRewardOfferRequest, opts ...grpc.CallOption) (*FinishRewardOfferResponse, error)
	ConvertUnusedNewUserDiscount(ctx context.Context, in *ConvertUnusedNewUserDiscountRequest, opts ...grpc.CallOption) (*ConvertUnusedNewUserDiscountResponse, error)
	CheckReferralCodeAndDevice(ctx context.Context, in *CheckReferralCodeAndDeviceRequest, opts ...grpc.CallOption) (*CheckReferralCodeAndDeviceResponse, error)
	MarkNewRegistration(ctx context.Context, in *MarkNewRegistrationRequest, opts ...grpc.CallOption) (*MarkNewRegistrationResponse, error)
	Unregister(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UnregisterResponse, error)
	GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*GetStateResponse, error)
}

type alchemistServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAlchemistServiceClient(cc grpc.ClientConnInterface) AlchemistServiceClient {
	return &alchemistServiceClient{cc}
}

func (c *alchemistServiceClient) GetAppAccountToken(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAppAccountTokenResponse, error) {
	out := new(GetAppAccountTokenResponse)
	err := c.cc.Invoke(ctx, AlchemistService_GetAppAccountToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alchemistServiceClient) JoinReferralProgram(ctx context.Context, in *JoinReferralProgramRequest, opts ...grpc.CallOption) (*JoinReferralProgramResponse, error) {
	out := new(JoinReferralProgramResponse)
	err := c.cc.Invoke(ctx, AlchemistService_JoinReferralProgram_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alchemistServiceClient) CheckReferralCode(ctx context.Context, in *CheckReferralCodeRequest, opts ...grpc.CallOption) (*CheckReferralCodeResponse, error) {
	out := new(CheckReferralCodeResponse)
	err := c.cc.Invoke(ctx, AlchemistService_CheckReferralCode_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alchemistServiceClient) BindReferralCode(ctx context.Context, in *BindReferralCodeRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, AlchemistService_BindReferralCode_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alchemistServiceClient) GetRewardPoints(ctx context.Context, in *GetRewardPointsRequest, opts ...grpc.CallOption) (*GetRewardPointsResponse, error) {
	out := new(GetRewardPointsResponse)
	err := c.cc.Invoke(ctx, AlchemistService_GetRewardPoints_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alchemistServiceClient) GetNewUserDiscountState(ctx context.Context, in *GetNewUserDiscountStateRequest, opts ...grpc.CallOption) (*GetNewUserDiscountStateResponse, error) {
	out := new(GetNewUserDiscountStateResponse)
	err := c.cc.Invoke(ctx, AlchemistService_GetNewUserDiscountState_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alchemistServiceClient) GetNewUserDiscountSignature(ctx context.Context, in *GetNewUserDiscountSignatureRequest, opts ...grpc.CallOption) (*GetNewUserDiscountSignatureResponse, error) {
	out := new(GetNewUserDiscountSignatureResponse)
	err := c.cc.Invoke(ctx, AlchemistService_GetNewUserDiscountSignature_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alchemistServiceClient) UseNewUserDiscountOffer(ctx context.Context, in *UseNewUserDiscountOfferRequest, opts ...grpc.CallOption) (*UseNewUserDiscountOfferResponse, error) {
	out := new(UseNewUserDiscountOfferResponse)
	err := c.cc.Invoke(ctx, AlchemistService_UseNewUserDiscountOffer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alchemistServiceClient) GetTrialState(ctx context.Context, in *GetTrialStateRequest, opts ...grpc.CallOption) (*GetTrialStateResponse, error) {
	out := new(GetTrialStateResponse)
	err := c.cc.Invoke(ctx, AlchemistService_GetTrialState_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alchemistServiceClient) GetRewardList(ctx context.Context, in *GetRewardListRequest, opts ...grpc.CallOption) (*GetRewardListResponse, error) {
	out := new(GetRewardListResponse)
	err := c.cc.Invoke(ctx, AlchemistService_GetRewardList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alchemistServiceClient) RedeemReward(ctx context.Context, in *RedeemRewardRequest, opts ...grpc.CallOption) (*RedeemRewardResponse, error) {
	out := new(RedeemRewardResponse)
	err := c.cc.Invoke(ctx, AlchemistService_RedeemReward_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alchemistServiceClient) RedeemRewardOffer(ctx context.Context, in *RedeemRewardOfferRequest, opts ...grpc.CallOption) (*RedeemRewardOfferResponse, error) {
	out := new(RedeemRewardOfferResponse)
	err := c.cc.Invoke(ctx, AlchemistService_RedeemRewardOffer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alchemistServiceClient) FinishRewardOffer(ctx context.Context, in *FinishRewardOfferRequest, opts ...grpc.CallOption) (*FinishRewardOfferResponse, error) {
	out := new(FinishRewardOfferResponse)
	err := c.cc.Invoke(ctx, AlchemistService_FinishRewardOffer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alchemistServiceClient) ConvertUnusedNewUserDiscount(ctx context.Context, in *ConvertUnusedNewUserDiscountRequest, opts ...grpc.CallOption) (*ConvertUnusedNewUserDiscountResponse, error) {
	out := new(ConvertUnusedNewUserDiscountResponse)
	err := c.cc.Invoke(ctx, AlchemistService_ConvertUnusedNewUserDiscount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alchemistServiceClient) CheckReferralCodeAndDevice(ctx context.Context, in *CheckReferralCodeAndDeviceRequest, opts ...grpc.CallOption) (*CheckReferralCodeAndDeviceResponse, error) {
	out := new(CheckReferralCodeAndDeviceResponse)
	err := c.cc.Invoke(ctx, AlchemistService_CheckReferralCodeAndDevice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alchemistServiceClient) MarkNewRegistration(ctx context.Context, in *MarkNewRegistrationRequest, opts ...grpc.CallOption) (*MarkNewRegistrationResponse, error) {
	out := new(MarkNewRegistrationResponse)
	err := c.cc.Invoke(ctx, AlchemistService_MarkNewRegistration_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alchemistServiceClient) Unregister(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UnregisterResponse, error) {
	out := new(UnregisterResponse)
	err := c.cc.Invoke(ctx, AlchemistService_Unregister_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alchemistServiceClient) GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*GetStateResponse, error) {
	out := new(GetStateResponse)
	err := c.cc.Invoke(ctx, AlchemistService_GetState_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlchemistServiceServer is the server API for AlchemistService service.
// All implementations must embed UnimplementedAlchemistServiceServer
// for forward compatibility
type AlchemistServiceServer interface {
	GetAppAccountToken(context.Context, *Empty) (*GetAppAccountTokenResponse, error)
	JoinReferralProgram(context.Context, *JoinReferralProgramRequest) (*JoinReferralProgramResponse, error)
	CheckReferralCode(context.Context, *CheckReferralCodeRequest) (*CheckReferralCodeResponse, error)
	BindReferralCode(context.Context, *BindReferralCodeRequest) (*EmptyResponse, error)
	GetRewardPoints(context.Context, *GetRewardPointsRequest) (*GetRewardPointsResponse, error)
	GetNewUserDiscountState(context.Context, *GetNewUserDiscountStateRequest) (*GetNewUserDiscountStateResponse, error)
	GetNewUserDiscountSignature(context.Context, *GetNewUserDiscountSignatureRequest) (*GetNewUserDiscountSignatureResponse, error)
	UseNewUserDiscountOffer(context.Context, *UseNewUserDiscountOfferRequest) (*UseNewUserDiscountOfferResponse, error)
	GetTrialState(context.Context, *GetTrialStateRequest) (*GetTrialStateResponse, error)
	GetRewardList(context.Context, *GetRewardListRequest) (*GetRewardListResponse, error)
	RedeemReward(context.Context, *RedeemRewardRequest) (*RedeemRewardResponse, error)
	RedeemRewardOffer(context.Context, *RedeemRewardOfferRequest) (*RedeemRewardOfferResponse, error)
	FinishRewardOffer(context.Context, *FinishRewardOfferRequest) (*FinishRewardOfferResponse, error)
	ConvertUnusedNewUserDiscount(context.Context, *ConvertUnusedNewUserDiscountRequest) (*ConvertUnusedNewUserDiscountResponse, error)
	CheckReferralCodeAndDevice(context.Context, *CheckReferralCodeAndDeviceRequest) (*CheckReferralCodeAndDeviceResponse, error)
	MarkNewRegistration(context.Context, *MarkNewRegistrationRequest) (*MarkNewRegistrationResponse, error)
	Unregister(context.Context, *Empty) (*UnregisterResponse, error)
	GetState(context.Context, *GetStateRequest) (*GetStateResponse, error)
	mustEmbedUnimplementedAlchemistServiceServer()
}

// UnimplementedAlchemistServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAlchemistServiceServer struct {
}

func (UnimplementedAlchemistServiceServer) GetAppAccountToken(context.Context, *Empty) (*GetAppAccountTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAppAccountToken not implemented")
}
func (UnimplementedAlchemistServiceServer) JoinReferralProgram(context.Context, *JoinReferralProgramRequest) (*JoinReferralProgramResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinReferralProgram not implemented")
}
func (UnimplementedAlchemistServiceServer) CheckReferralCode(context.Context, *CheckReferralCodeRequest) (*CheckReferralCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckReferralCode not implemented")
}
func (UnimplementedAlchemistServiceServer) BindReferralCode(context.Context, *BindReferralCodeRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BindReferralCode not implemented")
}
func (UnimplementedAlchemistServiceServer) GetRewardPoints(context.Context, *GetRewardPointsRequest) (*GetRewardPointsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRewardPoints not implemented")
}
func (UnimplementedAlchemistServiceServer) GetNewUserDiscountState(context.Context, *GetNewUserDiscountStateRequest) (*GetNewUserDiscountStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNewUserDiscountState not implemented")
}
func (UnimplementedAlchemistServiceServer) GetNewUserDiscountSignature(context.Context, *GetNewUserDiscountSignatureRequest) (*GetNewUserDiscountSignatureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNewUserDiscountSignature not implemented")
}
func (UnimplementedAlchemistServiceServer) UseNewUserDiscountOffer(context.Context, *UseNewUserDiscountOfferRequest) (*UseNewUserDiscountOfferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UseNewUserDiscountOffer not implemented")
}
func (UnimplementedAlchemistServiceServer) GetTrialState(context.Context, *GetTrialStateRequest) (*GetTrialStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrialState not implemented")
}
func (UnimplementedAlchemistServiceServer) GetRewardList(context.Context, *GetRewardListRequest) (*GetRewardListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRewardList not implemented")
}
func (UnimplementedAlchemistServiceServer) RedeemReward(context.Context, *RedeemRewardRequest) (*RedeemRewardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RedeemReward not implemented")
}
func (UnimplementedAlchemistServiceServer) RedeemRewardOffer(context.Context, *RedeemRewardOfferRequest) (*RedeemRewardOfferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RedeemRewardOffer not implemented")
}
func (UnimplementedAlchemistServiceServer) FinishRewardOffer(context.Context, *FinishRewardOfferRequest) (*FinishRewardOfferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinishRewardOffer not implemented")
}
func (UnimplementedAlchemistServiceServer) ConvertUnusedNewUserDiscount(context.Context, *ConvertUnusedNewUserDiscountRequest) (*ConvertUnusedNewUserDiscountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConvertUnusedNewUserDiscount not implemented")
}
func (UnimplementedAlchemistServiceServer) CheckReferralCodeAndDevice(context.Context, *CheckReferralCodeAndDeviceRequest) (*CheckReferralCodeAndDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckReferralCodeAndDevice not implemented")
}
func (UnimplementedAlchemistServiceServer) MarkNewRegistration(context.Context, *MarkNewRegistrationRequest) (*MarkNewRegistrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkNewRegistration not implemented")
}
func (UnimplementedAlchemistServiceServer) Unregister(context.Context, *Empty) (*UnregisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unregister not implemented")
}
func (UnimplementedAlchemistServiceServer) GetState(context.Context, *GetStateRequest) (*GetStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetState not implemented")
}
func (UnimplementedAlchemistServiceServer) mustEmbedUnimplementedAlchemistServiceServer() {}

// UnsafeAlchemistServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AlchemistServiceServer will
// result in compilation errors.
type UnsafeAlchemistServiceServer interface {
	mustEmbedUnimplementedAlchemistServiceServer()
}

func RegisterAlchemistServiceServer(s grpc.ServiceRegistrar, srv AlchemistServiceServer) {
	s.RegisterService(&AlchemistService_ServiceDesc, srv)
}

func _AlchemistService_GetAppAccountToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlchemistServiceServer).GetAppAccountToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlchemistService_GetAppAccountToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlchemistServiceServer).GetAppAccountToken(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlchemistService_JoinReferralProgram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinReferralProgramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlchemistServiceServer).JoinReferralProgram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlchemistService_JoinReferralProgram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlchemistServiceServer).JoinReferralProgram(ctx, req.(*JoinReferralProgramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlchemistService_CheckReferralCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckReferralCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlchemistServiceServer).CheckReferralCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlchemistService_CheckReferralCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlchemistServiceServer).CheckReferralCode(ctx, req.(*CheckReferralCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlchemistService_BindReferralCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindReferralCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlchemistServiceServer).BindReferralCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlchemistService_BindReferralCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlchemistServiceServer).BindReferralCode(ctx, req.(*BindReferralCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlchemistService_GetRewardPoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRewardPointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlchemistServiceServer).GetRewardPoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlchemistService_GetRewardPoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlchemistServiceServer).GetRewardPoints(ctx, req.(*GetRewardPointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlchemistService_GetNewUserDiscountState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNewUserDiscountStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlchemistServiceServer).GetNewUserDiscountState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlchemistService_GetNewUserDiscountState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlchemistServiceServer).GetNewUserDiscountState(ctx, req.(*GetNewUserDiscountStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlchemistService_GetNewUserDiscountSignature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNewUserDiscountSignatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlchemistServiceServer).GetNewUserDiscountSignature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlchemistService_GetNewUserDiscountSignature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlchemistServiceServer).GetNewUserDiscountSignature(ctx, req.(*GetNewUserDiscountSignatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlchemistService_UseNewUserDiscountOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UseNewUserDiscountOfferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlchemistServiceServer).UseNewUserDiscountOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlchemistService_UseNewUserDiscountOffer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlchemistServiceServer).UseNewUserDiscountOffer(ctx, req.(*UseNewUserDiscountOfferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlchemistService_GetTrialState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrialStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlchemistServiceServer).GetTrialState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlchemistService_GetTrialState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlchemistServiceServer).GetTrialState(ctx, req.(*GetTrialStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlchemistService_GetRewardList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRewardListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlchemistServiceServer).GetRewardList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlchemistService_GetRewardList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlchemistServiceServer).GetRewardList(ctx, req.(*GetRewardListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlchemistService_RedeemReward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RedeemRewardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlchemistServiceServer).RedeemReward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlchemistService_RedeemReward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlchemistServiceServer).RedeemReward(ctx, req.(*RedeemRewardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlchemistService_RedeemRewardOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RedeemRewardOfferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlchemistServiceServer).RedeemRewardOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlchemistService_RedeemRewardOffer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlchemistServiceServer).RedeemRewardOffer(ctx, req.(*RedeemRewardOfferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlchemistService_FinishRewardOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishRewardOfferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlchemistServiceServer).FinishRewardOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlchemistService_FinishRewardOffer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlchemistServiceServer).FinishRewardOffer(ctx, req.(*FinishRewardOfferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlchemistService_ConvertUnusedNewUserDiscount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConvertUnusedNewUserDiscountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlchemistServiceServer).ConvertUnusedNewUserDiscount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlchemistService_ConvertUnusedNewUserDiscount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlchemistServiceServer).ConvertUnusedNewUserDiscount(ctx, req.(*ConvertUnusedNewUserDiscountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlchemistService_CheckReferralCodeAndDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckReferralCodeAndDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlchemistServiceServer).CheckReferralCodeAndDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlchemistService_CheckReferralCodeAndDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlchemistServiceServer).CheckReferralCodeAndDevice(ctx, req.(*CheckReferralCodeAndDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlchemistService_MarkNewRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkNewRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlchemistServiceServer).MarkNewRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlchemistService_MarkNewRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlchemistServiceServer).MarkNewRegistration(ctx, req.(*MarkNewRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlchemistService_Unregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlchemistServiceServer).Unregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlchemistService_Unregister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlchemistServiceServer).Unregister(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlchemistService_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlchemistServiceServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlchemistService_GetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlchemistServiceServer).GetState(ctx, req.(*GetStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AlchemistService_ServiceDesc is the grpc.ServiceDesc for AlchemistService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AlchemistService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "alchemist_api.AlchemistService",
	HandlerType: (*AlchemistServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAppAccountToken",
			Handler:    _AlchemistService_GetAppAccountToken_Handler,
		},
		{
			MethodName: "JoinReferralProgram",
			Handler:    _AlchemistService_JoinReferralProgram_Handler,
		},
		{
			MethodName: "CheckReferralCode",
			Handler:    _AlchemistService_CheckReferralCode_Handler,
		},
		{
			MethodName: "BindReferralCode",
			Handler:    _AlchemistService_BindReferralCode_Handler,
		},
		{
			MethodName: "GetRewardPoints",
			Handler:    _AlchemistService_GetRewardPoints_Handler,
		},
		{
			MethodName: "GetNewUserDiscountState",
			Handler:    _AlchemistService_GetNewUserDiscountState_Handler,
		},
		{
			MethodName: "GetNewUserDiscountSignature",
			Handler:    _AlchemistService_GetNewUserDiscountSignature_Handler,
		},
		{
			MethodName: "UseNewUserDiscountOffer",
			Handler:    _AlchemistService_UseNewUserDiscountOffer_Handler,
		},
		{
			MethodName: "GetTrialState",
			Handler:    _AlchemistService_GetTrialState_Handler,
		},
		{
			MethodName: "GetRewardList",
			Handler:    _AlchemistService_GetRewardList_Handler,
		},
		{
			MethodName: "RedeemReward",
			Handler:    _AlchemistService_RedeemReward_Handler,
		},
		{
			MethodName: "RedeemRewardOffer",
			Handler:    _AlchemistService_RedeemRewardOffer_Handler,
		},
		{
			MethodName: "FinishRewardOffer",
			Handler:    _AlchemistService_FinishRewardOffer_Handler,
		},
		{
			MethodName: "ConvertUnusedNewUserDiscount",
			Handler:    _AlchemistService_ConvertUnusedNewUserDiscount_Handler,
		},
		{
			MethodName: "CheckReferralCodeAndDevice",
			Handler:    _AlchemistService_CheckReferralCodeAndDevice_Handler,
		},
		{
			MethodName: "MarkNewRegistration",
			Handler:    _AlchemistService_MarkNewRegistration_Handler,
		},
		{
			MethodName: "Unregister",
			Handler:    _AlchemistService_Unregister_Handler,
		},
		{
			MethodName: "GetState",
			Handler:    _AlchemistService_GetState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/alchemist.proto",
}

const (
	AlchemistConsoleService_ListConfigs_FullMethodName                 = "/alchemist_api.AlchemistConsoleService/ListConfigs"
	AlchemistConsoleService_CreateConfig_FullMethodName                = "/alchemist_api.AlchemistConsoleService/CreateConfig"
	AlchemistConsoleService_UpdateConfig_FullMethodName                = "/alchemist_api.AlchemistConsoleService/UpdateConfig"
	AlchemistConsoleService_DeleteConfig_FullMethodName                = "/alchemist_api.AlchemistConsoleService/DeleteConfig"
	AlchemistConsoleService_GetCurrentSubscriptionCount_FullMethodName = "/alchemist_api.AlchemistConsoleService/GetCurrentSubscriptionCount"
	AlchemistConsoleService_ListSubscriptionCounts_FullMethodName      = "/alchemist_api.AlchemistConsoleService/ListSubscriptionCounts"
	AlchemistConsoleService_GetAllApps_FullMethodName                  = "/alchemist_api.AlchemistConsoleService/GetAllApps"
)

// AlchemistConsoleServiceClient is the client API for AlchemistConsoleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AlchemistConsoleServiceClient interface {
	ListConfigs(ctx context.Context, in *ListConfigsRequest, opts ...grpc.CallOption) (*ListConfigsResponse, error)
	CreateConfig(ctx context.Context, in *CreateConfigRequest, opts ...grpc.CallOption) (*CreateConfigResponse, error)
	UpdateConfig(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*UpdateConfigResponse, error)
	DeleteConfig(ctx context.Context, in *DeleteConfigRequest, opts ...grpc.CallOption) (*DeleteConfigResponse, error)
	GetCurrentSubscriptionCount(ctx context.Context, in *GetCurrentSubscriptionCountRequest, opts ...grpc.CallOption) (*GetCurrentSubscriptionCountResponse, error)
	ListSubscriptionCounts(ctx context.Context, in *ListSubscriptionCountsRequest, opts ...grpc.CallOption) (*ListSubscriptionCountsResponse, error)
	GetAllApps(ctx context.Context, in *GetAllAppsRequest, opts ...grpc.CallOption) (*GetAllAppsResponse, error)
}

type alchemistConsoleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAlchemistConsoleServiceClient(cc grpc.ClientConnInterface) AlchemistConsoleServiceClient {
	return &alchemistConsoleServiceClient{cc}
}

func (c *alchemistConsoleServiceClient) ListConfigs(ctx context.Context, in *ListConfigsRequest, opts ...grpc.CallOption) (*ListConfigsResponse, error) {
	out := new(ListConfigsResponse)
	err := c.cc.Invoke(ctx, AlchemistConsoleService_ListConfigs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alchemistConsoleServiceClient) CreateConfig(ctx context.Context, in *CreateConfigRequest, opts ...grpc.CallOption) (*CreateConfigResponse, error) {
	out := new(CreateConfigResponse)
	err := c.cc.Invoke(ctx, AlchemistConsoleService_CreateConfig_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alchemistConsoleServiceClient) UpdateConfig(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*UpdateConfigResponse, error) {
	out := new(UpdateConfigResponse)
	err := c.cc.Invoke(ctx, AlchemistConsoleService_UpdateConfig_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alchemistConsoleServiceClient) DeleteConfig(ctx context.Context, in *DeleteConfigRequest, opts ...grpc.CallOption) (*DeleteConfigResponse, error) {
	out := new(DeleteConfigResponse)
	err := c.cc.Invoke(ctx, AlchemistConsoleService_DeleteConfig_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alchemistConsoleServiceClient) GetCurrentSubscriptionCount(ctx context.Context, in *GetCurrentSubscriptionCountRequest, opts ...grpc.CallOption) (*GetCurrentSubscriptionCountResponse, error) {
	out := new(GetCurrentSubscriptionCountResponse)
	err := c.cc.Invoke(ctx, AlchemistConsoleService_GetCurrentSubscriptionCount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alchemistConsoleServiceClient) ListSubscriptionCounts(ctx context.Context, in *ListSubscriptionCountsRequest, opts ...grpc.CallOption) (*ListSubscriptionCountsResponse, error) {
	out := new(ListSubscriptionCountsResponse)
	err := c.cc.Invoke(ctx, AlchemistConsoleService_ListSubscriptionCounts_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alchemistConsoleServiceClient) GetAllApps(ctx context.Context, in *GetAllAppsRequest, opts ...grpc.CallOption) (*GetAllAppsResponse, error) {
	out := new(GetAllAppsResponse)
	err := c.cc.Invoke(ctx, AlchemistConsoleService_GetAllApps_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlchemistConsoleServiceServer is the server API for AlchemistConsoleService service.
// All implementations must embed UnimplementedAlchemistConsoleServiceServer
// for forward compatibility
type AlchemistConsoleServiceServer interface {
	ListConfigs(context.Context, *ListConfigsRequest) (*ListConfigsResponse, error)
	CreateConfig(context.Context, *CreateConfigRequest) (*CreateConfigResponse, error)
	UpdateConfig(context.Context, *UpdateConfigRequest) (*UpdateConfigResponse, error)
	DeleteConfig(context.Context, *DeleteConfigRequest) (*DeleteConfigResponse, error)
	GetCurrentSubscriptionCount(context.Context, *GetCurrentSubscriptionCountRequest) (*GetCurrentSubscriptionCountResponse, error)
	ListSubscriptionCounts(context.Context, *ListSubscriptionCountsRequest) (*ListSubscriptionCountsResponse, error)
	GetAllApps(context.Context, *GetAllAppsRequest) (*GetAllAppsResponse, error)
	mustEmbedUnimplementedAlchemistConsoleServiceServer()
}

// UnimplementedAlchemistConsoleServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAlchemistConsoleServiceServer struct {
}

func (UnimplementedAlchemistConsoleServiceServer) ListConfigs(context.Context, *ListConfigsRequest) (*ListConfigsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListConfigs not implemented")
}
func (UnimplementedAlchemistConsoleServiceServer) CreateConfig(context.Context, *CreateConfigRequest) (*CreateConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateConfig not implemented")
}
func (UnimplementedAlchemistConsoleServiceServer) UpdateConfig(context.Context, *UpdateConfigRequest) (*UpdateConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateConfig not implemented")
}
func (UnimplementedAlchemistConsoleServiceServer) DeleteConfig(context.Context, *DeleteConfigRequest) (*DeleteConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteConfig not implemented")
}
func (UnimplementedAlchemistConsoleServiceServer) GetCurrentSubscriptionCount(context.Context, *GetCurrentSubscriptionCountRequest) (*GetCurrentSubscriptionCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrentSubscriptionCount not implemented")
}
func (UnimplementedAlchemistConsoleServiceServer) ListSubscriptionCounts(context.Context, *ListSubscriptionCountsRequest) (*ListSubscriptionCountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSubscriptionCounts not implemented")
}
func (UnimplementedAlchemistConsoleServiceServer) GetAllApps(context.Context, *GetAllAppsRequest) (*GetAllAppsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllApps not implemented")
}
func (UnimplementedAlchemistConsoleServiceServer) mustEmbedUnimplementedAlchemistConsoleServiceServer() {
}

// UnsafeAlchemistConsoleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AlchemistConsoleServiceServer will
// result in compilation errors.
type UnsafeAlchemistConsoleServiceServer interface {
	mustEmbedUnimplementedAlchemistConsoleServiceServer()
}

func RegisterAlchemistConsoleServiceServer(s grpc.ServiceRegistrar, srv AlchemistConsoleServiceServer) {
	s.RegisterService(&AlchemistConsoleService_ServiceDesc, srv)
}

func _AlchemistConsoleService_ListConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConfigsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlchemistConsoleServiceServer).ListConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlchemistConsoleService_ListConfigs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlchemistConsoleServiceServer).ListConfigs(ctx, req.(*ListConfigsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlchemistConsoleService_CreateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlchemistConsoleServiceServer).CreateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlchemistConsoleService_CreateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlchemistConsoleServiceServer).CreateConfig(ctx, req.(*CreateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlchemistConsoleService_UpdateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlchemistConsoleServiceServer).UpdateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlchemistConsoleService_UpdateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlchemistConsoleServiceServer).UpdateConfig(ctx, req.(*UpdateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlchemistConsoleService_DeleteConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlchemistConsoleServiceServer).DeleteConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlchemistConsoleService_DeleteConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlchemistConsoleServiceServer).DeleteConfig(ctx, req.(*DeleteConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlchemistConsoleService_GetCurrentSubscriptionCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentSubscriptionCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlchemistConsoleServiceServer).GetCurrentSubscriptionCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlchemistConsoleService_GetCurrentSubscriptionCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlchemistConsoleServiceServer).GetCurrentSubscriptionCount(ctx, req.(*GetCurrentSubscriptionCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlchemistConsoleService_ListSubscriptionCounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSubscriptionCountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlchemistConsoleServiceServer).ListSubscriptionCounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlchemistConsoleService_ListSubscriptionCounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlchemistConsoleServiceServer).ListSubscriptionCounts(ctx, req.(*ListSubscriptionCountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlchemistConsoleService_GetAllApps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllAppsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlchemistConsoleServiceServer).GetAllApps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlchemistConsoleService_GetAllApps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlchemistConsoleServiceServer).GetAllApps(ctx, req.(*GetAllAppsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AlchemistConsoleService_ServiceDesc is the grpc.ServiceDesc for AlchemistConsoleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AlchemistConsoleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "alchemist_api.AlchemistConsoleService",
	HandlerType: (*AlchemistConsoleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListConfigs",
			Handler:    _AlchemistConsoleService_ListConfigs_Handler,
		},
		{
			MethodName: "CreateConfig",
			Handler:    _AlchemistConsoleService_CreateConfig_Handler,
		},
		{
			MethodName: "UpdateConfig",
			Handler:    _AlchemistConsoleService_UpdateConfig_Handler,
		},
		{
			MethodName: "DeleteConfig",
			Handler:    _AlchemistConsoleService_DeleteConfig_Handler,
		},
		{
			MethodName: "GetCurrentSubscriptionCount",
			Handler:    _AlchemistConsoleService_GetCurrentSubscriptionCount_Handler,
		},
		{
			MethodName: "ListSubscriptionCounts",
			Handler:    _AlchemistConsoleService_ListSubscriptionCounts_Handler,
		},
		{
			MethodName: "GetAllApps",
			Handler:    _AlchemistConsoleService_GetAllApps_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/alchemist.proto",
}

const (
	TestService_ResetDeviceCheck_FullMethodName  = "/alchemist_api.TestService/ResetDeviceCheck"
	TestService_RemoveFraudRecord_FullMethodName = "/alchemist_api.TestService/RemoveFraudRecord"
)

// TestServiceClient is the client API for TestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TestServiceClient interface {
	ResetDeviceCheck(ctx context.Context, in *ResetDeviceCheckRequest, opts ...grpc.CallOption) (*ResetDeviceCheckResponse, error)
	RemoveFraudRecord(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RemoveFraudRecordResponse, error)
}

type testServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTestServiceClient(cc grpc.ClientConnInterface) TestServiceClient {
	return &testServiceClient{cc}
}

func (c *testServiceClient) ResetDeviceCheck(ctx context.Context, in *ResetDeviceCheckRequest, opts ...grpc.CallOption) (*ResetDeviceCheckResponse, error) {
	out := new(ResetDeviceCheckResponse)
	err := c.cc.Invoke(ctx, TestService_ResetDeviceCheck_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testServiceClient) RemoveFraudRecord(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RemoveFraudRecordResponse, error) {
	out := new(RemoveFraudRecordResponse)
	err := c.cc.Invoke(ctx, TestService_RemoveFraudRecord_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestServiceServer is the server API for TestService service.
// All implementations must embed UnimplementedTestServiceServer
// for forward compatibility
type TestServiceServer interface {
	ResetDeviceCheck(context.Context, *ResetDeviceCheckRequest) (*ResetDeviceCheckResponse, error)
	RemoveFraudRecord(context.Context, *Empty) (*RemoveFraudRecordResponse, error)
	mustEmbedUnimplementedTestServiceServer()
}

// UnimplementedTestServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTestServiceServer struct {
}

func (UnimplementedTestServiceServer) ResetDeviceCheck(context.Context, *ResetDeviceCheckRequest) (*ResetDeviceCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetDeviceCheck not implemented")
}
func (UnimplementedTestServiceServer) RemoveFraudRecord(context.Context, *Empty) (*RemoveFraudRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveFraudRecord not implemented")
}
func (UnimplementedTestServiceServer) mustEmbedUnimplementedTestServiceServer() {}

// UnsafeTestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TestServiceServer will
// result in compilation errors.
type UnsafeTestServiceServer interface {
	mustEmbedUnimplementedTestServiceServer()
}

func RegisterTestServiceServer(s grpc.ServiceRegistrar, srv TestServiceServer) {
	s.RegisterService(&TestService_ServiceDesc, srv)
}

func _TestService_ResetDeviceCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetDeviceCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).ResetDeviceCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TestService_ResetDeviceCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).ResetDeviceCheck(ctx, req.(*ResetDeviceCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestService_RemoveFraudRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).RemoveFraudRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TestService_RemoveFraudRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).RemoveFraudRecord(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// TestService_ServiceDesc is the grpc.ServiceDesc for TestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "alchemist_api.TestService",
	HandlerType: (*TestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResetDeviceCheck",
			Handler:    _TestService_ResetDeviceCheck_Handler,
		},
		{
			MethodName: "RemoveFraudRecord",
			Handler:    _TestService_RemoveFraudRecord_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/alchemist.proto",
}
