// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBackup = "backup"

// Backup backup table
type Backup struct {
	ID                          int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:primary id" json:"id"`                                                                 // primary id
	CreatedAt                   int64  `gorm:"column:created_at;not null;comment:created at" json:"created_at"`                                                                      // created at
	UpdatedAt                   int64  `gorm:"column:updated_at;not null;comment:updated at" json:"updated_at"`                                                                      // updated at
	UserID                      int64  `gorm:"column:user_id;not null;comment:slark user id" json:"user_id"`                                                                         // slark user id
	PasswordHash                string `gorm:"column:password_hash;not null;comment:unlock password hash" json:"password_hash"`                                                      // unlock password hash
	UserPublicKey               string `gorm:"column:user_public_key;not null;comment:user public key" json:"user_public_key"`                                                       // user public key
	EncryptedFamilyKey          string `gorm:"column:encrypted_family_key;not null;comment:encrypted family key" json:"encrypted_family_key"`                                        // encrypted family key
	SecurityQuestions           string `gorm:"column:security_questions;not null;comment:unlock password security questions" json:"security_questions"`                              // unlock password security questions
	SecurityQuestionsCiphertext string `gorm:"column:security_questions_ciphertext;not null;comment:unlock password security question answers" json:"security_questions_ciphertext"` // unlock password security question answers
}

// TableName Backup's table name
func (*Backup) TableName() string {
	return TableNameBackup
}
