// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFamilyMessage = "family_message"

// FamilyMessage family message table
type FamilyMessage struct {
	ID        int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:primary id" json:"id"`  // primary id
	FamilyID  string `gorm:"column:family_id;not null;comment:family id" json:"family_id"`          // family id
	CreatedAt int64  `gorm:"column:created_at;not null;comment:created at" json:"created_at"`       // created at
	CreatedBy string `gorm:"column:created_by;not null;comment:slark user email" json:"created_by"` // slark user email
	Target    string `gorm:"column:target;not null;comment:slark user email" json:"target"`         // slark user email
	Operation int32  `gorm:"column:operation;not null;comment:operation" json:"operation"`          // operation
}

// TableName FamilyMessage's table name
func (*FamilyMessage) TableName() string {
	return TableNameFamilyMessage
}
