[ClientErrMsg_WrongRequestParameters]
other = "请求参数有误，请您排错后重试"

[ClientErrMsg_ResourceNotFound]
other = "未找到相关资源"

[ClientErrMsg_UnsupportedToken]
other = "未找到相关token"

[ClientErrMsg_ApiKeyIsInvalid]
other = "ApiKey无效，请正确输入apiKey"

[FatalErrMsg]
other = "服务器发生一些问题， 请稍后重试。 如果多次无法登录， 请联系客服"
