[ClientErrMsg_WrongRequestParameters]
other = "Request has wrong parameters, please inspect parameters"

[ClientErrMsg_UnknownSpotPrice]
other = "Sorry. Token spot prices are handled, you can try after some seconds"

[ClientErrMsg_UserHasNoSecurityQuestions]
other = "User has no security questions. You can try to create some security questions."

[ClientErrMsg_UserHasNoDatum]
other = "User has no datum. You can try to create some datum."

[ClientErrMsg_UserHasNoPrivateKeyBackup]
other = "User has no private key bakup. You can try to create some private key backup."

[ClientErrMsg_TooManyRequests]
other = "Too many requests."

[FatalErrMsg]
other = "Sorry. Some fatal error happened. Try to contact the custom service of this APP."
