// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePrivacyEmailAccount = "privacy_email_account"

// PrivacyEmailAccount email account table
type PrivacyEmailAccount struct {
	ID           int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:primary id" json:"id"`     // primary id
	UserID       int64  `gorm:"column:user_id;not null;comment:slark user id" json:"user_id"`             // slark user id
	EmailAccount string `gorm:"column:email_account;not null;comment:email account" json:"email_account"` // email account
	Password     string `gorm:"column:password;not null;comment:email account password" json:"password"`  // email account password
}

// TableName PrivacyEmailAccount's table name
func (*PrivacyEmailAccount) TableName() string {
	return TableNamePrivacyEmailAccount
}
