// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRawTransaction = "raw_transactions"

// RawTransaction mapped from table <raw_transactions>
type RawTransaction struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt   int64     `gorm:"column:deleted_at;not null;comment:Coding style" json:"deleted_at"` // Coding style
	Data        string    `gorm:"column:data;not null" json:"data"`
	Handled     bool      `gorm:"column:handled;not null" json:"handled"`
	Error       string    `gorm:"column:error;not null" json:"error"`
	Environment int32     `gorm:"column:environment;not null" json:"environment"`
}

// TableName RawTransaction's table name
func (*RawTransaction) TableName() string {
	return TableNameRawTransaction
}
