// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameReferralLog = "referral_log"

// ReferralLog mapped from table <referral_log>
type ReferralLog struct {
	ID              int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt       time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt       time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt       int64     `gorm:"column:deleted_at;not null;comment:Coding style" json:"deleted_at"` // Coding style
	ReferralPointID int64     `gorm:"column:referral_point_id;not null" json:"referral_point_id"`
	UserID          int64     `gorm:"column:user_id;not null" json:"user_id"`
	App             string    `gorm:"column:app;not null" json:"app"`
	Timestamp       int64     `gorm:"column:timestamp;not null" json:"timestamp"`
	Type            int32     `gorm:"column:type;not null" json:"type"`
	Reason          int32     `gorm:"column:reason;not null" json:"reason"`
	Points          int32     `gorm:"column:points;not null" json:"points"`
}

// TableName ReferralLog's table name
func (*ReferralLog) TableName() string {
	return TableNameReferralLog
}
