// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSlarkUser = "slark_users"

// SlarkUser mapped from table <slark_users>
type SlarkUser struct {
	ID              int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt       time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt       time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt       int64     `gorm:"column:deleted_at;not null;comment:Coding style" json:"deleted_at"` // Coding style
	AppAccountToken string    `gorm:"column:app_account_token;not null" json:"app_account_token"`
	RegisteredAt    int64     `gorm:"column:registered_at;not null" json:"registered_at"`
	UserID          int64     `gorm:"column:user_id;not null" json:"user_id"`
}

// TableName SlarkUser's table name
func (*SlarkUser) TableName() string {
	return TableNameSlarkUser
}
