// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSubscriptionStateProd = "subscription_state_prod"

// SubscriptionStateProd mapped from table <subscription_state_prod>
type SubscriptionStateProd struct {
	ID                    int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt             time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt             time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt             int64     `gorm:"column:deleted_at;not null;comment:Coding style" json:"deleted_at"` // Coding style
	UserID                int64     `gorm:"column:user_id;not null" json:"user_id"`
	App                   string    `gorm:"column:app;not null" json:"app"`
	Subscribed            bool      `gorm:"column:subscribed;not null" json:"subscribed"`
	FirstTimeSubscribedAt int64     `gorm:"column:first_time_subscribed_at;not null" json:"first_time_subscribed_at"`
	SubscribedAt          int64     `gorm:"column:subscribed_at;not null" json:"subscribed_at"`
	CurrentBillDate       int64     `gorm:"column:current_bill_date;not null" json:"current_bill_date"`
	CurrentBillPrice      string    `gorm:"column:current_bill_price;not null" json:"current_bill_price"`
	CurrentOfferType      string    `gorm:"column:current_offer_type;not null" json:"current_offer_type"`
	CurrentOfferID        string    `gorm:"column:current_offer_id;not null" json:"current_offer_id"`
	ExpirationDate        int64     `gorm:"column:expiration_date;not null" json:"expiration_date"`
	AutoRenew             bool      `gorm:"column:auto_renew;not null" json:"auto_renew"`
	NextBillPrice         string    `gorm:"column:next_bill_price;not null" json:"next_bill_price"`
	NextOfferType         string    `gorm:"column:next_offer_type;not null" json:"next_offer_type"`
	NextOfferID           string    `gorm:"column:next_offer_id;not null" json:"next_offer_id"`
	CurrencyCode          string    `gorm:"column:currency_code;not null" json:"currency_code"`
}

// TableName SubscriptionStateProd's table name
func (*SubscriptionStateProd) TableName() string {
	return TableNameSubscriptionStateProd
}
