// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTransactionsProd = "transactions_prod"

// TransactionsProd mapped from table <transactions_prod>
type TransactionsProd struct {
	ID                          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt                   time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt                   time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt                   int64     `gorm:"column:deleted_at;not null;comment:Coding style" json:"deleted_at"` // Coding style
	UserID                      int64     `gorm:"column:user_id;not null" json:"user_id"`
	App                         string    `gorm:"column:app;not null" json:"app"`
	OriginalTransactionID       string    `gorm:"column:original_transaction_id;not null" json:"original_transaction_id"`
	TransactionID               string    `gorm:"column:transaction_id;not null" json:"transaction_id"`
	WebOrderLineItemID          string    `gorm:"column:web_order_line_item_id;not null" json:"web_order_line_item_id"`
	BundleID                    string    `gorm:"column:bundle_id;not null" json:"bundle_id"`
	AppAccountToken             string    `gorm:"column:app_account_token;not null" json:"app_account_token"`
	ProductID                   string    `gorm:"column:product_id;not null" json:"product_id"`
	Type                        string    `gorm:"column:type;not null" json:"type"`
	SubscriptionGroupIdentifier string    `gorm:"column:subscription_group_identifier;not null" json:"subscription_group_identifier"`
	Quantity                    int32     `gorm:"column:quantity;not null" json:"quantity"`
	Price                       int32     `gorm:"column:price;not null" json:"price"`
	Currency                    string    `gorm:"column:currency;not null" json:"currency"`
	Storefront                  string    `gorm:"column:storefront;not null" json:"storefront"`
	StorefrontID                string    `gorm:"column:storefront_id;not null" json:"storefront_id"`
	OfferIdentifier             string    `gorm:"column:offer_identifier;not null" json:"offer_identifier"`
	OfferType                   int32     `gorm:"column:offer_type;not null" json:"offer_type"`
	OfferDiscountType           string    `gorm:"column:offer_discount_type;not null" json:"offer_discount_type"`
	OriginalPurchaseDate        int64     `gorm:"column:original_purchase_date;not null" json:"original_purchase_date"`
	PurchaseDate                int64     `gorm:"column:purchase_date;not null" json:"purchase_date"`
	RecentSubscriptionStartDate int64     `gorm:"column:recent_subscription_start_date;not null" json:"recent_subscription_start_date"`
	IsInBillingRetryPeriod      bool      `gorm:"column:is_in_billing_retry_period;not null" json:"is_in_billing_retry_period"`
	GracePeriodExpiresDate      int64     `gorm:"column:grace_period_expires_date;not null" json:"grace_period_expires_date"`
	AutoRenewStatus             int32     `gorm:"column:auto_renew_status;not null" json:"auto_renew_status"`
	AutoRenewProductID          string    `gorm:"column:auto_renew_product_id;not null" json:"auto_renew_product_id"`
	ExpirationIntent            int32     `gorm:"column:expiration_intent;not null" json:"expiration_intent"`
	ExpiresDate                 int64     `gorm:"column:expires_date;not null" json:"expires_date"`
	IsUpgraded                  bool      `gorm:"column:is_upgraded;not null" json:"is_upgraded"`
	RenewalDate                 int64     `gorm:"column:renewal_date;not null" json:"renewal_date"`
	InAppOwnershipType          string    `gorm:"column:in_app_ownership_type;not null" json:"in_app_ownership_type"`
	PriceIncreaseStatus         int32     `gorm:"column:price_increase_status;not null" json:"price_increase_status"`
	RevocationDate              int64     `gorm:"column:revocation_date;not null" json:"revocation_date"`
	RevocationReason            int32     `gorm:"column:revocation_reason;not null" json:"revocation_reason"`
	TransactionReason           string    `gorm:"column:transaction_reason;not null" json:"transaction_reason"`
	SignedDate                  int64     `gorm:"column:signed_date;not null" json:"signed_date"`
}

// TableName TransactionsProd's table name
func (*TransactionsProd) TableName() string {
	return TableNameTransactionsProd
}
