// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.28.0--dev
// source: api/connector.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ConnectorService_CreatePassword_FullMethodName   = "/connector_api.ConnectorService/CreatePassword"
	ConnectorService_CheckPassword_FullMethodName    = "/connector_api.ConnectorService/CheckPassword"
	ConnectorService_DeletePassword_FullMethodName   = "/connector_api.ConnectorService/DeletePassword"
	ConnectorService_CreatePrivateKey_FullMethodName = "/connector_api.ConnectorService/CreatePrivateKey"
	ConnectorService_GetPublicKey_FullMethodName     = "/connector_api.ConnectorService/GetPublicKey"
	ConnectorService_DeletePrivateKey_FullMethodName = "/connector_api.ConnectorService/DeletePrivateKey"
	ConnectorService_SaveData_FullMethodName         = "/connector_api.ConnectorService/SaveData"
	ConnectorService_DeleteData_FullMethodName       = "/connector_api.ConnectorService/DeleteData"
	ConnectorService_DecryptData_FullMethodName      = "/connector_api.ConnectorService/DecryptData"
	ConnectorService_GetData_FullMethodName          = "/connector_api.ConnectorService/GetData"
	ConnectorService_CheckKeyExisting_FullMethodName = "/connector_api.ConnectorService/CheckKeyExisting"
)

// ConnectorServiceClient is the client API for ConnectorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConnectorServiceClient interface {
	CreatePassword(ctx context.Context, in *CreatePasswordRequest, opts ...grpc.CallOption) (*CreatePasswordResponse, error)
	CheckPassword(ctx context.Context, in *CheckPasswordRequest, opts ...grpc.CallOption) (*CheckPasswordResponse, error)
	DeletePassword(ctx context.Context, in *DeletePasswordRequest, opts ...grpc.CallOption) (*DeletePasswordResponse, error)
	CreatePrivateKey(ctx context.Context, in *CreatePrivateKeyRequest, opts ...grpc.CallOption) (*CreatePrivateKeyResponse, error)
	GetPublicKey(ctx context.Context, in *GetPublicKeyRequest, opts ...grpc.CallOption) (*GetPublicKeyResponse, error)
	DeletePrivateKey(ctx context.Context, in *DeletePrivateKeyRequest, opts ...grpc.CallOption) (*DeletePrivateKeyResponse, error)
	SaveData(ctx context.Context, in *SaveDataRequest, opts ...grpc.CallOption) (*SaveDataResponse, error)
	DeleteData(ctx context.Context, in *DeleteDataRequest, opts ...grpc.CallOption) (*DeleteDataResponse, error)
	DecryptData(ctx context.Context, in *DecryptDataRequest, opts ...grpc.CallOption) (*DecryptDataResponse, error)
	GetData(ctx context.Context, in *GetDataRequest, opts ...grpc.CallOption) (*GetDataResponse, error)
	CheckKeyExisting(ctx context.Context, in *CheckKeyExistingRequest, opts ...grpc.CallOption) (*CheckKeyExistingResponse, error)
}

type connectorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConnectorServiceClient(cc grpc.ClientConnInterface) ConnectorServiceClient {
	return &connectorServiceClient{cc}
}

func (c *connectorServiceClient) CreatePassword(ctx context.Context, in *CreatePasswordRequest, opts ...grpc.CallOption) (*CreatePasswordResponse, error) {
	out := new(CreatePasswordResponse)
	err := c.cc.Invoke(ctx, ConnectorService_CreatePassword_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorServiceClient) CheckPassword(ctx context.Context, in *CheckPasswordRequest, opts ...grpc.CallOption) (*CheckPasswordResponse, error) {
	out := new(CheckPasswordResponse)
	err := c.cc.Invoke(ctx, ConnectorService_CheckPassword_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorServiceClient) DeletePassword(ctx context.Context, in *DeletePasswordRequest, opts ...grpc.CallOption) (*DeletePasswordResponse, error) {
	out := new(DeletePasswordResponse)
	err := c.cc.Invoke(ctx, ConnectorService_DeletePassword_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorServiceClient) CreatePrivateKey(ctx context.Context, in *CreatePrivateKeyRequest, opts ...grpc.CallOption) (*CreatePrivateKeyResponse, error) {
	out := new(CreatePrivateKeyResponse)
	err := c.cc.Invoke(ctx, ConnectorService_CreatePrivateKey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorServiceClient) GetPublicKey(ctx context.Context, in *GetPublicKeyRequest, opts ...grpc.CallOption) (*GetPublicKeyResponse, error) {
	out := new(GetPublicKeyResponse)
	err := c.cc.Invoke(ctx, ConnectorService_GetPublicKey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorServiceClient) DeletePrivateKey(ctx context.Context, in *DeletePrivateKeyRequest, opts ...grpc.CallOption) (*DeletePrivateKeyResponse, error) {
	out := new(DeletePrivateKeyResponse)
	err := c.cc.Invoke(ctx, ConnectorService_DeletePrivateKey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorServiceClient) SaveData(ctx context.Context, in *SaveDataRequest, opts ...grpc.CallOption) (*SaveDataResponse, error) {
	out := new(SaveDataResponse)
	err := c.cc.Invoke(ctx, ConnectorService_SaveData_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorServiceClient) DeleteData(ctx context.Context, in *DeleteDataRequest, opts ...grpc.CallOption) (*DeleteDataResponse, error) {
	out := new(DeleteDataResponse)
	err := c.cc.Invoke(ctx, ConnectorService_DeleteData_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorServiceClient) DecryptData(ctx context.Context, in *DecryptDataRequest, opts ...grpc.CallOption) (*DecryptDataResponse, error) {
	out := new(DecryptDataResponse)
	err := c.cc.Invoke(ctx, ConnectorService_DecryptData_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorServiceClient) GetData(ctx context.Context, in *GetDataRequest, opts ...grpc.CallOption) (*GetDataResponse, error) {
	out := new(GetDataResponse)
	err := c.cc.Invoke(ctx, ConnectorService_GetData_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorServiceClient) CheckKeyExisting(ctx context.Context, in *CheckKeyExistingRequest, opts ...grpc.CallOption) (*CheckKeyExistingResponse, error) {
	out := new(CheckKeyExistingResponse)
	err := c.cc.Invoke(ctx, ConnectorService_CheckKeyExisting_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConnectorServiceServer is the server API for ConnectorService service.
// All implementations must embed UnimplementedConnectorServiceServer
// for forward compatibility
type ConnectorServiceServer interface {
	CreatePassword(context.Context, *CreatePasswordRequest) (*CreatePasswordResponse, error)
	CheckPassword(context.Context, *CheckPasswordRequest) (*CheckPasswordResponse, error)
	DeletePassword(context.Context, *DeletePasswordRequest) (*DeletePasswordResponse, error)
	CreatePrivateKey(context.Context, *CreatePrivateKeyRequest) (*CreatePrivateKeyResponse, error)
	GetPublicKey(context.Context, *GetPublicKeyRequest) (*GetPublicKeyResponse, error)
	DeletePrivateKey(context.Context, *DeletePrivateKeyRequest) (*DeletePrivateKeyResponse, error)
	SaveData(context.Context, *SaveDataRequest) (*SaveDataResponse, error)
	DeleteData(context.Context, *DeleteDataRequest) (*DeleteDataResponse, error)
	DecryptData(context.Context, *DecryptDataRequest) (*DecryptDataResponse, error)
	GetData(context.Context, *GetDataRequest) (*GetDataResponse, error)
	CheckKeyExisting(context.Context, *CheckKeyExistingRequest) (*CheckKeyExistingResponse, error)
	mustEmbedUnimplementedConnectorServiceServer()
}

// UnimplementedConnectorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedConnectorServiceServer struct {
}

func (UnimplementedConnectorServiceServer) CreatePassword(context.Context, *CreatePasswordRequest) (*CreatePasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePassword not implemented")
}
func (UnimplementedConnectorServiceServer) CheckPassword(context.Context, *CheckPasswordRequest) (*CheckPasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckPassword not implemented")
}
func (UnimplementedConnectorServiceServer) DeletePassword(context.Context, *DeletePasswordRequest) (*DeletePasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePassword not implemented")
}
func (UnimplementedConnectorServiceServer) CreatePrivateKey(context.Context, *CreatePrivateKeyRequest) (*CreatePrivateKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePrivateKey not implemented")
}
func (UnimplementedConnectorServiceServer) GetPublicKey(context.Context, *GetPublicKeyRequest) (*GetPublicKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPublicKey not implemented")
}
func (UnimplementedConnectorServiceServer) DeletePrivateKey(context.Context, *DeletePrivateKeyRequest) (*DeletePrivateKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePrivateKey not implemented")
}
func (UnimplementedConnectorServiceServer) SaveData(context.Context, *SaveDataRequest) (*SaveDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveData not implemented")
}
func (UnimplementedConnectorServiceServer) DeleteData(context.Context, *DeleteDataRequest) (*DeleteDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteData not implemented")
}
func (UnimplementedConnectorServiceServer) DecryptData(context.Context, *DecryptDataRequest) (*DecryptDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecryptData not implemented")
}
func (UnimplementedConnectorServiceServer) GetData(context.Context, *GetDataRequest) (*GetDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetData not implemented")
}
func (UnimplementedConnectorServiceServer) CheckKeyExisting(context.Context, *CheckKeyExistingRequest) (*CheckKeyExistingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckKeyExisting not implemented")
}
func (UnimplementedConnectorServiceServer) mustEmbedUnimplementedConnectorServiceServer() {}

// UnsafeConnectorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConnectorServiceServer will
// result in compilation errors.
type UnsafeConnectorServiceServer interface {
	mustEmbedUnimplementedConnectorServiceServer()
}

func RegisterConnectorServiceServer(s grpc.ServiceRegistrar, srv ConnectorServiceServer) {
	s.RegisterService(&ConnectorService_ServiceDesc, srv)
}

func _ConnectorService_CreatePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorServiceServer).CreatePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectorService_CreatePassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorServiceServer).CreatePassword(ctx, req.(*CreatePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectorService_CheckPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorServiceServer).CheckPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectorService_CheckPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorServiceServer).CheckPassword(ctx, req.(*CheckPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectorService_DeletePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorServiceServer).DeletePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectorService_DeletePassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorServiceServer).DeletePassword(ctx, req.(*DeletePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectorService_CreatePrivateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePrivateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorServiceServer).CreatePrivateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectorService_CreatePrivateKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorServiceServer).CreatePrivateKey(ctx, req.(*CreatePrivateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectorService_GetPublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublicKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorServiceServer).GetPublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectorService_GetPublicKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorServiceServer).GetPublicKey(ctx, req.(*GetPublicKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectorService_DeletePrivateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePrivateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorServiceServer).DeletePrivateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectorService_DeletePrivateKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorServiceServer).DeletePrivateKey(ctx, req.(*DeletePrivateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectorService_SaveData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorServiceServer).SaveData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectorService_SaveData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorServiceServer).SaveData(ctx, req.(*SaveDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectorService_DeleteData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorServiceServer).DeleteData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectorService_DeleteData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorServiceServer).DeleteData(ctx, req.(*DeleteDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectorService_DecryptData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecryptDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorServiceServer).DecryptData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectorService_DecryptData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorServiceServer).DecryptData(ctx, req.(*DecryptDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectorService_GetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorServiceServer).GetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectorService_GetData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorServiceServer).GetData(ctx, req.(*GetDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectorService_CheckKeyExisting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckKeyExistingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorServiceServer).CheckKeyExisting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectorService_CheckKeyExisting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorServiceServer).CheckKeyExisting(ctx, req.(*CheckKeyExistingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConnectorService_ServiceDesc is the grpc.ServiceDesc for ConnectorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConnectorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "connector_api.ConnectorService",
	HandlerType: (*ConnectorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePassword",
			Handler:    _ConnectorService_CreatePassword_Handler,
		},
		{
			MethodName: "CheckPassword",
			Handler:    _ConnectorService_CheckPassword_Handler,
		},
		{
			MethodName: "DeletePassword",
			Handler:    _ConnectorService_DeletePassword_Handler,
		},
		{
			MethodName: "CreatePrivateKey",
			Handler:    _ConnectorService_CreatePrivateKey_Handler,
		},
		{
			MethodName: "GetPublicKey",
			Handler:    _ConnectorService_GetPublicKey_Handler,
		},
		{
			MethodName: "DeletePrivateKey",
			Handler:    _ConnectorService_DeletePrivateKey_Handler,
		},
		{
			MethodName: "SaveData",
			Handler:    _ConnectorService_SaveData_Handler,
		},
		{
			MethodName: "DeleteData",
			Handler:    _ConnectorService_DeleteData_Handler,
		},
		{
			MethodName: "DecryptData",
			Handler:    _ConnectorService_DecryptData_Handler,
		},
		{
			MethodName: "GetData",
			Handler:    _ConnectorService_GetData_Handler,
		},
		{
			MethodName: "CheckKeyExisting",
			Handler:    _ConnectorService_CheckKeyExisting_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/connector.proto",
}

const (
	ConnectorConsoleService_GetLogs_FullMethodName               = "/connector_api.ConnectorConsoleService/GetLogs"
	ConnectorConsoleService_GetMonitorInfos_FullMethodName       = "/connector_api.ConnectorConsoleService/GetMonitorInfos"
	ConnectorConsoleService_ListConfigs_FullMethodName           = "/connector_api.ConnectorConsoleService/ListConfigs"
	ConnectorConsoleService_CreateConfig_FullMethodName          = "/connector_api.ConnectorConsoleService/CreateConfig"
	ConnectorConsoleService_UpdateConfig_FullMethodName          = "/connector_api.ConnectorConsoleService/UpdateConfig"
	ConnectorConsoleService_DeleteConfig_FullMethodName          = "/connector_api.ConnectorConsoleService/DeleteConfig"
	ConnectorConsoleService_ListPassword_FullMethodName          = "/connector_api.ConnectorConsoleService/ListPassword"
	ConnectorConsoleService_AddPassword_FullMethodName           = "/connector_api.ConnectorConsoleService/AddPassword"
	ConnectorConsoleService_RemovePassword_FullMethodName        = "/connector_api.ConnectorConsoleService/RemovePassword"
	ConnectorConsoleService_FetchPassword_FullMethodName         = "/connector_api.ConnectorConsoleService/FetchPassword"
	ConnectorConsoleService_ListPrivateKey_FullMethodName        = "/connector_api.ConnectorConsoleService/ListPrivateKey"
	ConnectorConsoleService_AddPrivateKey_FullMethodName         = "/connector_api.ConnectorConsoleService/AddPrivateKey"
	ConnectorConsoleService_RemovePrivateKey_FullMethodName      = "/connector_api.ConnectorConsoleService/RemovePrivateKey"
	ConnectorConsoleService_GetAllApps_FullMethodName            = "/connector_api.ConnectorConsoleService/GetAllApps"
	ConnectorConsoleService_GetAllKeyIDs_FullMethodName          = "/connector_api.ConnectorConsoleService/GetAllKeyIDs"
	ConnectorConsoleService_ListApiKey_FullMethodName            = "/connector_api.ConnectorConsoleService/ListApiKey"
	ConnectorConsoleService_AddApiKey_FullMethodName             = "/connector_api.ConnectorConsoleService/AddApiKey"
	ConnectorConsoleService_RemoveApiKey_FullMethodName          = "/connector_api.ConnectorConsoleService/RemoveApiKey"
	ConnectorConsoleService_ValidateApiKey_FullMethodName        = "/connector_api.ConnectorConsoleService/ValidateApiKey"
	ConnectorConsoleService_GetManagePlatformLogs_FullMethodName = "/connector_api.ConnectorConsoleService/GetManagePlatformLogs"
)

// ConnectorConsoleServiceClient is the client API for ConnectorConsoleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConnectorConsoleServiceClient interface {
	GetLogs(ctx context.Context, in *GetLogsRequest, opts ...grpc.CallOption) (*GetLogsResponse, error)
	GetMonitorInfos(ctx context.Context, in *GetMonitorInfosRequest, opts ...grpc.CallOption) (*GetMonitorInfosResponse, error)
	ListConfigs(ctx context.Context, in *ListConfigsRequest, opts ...grpc.CallOption) (*ListConfigsResponse, error)
	CreateConfig(ctx context.Context, in *CreateConfigRequest, opts ...grpc.CallOption) (*CreateConfigResponse, error)
	UpdateConfig(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*UpdateConfigResponse, error)
	DeleteConfig(ctx context.Context, in *DeleteConfigRequest, opts ...grpc.CallOption) (*DeleteConfigResponse, error)
	ListPassword(ctx context.Context, in *ListPasswordRequest, opts ...grpc.CallOption) (*ListPasswordResponse, error)
	AddPassword(ctx context.Context, in *AddPasswordRequest, opts ...grpc.CallOption) (*AddPasswordResponse, error)
	RemovePassword(ctx context.Context, in *RemovePasswordRequest, opts ...grpc.CallOption) (*RemovePasswordResponse, error)
	FetchPassword(ctx context.Context, in *FetchPasswordRequest, opts ...grpc.CallOption) (*FetchPasswordResponse, error)
	ListPrivateKey(ctx context.Context, in *ListPrivateKeyRequest, opts ...grpc.CallOption) (*ListPrivateKeyResponse, error)
	AddPrivateKey(ctx context.Context, in *AddPrivateKeyRequest, opts ...grpc.CallOption) (*AddPrivateKeyResponse, error)
	RemovePrivateKey(ctx context.Context, in *RemovePrivateKeyRequest, opts ...grpc.CallOption) (*RemovePrivateKeyResponse, error)
	GetAllApps(ctx context.Context, in *GetAllAppsRequest, opts ...grpc.CallOption) (*GetAllAppsResponse, error)
	GetAllKeyIDs(ctx context.Context, in *GetAllKeyIDsRequest, opts ...grpc.CallOption) (*GetAllKeyIDsResponse, error)
	ListApiKey(ctx context.Context, in *ListApiKeyRequest, opts ...grpc.CallOption) (*ListApiKeyResponse, error)
	AddApiKey(ctx context.Context, in *AddApiKeyRequest, opts ...grpc.CallOption) (*AddApiKeyResponse, error)
	RemoveApiKey(ctx context.Context, in *RemoveApiKeyRequest, opts ...grpc.CallOption) (*RemoveApiKeyResponse, error)
	ValidateApiKey(ctx context.Context, in *ValidateApiKeyRequest, opts ...grpc.CallOption) (*ValidateApiKeyResponse, error)
	GetManagePlatformLogs(ctx context.Context, in *GetManagePlatformLogsRequest, opts ...grpc.CallOption) (*GetManagePlatformLogsResponse, error)
}

type connectorConsoleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConnectorConsoleServiceClient(cc grpc.ClientConnInterface) ConnectorConsoleServiceClient {
	return &connectorConsoleServiceClient{cc}
}

func (c *connectorConsoleServiceClient) GetLogs(ctx context.Context, in *GetLogsRequest, opts ...grpc.CallOption) (*GetLogsResponse, error) {
	out := new(GetLogsResponse)
	err := c.cc.Invoke(ctx, ConnectorConsoleService_GetLogs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorConsoleServiceClient) GetMonitorInfos(ctx context.Context, in *GetMonitorInfosRequest, opts ...grpc.CallOption) (*GetMonitorInfosResponse, error) {
	out := new(GetMonitorInfosResponse)
	err := c.cc.Invoke(ctx, ConnectorConsoleService_GetMonitorInfos_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorConsoleServiceClient) ListConfigs(ctx context.Context, in *ListConfigsRequest, opts ...grpc.CallOption) (*ListConfigsResponse, error) {
	out := new(ListConfigsResponse)
	err := c.cc.Invoke(ctx, ConnectorConsoleService_ListConfigs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorConsoleServiceClient) CreateConfig(ctx context.Context, in *CreateConfigRequest, opts ...grpc.CallOption) (*CreateConfigResponse, error) {
	out := new(CreateConfigResponse)
	err := c.cc.Invoke(ctx, ConnectorConsoleService_CreateConfig_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorConsoleServiceClient) UpdateConfig(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*UpdateConfigResponse, error) {
	out := new(UpdateConfigResponse)
	err := c.cc.Invoke(ctx, ConnectorConsoleService_UpdateConfig_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorConsoleServiceClient) DeleteConfig(ctx context.Context, in *DeleteConfigRequest, opts ...grpc.CallOption) (*DeleteConfigResponse, error) {
	out := new(DeleteConfigResponse)
	err := c.cc.Invoke(ctx, ConnectorConsoleService_DeleteConfig_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorConsoleServiceClient) ListPassword(ctx context.Context, in *ListPasswordRequest, opts ...grpc.CallOption) (*ListPasswordResponse, error) {
	out := new(ListPasswordResponse)
	err := c.cc.Invoke(ctx, ConnectorConsoleService_ListPassword_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorConsoleServiceClient) AddPassword(ctx context.Context, in *AddPasswordRequest, opts ...grpc.CallOption) (*AddPasswordResponse, error) {
	out := new(AddPasswordResponse)
	err := c.cc.Invoke(ctx, ConnectorConsoleService_AddPassword_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorConsoleServiceClient) RemovePassword(ctx context.Context, in *RemovePasswordRequest, opts ...grpc.CallOption) (*RemovePasswordResponse, error) {
	out := new(RemovePasswordResponse)
	err := c.cc.Invoke(ctx, ConnectorConsoleService_RemovePassword_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorConsoleServiceClient) FetchPassword(ctx context.Context, in *FetchPasswordRequest, opts ...grpc.CallOption) (*FetchPasswordResponse, error) {
	out := new(FetchPasswordResponse)
	err := c.cc.Invoke(ctx, ConnectorConsoleService_FetchPassword_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorConsoleServiceClient) ListPrivateKey(ctx context.Context, in *ListPrivateKeyRequest, opts ...grpc.CallOption) (*ListPrivateKeyResponse, error) {
	out := new(ListPrivateKeyResponse)
	err := c.cc.Invoke(ctx, ConnectorConsoleService_ListPrivateKey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorConsoleServiceClient) AddPrivateKey(ctx context.Context, in *AddPrivateKeyRequest, opts ...grpc.CallOption) (*AddPrivateKeyResponse, error) {
	out := new(AddPrivateKeyResponse)
	err := c.cc.Invoke(ctx, ConnectorConsoleService_AddPrivateKey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorConsoleServiceClient) RemovePrivateKey(ctx context.Context, in *RemovePrivateKeyRequest, opts ...grpc.CallOption) (*RemovePrivateKeyResponse, error) {
	out := new(RemovePrivateKeyResponse)
	err := c.cc.Invoke(ctx, ConnectorConsoleService_RemovePrivateKey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorConsoleServiceClient) GetAllApps(ctx context.Context, in *GetAllAppsRequest, opts ...grpc.CallOption) (*GetAllAppsResponse, error) {
	out := new(GetAllAppsResponse)
	err := c.cc.Invoke(ctx, ConnectorConsoleService_GetAllApps_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorConsoleServiceClient) GetAllKeyIDs(ctx context.Context, in *GetAllKeyIDsRequest, opts ...grpc.CallOption) (*GetAllKeyIDsResponse, error) {
	out := new(GetAllKeyIDsResponse)
	err := c.cc.Invoke(ctx, ConnectorConsoleService_GetAllKeyIDs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorConsoleServiceClient) ListApiKey(ctx context.Context, in *ListApiKeyRequest, opts ...grpc.CallOption) (*ListApiKeyResponse, error) {
	out := new(ListApiKeyResponse)
	err := c.cc.Invoke(ctx, ConnectorConsoleService_ListApiKey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorConsoleServiceClient) AddApiKey(ctx context.Context, in *AddApiKeyRequest, opts ...grpc.CallOption) (*AddApiKeyResponse, error) {
	out := new(AddApiKeyResponse)
	err := c.cc.Invoke(ctx, ConnectorConsoleService_AddApiKey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorConsoleServiceClient) RemoveApiKey(ctx context.Context, in *RemoveApiKeyRequest, opts ...grpc.CallOption) (*RemoveApiKeyResponse, error) {
	out := new(RemoveApiKeyResponse)
	err := c.cc.Invoke(ctx, ConnectorConsoleService_RemoveApiKey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorConsoleServiceClient) ValidateApiKey(ctx context.Context, in *ValidateApiKeyRequest, opts ...grpc.CallOption) (*ValidateApiKeyResponse, error) {
	out := new(ValidateApiKeyResponse)
	err := c.cc.Invoke(ctx, ConnectorConsoleService_ValidateApiKey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorConsoleServiceClient) GetManagePlatformLogs(ctx context.Context, in *GetManagePlatformLogsRequest, opts ...grpc.CallOption) (*GetManagePlatformLogsResponse, error) {
	out := new(GetManagePlatformLogsResponse)
	err := c.cc.Invoke(ctx, ConnectorConsoleService_GetManagePlatformLogs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConnectorConsoleServiceServer is the server API for ConnectorConsoleService service.
// All implementations must embed UnimplementedConnectorConsoleServiceServer
// for forward compatibility
type ConnectorConsoleServiceServer interface {
	GetLogs(context.Context, *GetLogsRequest) (*GetLogsResponse, error)
	GetMonitorInfos(context.Context, *GetMonitorInfosRequest) (*GetMonitorInfosResponse, error)
	ListConfigs(context.Context, *ListConfigsRequest) (*ListConfigsResponse, error)
	CreateConfig(context.Context, *CreateConfigRequest) (*CreateConfigResponse, error)
	UpdateConfig(context.Context, *UpdateConfigRequest) (*UpdateConfigResponse, error)
	DeleteConfig(context.Context, *DeleteConfigRequest) (*DeleteConfigResponse, error)
	ListPassword(context.Context, *ListPasswordRequest) (*ListPasswordResponse, error)
	AddPassword(context.Context, *AddPasswordRequest) (*AddPasswordResponse, error)
	RemovePassword(context.Context, *RemovePasswordRequest) (*RemovePasswordResponse, error)
	FetchPassword(context.Context, *FetchPasswordRequest) (*FetchPasswordResponse, error)
	ListPrivateKey(context.Context, *ListPrivateKeyRequest) (*ListPrivateKeyResponse, error)
	AddPrivateKey(context.Context, *AddPrivateKeyRequest) (*AddPrivateKeyResponse, error)
	RemovePrivateKey(context.Context, *RemovePrivateKeyRequest) (*RemovePrivateKeyResponse, error)
	GetAllApps(context.Context, *GetAllAppsRequest) (*GetAllAppsResponse, error)
	GetAllKeyIDs(context.Context, *GetAllKeyIDsRequest) (*GetAllKeyIDsResponse, error)
	ListApiKey(context.Context, *ListApiKeyRequest) (*ListApiKeyResponse, error)
	AddApiKey(context.Context, *AddApiKeyRequest) (*AddApiKeyResponse, error)
	RemoveApiKey(context.Context, *RemoveApiKeyRequest) (*RemoveApiKeyResponse, error)
	ValidateApiKey(context.Context, *ValidateApiKeyRequest) (*ValidateApiKeyResponse, error)
	GetManagePlatformLogs(context.Context, *GetManagePlatformLogsRequest) (*GetManagePlatformLogsResponse, error)
	mustEmbedUnimplementedConnectorConsoleServiceServer()
}

// UnimplementedConnectorConsoleServiceServer must be embedded to have forward compatible implementations.
type UnimplementedConnectorConsoleServiceServer struct {
}

func (UnimplementedConnectorConsoleServiceServer) GetLogs(context.Context, *GetLogsRequest) (*GetLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLogs not implemented")
}
func (UnimplementedConnectorConsoleServiceServer) GetMonitorInfos(context.Context, *GetMonitorInfosRequest) (*GetMonitorInfosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMonitorInfos not implemented")
}
func (UnimplementedConnectorConsoleServiceServer) ListConfigs(context.Context, *ListConfigsRequest) (*ListConfigsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListConfigs not implemented")
}
func (UnimplementedConnectorConsoleServiceServer) CreateConfig(context.Context, *CreateConfigRequest) (*CreateConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateConfig not implemented")
}
func (UnimplementedConnectorConsoleServiceServer) UpdateConfig(context.Context, *UpdateConfigRequest) (*UpdateConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateConfig not implemented")
}
func (UnimplementedConnectorConsoleServiceServer) DeleteConfig(context.Context, *DeleteConfigRequest) (*DeleteConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteConfig not implemented")
}
func (UnimplementedConnectorConsoleServiceServer) ListPassword(context.Context, *ListPasswordRequest) (*ListPasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPassword not implemented")
}
func (UnimplementedConnectorConsoleServiceServer) AddPassword(context.Context, *AddPasswordRequest) (*AddPasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPassword not implemented")
}
func (UnimplementedConnectorConsoleServiceServer) RemovePassword(context.Context, *RemovePasswordRequest) (*RemovePasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemovePassword not implemented")
}
func (UnimplementedConnectorConsoleServiceServer) FetchPassword(context.Context, *FetchPasswordRequest) (*FetchPasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchPassword not implemented")
}
func (UnimplementedConnectorConsoleServiceServer) ListPrivateKey(context.Context, *ListPrivateKeyRequest) (*ListPrivateKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPrivateKey not implemented")
}
func (UnimplementedConnectorConsoleServiceServer) AddPrivateKey(context.Context, *AddPrivateKeyRequest) (*AddPrivateKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPrivateKey not implemented")
}
func (UnimplementedConnectorConsoleServiceServer) RemovePrivateKey(context.Context, *RemovePrivateKeyRequest) (*RemovePrivateKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemovePrivateKey not implemented")
}
func (UnimplementedConnectorConsoleServiceServer) GetAllApps(context.Context, *GetAllAppsRequest) (*GetAllAppsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllApps not implemented")
}
func (UnimplementedConnectorConsoleServiceServer) GetAllKeyIDs(context.Context, *GetAllKeyIDsRequest) (*GetAllKeyIDsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllKeyIDs not implemented")
}
func (UnimplementedConnectorConsoleServiceServer) ListApiKey(context.Context, *ListApiKeyRequest) (*ListApiKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListApiKey not implemented")
}
func (UnimplementedConnectorConsoleServiceServer) AddApiKey(context.Context, *AddApiKeyRequest) (*AddApiKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddApiKey not implemented")
}
func (UnimplementedConnectorConsoleServiceServer) RemoveApiKey(context.Context, *RemoveApiKeyRequest) (*RemoveApiKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveApiKey not implemented")
}
func (UnimplementedConnectorConsoleServiceServer) ValidateApiKey(context.Context, *ValidateApiKeyRequest) (*ValidateApiKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateApiKey not implemented")
}
func (UnimplementedConnectorConsoleServiceServer) GetManagePlatformLogs(context.Context, *GetManagePlatformLogsRequest) (*GetManagePlatformLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetManagePlatformLogs not implemented")
}
func (UnimplementedConnectorConsoleServiceServer) mustEmbedUnimplementedConnectorConsoleServiceServer() {
}

// UnsafeConnectorConsoleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConnectorConsoleServiceServer will
// result in compilation errors.
type UnsafeConnectorConsoleServiceServer interface {
	mustEmbedUnimplementedConnectorConsoleServiceServer()
}

func RegisterConnectorConsoleServiceServer(s grpc.ServiceRegistrar, srv ConnectorConsoleServiceServer) {
	s.RegisterService(&ConnectorConsoleService_ServiceDesc, srv)
}

func _ConnectorConsoleService_GetLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorConsoleServiceServer).GetLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectorConsoleService_GetLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorConsoleServiceServer).GetLogs(ctx, req.(*GetLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectorConsoleService_GetMonitorInfos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMonitorInfosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorConsoleServiceServer).GetMonitorInfos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectorConsoleService_GetMonitorInfos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorConsoleServiceServer).GetMonitorInfos(ctx, req.(*GetMonitorInfosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectorConsoleService_ListConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConfigsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorConsoleServiceServer).ListConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectorConsoleService_ListConfigs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorConsoleServiceServer).ListConfigs(ctx, req.(*ListConfigsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectorConsoleService_CreateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorConsoleServiceServer).CreateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectorConsoleService_CreateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorConsoleServiceServer).CreateConfig(ctx, req.(*CreateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectorConsoleService_UpdateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorConsoleServiceServer).UpdateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectorConsoleService_UpdateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorConsoleServiceServer).UpdateConfig(ctx, req.(*UpdateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectorConsoleService_DeleteConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorConsoleServiceServer).DeleteConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectorConsoleService_DeleteConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorConsoleServiceServer).DeleteConfig(ctx, req.(*DeleteConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectorConsoleService_ListPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorConsoleServiceServer).ListPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectorConsoleService_ListPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorConsoleServiceServer).ListPassword(ctx, req.(*ListPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectorConsoleService_AddPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorConsoleServiceServer).AddPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectorConsoleService_AddPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorConsoleServiceServer).AddPassword(ctx, req.(*AddPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectorConsoleService_RemovePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorConsoleServiceServer).RemovePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectorConsoleService_RemovePassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorConsoleServiceServer).RemovePassword(ctx, req.(*RemovePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectorConsoleService_FetchPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorConsoleServiceServer).FetchPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectorConsoleService_FetchPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorConsoleServiceServer).FetchPassword(ctx, req.(*FetchPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectorConsoleService_ListPrivateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPrivateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorConsoleServiceServer).ListPrivateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectorConsoleService_ListPrivateKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorConsoleServiceServer).ListPrivateKey(ctx, req.(*ListPrivateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectorConsoleService_AddPrivateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPrivateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorConsoleServiceServer).AddPrivateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectorConsoleService_AddPrivateKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorConsoleServiceServer).AddPrivateKey(ctx, req.(*AddPrivateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectorConsoleService_RemovePrivateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePrivateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorConsoleServiceServer).RemovePrivateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectorConsoleService_RemovePrivateKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorConsoleServiceServer).RemovePrivateKey(ctx, req.(*RemovePrivateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectorConsoleService_GetAllApps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllAppsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorConsoleServiceServer).GetAllApps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectorConsoleService_GetAllApps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorConsoleServiceServer).GetAllApps(ctx, req.(*GetAllAppsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectorConsoleService_GetAllKeyIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllKeyIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorConsoleServiceServer).GetAllKeyIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectorConsoleService_GetAllKeyIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorConsoleServiceServer).GetAllKeyIDs(ctx, req.(*GetAllKeyIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectorConsoleService_ListApiKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListApiKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorConsoleServiceServer).ListApiKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectorConsoleService_ListApiKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorConsoleServiceServer).ListApiKey(ctx, req.(*ListApiKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectorConsoleService_AddApiKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddApiKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorConsoleServiceServer).AddApiKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectorConsoleService_AddApiKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorConsoleServiceServer).AddApiKey(ctx, req.(*AddApiKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectorConsoleService_RemoveApiKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveApiKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorConsoleServiceServer).RemoveApiKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectorConsoleService_RemoveApiKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorConsoleServiceServer).RemoveApiKey(ctx, req.(*RemoveApiKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectorConsoleService_ValidateApiKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateApiKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorConsoleServiceServer).ValidateApiKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectorConsoleService_ValidateApiKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorConsoleServiceServer).ValidateApiKey(ctx, req.(*ValidateApiKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectorConsoleService_GetManagePlatformLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetManagePlatformLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorConsoleServiceServer).GetManagePlatformLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectorConsoleService_GetManagePlatformLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorConsoleServiceServer).GetManagePlatformLogs(ctx, req.(*GetManagePlatformLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConnectorConsoleService_ServiceDesc is the grpc.ServiceDesc for ConnectorConsoleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConnectorConsoleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "connector_api.ConnectorConsoleService",
	HandlerType: (*ConnectorConsoleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLogs",
			Handler:    _ConnectorConsoleService_GetLogs_Handler,
		},
		{
			MethodName: "GetMonitorInfos",
			Handler:    _ConnectorConsoleService_GetMonitorInfos_Handler,
		},
		{
			MethodName: "ListConfigs",
			Handler:    _ConnectorConsoleService_ListConfigs_Handler,
		},
		{
			MethodName: "CreateConfig",
			Handler:    _ConnectorConsoleService_CreateConfig_Handler,
		},
		{
			MethodName: "UpdateConfig",
			Handler:    _ConnectorConsoleService_UpdateConfig_Handler,
		},
		{
			MethodName: "DeleteConfig",
			Handler:    _ConnectorConsoleService_DeleteConfig_Handler,
		},
		{
			MethodName: "ListPassword",
			Handler:    _ConnectorConsoleService_ListPassword_Handler,
		},
		{
			MethodName: "AddPassword",
			Handler:    _ConnectorConsoleService_AddPassword_Handler,
		},
		{
			MethodName: "RemovePassword",
			Handler:    _ConnectorConsoleService_RemovePassword_Handler,
		},
		{
			MethodName: "FetchPassword",
			Handler:    _ConnectorConsoleService_FetchPassword_Handler,
		},
		{
			MethodName: "ListPrivateKey",
			Handler:    _ConnectorConsoleService_ListPrivateKey_Handler,
		},
		{
			MethodName: "AddPrivateKey",
			Handler:    _ConnectorConsoleService_AddPrivateKey_Handler,
		},
		{
			MethodName: "RemovePrivateKey",
			Handler:    _ConnectorConsoleService_RemovePrivateKey_Handler,
		},
		{
			MethodName: "GetAllApps",
			Handler:    _ConnectorConsoleService_GetAllApps_Handler,
		},
		{
			MethodName: "GetAllKeyIDs",
			Handler:    _ConnectorConsoleService_GetAllKeyIDs_Handler,
		},
		{
			MethodName: "ListApiKey",
			Handler:    _ConnectorConsoleService_ListApiKey_Handler,
		},
		{
			MethodName: "AddApiKey",
			Handler:    _ConnectorConsoleService_AddApiKey_Handler,
		},
		{
			MethodName: "RemoveApiKey",
			Handler:    _ConnectorConsoleService_RemoveApiKey_Handler,
		},
		{
			MethodName: "ValidateApiKey",
			Handler:    _ConnectorConsoleService_ValidateApiKey_Handler,
		},
		{
			MethodName: "GetManagePlatformLogs",
			Handler:    _ConnectorConsoleService_GetManagePlatformLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/connector.proto",
}
