// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTranslation = "translation"

// Translation mapped from table <translation>
type Translation struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt    time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt    int64     `gorm:"column:deleted_at;not null;comment:Coding style" json:"deleted_at"`                  // Coding style
	ItemType     string    `gorm:"column:item_type;not null;comment:definition or example" json:"item_type"`           // definition or example
	ItemID       int64     `gorm:"column:item_id;not null;comment:definition id or example id" json:"item_id"`         // definition id or example id
	Content      string    `gorm:"column:content;not null;comment:content of the translation" json:"content"`          // content of the translation
	LanguageCode string    `gorm:"column:language_code;not null;comment:ISO 639-1 language code" json:"language_code"` // ISO 639-1 language code
}

// TableName Translation's table name
func (*Translation) TableName() string {
	return TableNameTranslation
}
