// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: api/tester.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TesterService_UpdateAPITestcase_FullMethodName               = "/tester_api.TesterService/UpdateAPITestcase"
	TesterService_GetApps_FullMethodName                         = "/tester_api.TesterService/GetApps"
	TesterService_GetAPITestcases_FullMethodName                 = "/tester_api.TesterService/GetAPITestcases"
	TesterService_GetMysqlInfo_FullMethodName                    = "/tester_api.TesterService/GetMysqlInfo"
	TesterService_GetMongoInfo_FullMethodName                    = "/tester_api.TesterService/GetMongoInfo"
	TesterService_GetBtcDiff_FullMethodName                      = "/tester_api.TesterService/GetBtcDiff"
	TesterService_GetTxsMempoolInfo_FullMethodName               = "/tester_api.TesterService/GetTxsMempoolInfo"
	TesterService_GetSlarkRegistrationCaptchas_FullMethodName    = "/tester_api.TesterService/GetSlarkRegistrationCaptchas"
	TesterService_GetSlarkLoginCaptchas_FullMethodName           = "/tester_api.TesterService/GetSlarkLoginCaptchas"
	TesterService_UploadApp_FullMethodName                       = "/tester_api.TesterService/UploadApp"
	TesterService_GetUploadedApps_FullMethodName                 = "/tester_api.TesterService/GetUploadedApps"
	TesterService_GetMessageNotificationConfig_FullMethodName    = "/tester_api.TesterService/GetMessageNotificationConfig"
	TesterService_UpdateMessageNotificationConfig_FullMethodName = "/tester_api.TesterService/UpdateMessageNotificationConfig"
	TesterService_SendMessageNotification_FullMethodName         = "/tester_api.TesterService/SendMessageNotification"
	TesterService_GetMessageNotificationLogs_FullMethodName      = "/tester_api.TesterService/GetMessageNotificationLogs"
	TesterService_GetPrivacyEmailAccounts_FullMethodName         = "/tester_api.TesterService/GetPrivacyEmailAccounts"
)

// TesterServiceClient is the client API for TesterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TesterServiceClient interface {
	UpdateAPITestcase(ctx context.Context, in *UpdateAPITestcaseRequest, opts ...grpc.CallOption) (*UpdateAPITestcaseResponse, error)
	GetApps(ctx context.Context, in *GetAppsRequest, opts ...grpc.CallOption) (*GetAppsResponse, error)
	GetAPITestcases(ctx context.Context, in *GetAPITestcasesRequest, opts ...grpc.CallOption) (*GetAPITestcasesResponse, error)
	GetMysqlInfo(ctx context.Context, in *GetMysqlInfoRequest, opts ...grpc.CallOption) (*GetMysqlInfoResponse, error)
	GetMongoInfo(ctx context.Context, in *GetMongoInfoRequest, opts ...grpc.CallOption) (*GetMongoInfoResponse, error)
	GetBtcDiff(ctx context.Context, in *GetBtcDiffRequest, opts ...grpc.CallOption) (*GetBtcDiffResponse, error)
	GetTxsMempoolInfo(ctx context.Context, in *GetTxsMempoolInfoRequest, opts ...grpc.CallOption) (*GetTxsMempoolInfoResponse, error)
	GetSlarkRegistrationCaptchas(ctx context.Context, in *GetSlarkRegistrationCaptchasRequest, opts ...grpc.CallOption) (*GetSlarkRegistrationCaptchasResponse, error)
	GetSlarkLoginCaptchas(ctx context.Context, in *GetSlarkLoginCaptchasRequest, opts ...grpc.CallOption) (*GetSlarkLoginCaptchasResponse, error)
	UploadApp(ctx context.Context, in *UploadAppRequest, opts ...grpc.CallOption) (*UploadAppResponse, error)
	GetUploadedApps(ctx context.Context, in *GetUploadedAppsRequest, opts ...grpc.CallOption) (*GetUploadedAppsResponse, error)
	GetMessageNotificationConfig(ctx context.Context, in *GetMessageNotificationConfigRequest, opts ...grpc.CallOption) (*GetMessageNotificationConfigResponse, error)
	UpdateMessageNotificationConfig(ctx context.Context, in *UpdateMessageNotificationConfigRequest, opts ...grpc.CallOption) (*UpdateMessageNotificationConfigResponse, error)
	SendMessageNotification(ctx context.Context, in *SendMessageNotificationRequest, opts ...grpc.CallOption) (*SendMessageNotificationResponse, error)
	GetMessageNotificationLogs(ctx context.Context, in *GetMessageNotificationLogsRequest, opts ...grpc.CallOption) (*GetMessageNotificationLogsResponse, error)
	GetPrivacyEmailAccounts(ctx context.Context, in *GetPrivacyEmailAccountsRequest, opts ...grpc.CallOption) (*GetPrivacyEmailAccountsResponse, error)
}

type testerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTesterServiceClient(cc grpc.ClientConnInterface) TesterServiceClient {
	return &testerServiceClient{cc}
}

func (c *testerServiceClient) UpdateAPITestcase(ctx context.Context, in *UpdateAPITestcaseRequest, opts ...grpc.CallOption) (*UpdateAPITestcaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAPITestcaseResponse)
	err := c.cc.Invoke(ctx, TesterService_UpdateAPITestcase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testerServiceClient) GetApps(ctx context.Context, in *GetAppsRequest, opts ...grpc.CallOption) (*GetAppsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAppsResponse)
	err := c.cc.Invoke(ctx, TesterService_GetApps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testerServiceClient) GetAPITestcases(ctx context.Context, in *GetAPITestcasesRequest, opts ...grpc.CallOption) (*GetAPITestcasesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAPITestcasesResponse)
	err := c.cc.Invoke(ctx, TesterService_GetAPITestcases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testerServiceClient) GetMysqlInfo(ctx context.Context, in *GetMysqlInfoRequest, opts ...grpc.CallOption) (*GetMysqlInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMysqlInfoResponse)
	err := c.cc.Invoke(ctx, TesterService_GetMysqlInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testerServiceClient) GetMongoInfo(ctx context.Context, in *GetMongoInfoRequest, opts ...grpc.CallOption) (*GetMongoInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMongoInfoResponse)
	err := c.cc.Invoke(ctx, TesterService_GetMongoInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testerServiceClient) GetBtcDiff(ctx context.Context, in *GetBtcDiffRequest, opts ...grpc.CallOption) (*GetBtcDiffResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBtcDiffResponse)
	err := c.cc.Invoke(ctx, TesterService_GetBtcDiff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testerServiceClient) GetTxsMempoolInfo(ctx context.Context, in *GetTxsMempoolInfoRequest, opts ...grpc.CallOption) (*GetTxsMempoolInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTxsMempoolInfoResponse)
	err := c.cc.Invoke(ctx, TesterService_GetTxsMempoolInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testerServiceClient) GetSlarkRegistrationCaptchas(ctx context.Context, in *GetSlarkRegistrationCaptchasRequest, opts ...grpc.CallOption) (*GetSlarkRegistrationCaptchasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSlarkRegistrationCaptchasResponse)
	err := c.cc.Invoke(ctx, TesterService_GetSlarkRegistrationCaptchas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testerServiceClient) GetSlarkLoginCaptchas(ctx context.Context, in *GetSlarkLoginCaptchasRequest, opts ...grpc.CallOption) (*GetSlarkLoginCaptchasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSlarkLoginCaptchasResponse)
	err := c.cc.Invoke(ctx, TesterService_GetSlarkLoginCaptchas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testerServiceClient) UploadApp(ctx context.Context, in *UploadAppRequest, opts ...grpc.CallOption) (*UploadAppResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadAppResponse)
	err := c.cc.Invoke(ctx, TesterService_UploadApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testerServiceClient) GetUploadedApps(ctx context.Context, in *GetUploadedAppsRequest, opts ...grpc.CallOption) (*GetUploadedAppsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUploadedAppsResponse)
	err := c.cc.Invoke(ctx, TesterService_GetUploadedApps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testerServiceClient) GetMessageNotificationConfig(ctx context.Context, in *GetMessageNotificationConfigRequest, opts ...grpc.CallOption) (*GetMessageNotificationConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMessageNotificationConfigResponse)
	err := c.cc.Invoke(ctx, TesterService_GetMessageNotificationConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testerServiceClient) UpdateMessageNotificationConfig(ctx context.Context, in *UpdateMessageNotificationConfigRequest, opts ...grpc.CallOption) (*UpdateMessageNotificationConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateMessageNotificationConfigResponse)
	err := c.cc.Invoke(ctx, TesterService_UpdateMessageNotificationConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testerServiceClient) SendMessageNotification(ctx context.Context, in *SendMessageNotificationRequest, opts ...grpc.CallOption) (*SendMessageNotificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageNotificationResponse)
	err := c.cc.Invoke(ctx, TesterService_SendMessageNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testerServiceClient) GetMessageNotificationLogs(ctx context.Context, in *GetMessageNotificationLogsRequest, opts ...grpc.CallOption) (*GetMessageNotificationLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMessageNotificationLogsResponse)
	err := c.cc.Invoke(ctx, TesterService_GetMessageNotificationLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testerServiceClient) GetPrivacyEmailAccounts(ctx context.Context, in *GetPrivacyEmailAccountsRequest, opts ...grpc.CallOption) (*GetPrivacyEmailAccountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPrivacyEmailAccountsResponse)
	err := c.cc.Invoke(ctx, TesterService_GetPrivacyEmailAccounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TesterServiceServer is the server API for TesterService service.
// All implementations must embed UnimplementedTesterServiceServer
// for forward compatibility.
type TesterServiceServer interface {
	UpdateAPITestcase(context.Context, *UpdateAPITestcaseRequest) (*UpdateAPITestcaseResponse, error)
	GetApps(context.Context, *GetAppsRequest) (*GetAppsResponse, error)
	GetAPITestcases(context.Context, *GetAPITestcasesRequest) (*GetAPITestcasesResponse, error)
	GetMysqlInfo(context.Context, *GetMysqlInfoRequest) (*GetMysqlInfoResponse, error)
	GetMongoInfo(context.Context, *GetMongoInfoRequest) (*GetMongoInfoResponse, error)
	GetBtcDiff(context.Context, *GetBtcDiffRequest) (*GetBtcDiffResponse, error)
	GetTxsMempoolInfo(context.Context, *GetTxsMempoolInfoRequest) (*GetTxsMempoolInfoResponse, error)
	GetSlarkRegistrationCaptchas(context.Context, *GetSlarkRegistrationCaptchasRequest) (*GetSlarkRegistrationCaptchasResponse, error)
	GetSlarkLoginCaptchas(context.Context, *GetSlarkLoginCaptchasRequest) (*GetSlarkLoginCaptchasResponse, error)
	UploadApp(context.Context, *UploadAppRequest) (*UploadAppResponse, error)
	GetUploadedApps(context.Context, *GetUploadedAppsRequest) (*GetUploadedAppsResponse, error)
	GetMessageNotificationConfig(context.Context, *GetMessageNotificationConfigRequest) (*GetMessageNotificationConfigResponse, error)
	UpdateMessageNotificationConfig(context.Context, *UpdateMessageNotificationConfigRequest) (*UpdateMessageNotificationConfigResponse, error)
	SendMessageNotification(context.Context, *SendMessageNotificationRequest) (*SendMessageNotificationResponse, error)
	GetMessageNotificationLogs(context.Context, *GetMessageNotificationLogsRequest) (*GetMessageNotificationLogsResponse, error)
	GetPrivacyEmailAccounts(context.Context, *GetPrivacyEmailAccountsRequest) (*GetPrivacyEmailAccountsResponse, error)
	mustEmbedUnimplementedTesterServiceServer()
}

// UnimplementedTesterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTesterServiceServer struct{}

func (UnimplementedTesterServiceServer) UpdateAPITestcase(context.Context, *UpdateAPITestcaseRequest) (*UpdateAPITestcaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAPITestcase not implemented")
}
func (UnimplementedTesterServiceServer) GetApps(context.Context, *GetAppsRequest) (*GetAppsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetApps not implemented")
}
func (UnimplementedTesterServiceServer) GetAPITestcases(context.Context, *GetAPITestcasesRequest) (*GetAPITestcasesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAPITestcases not implemented")
}
func (UnimplementedTesterServiceServer) GetMysqlInfo(context.Context, *GetMysqlInfoRequest) (*GetMysqlInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMysqlInfo not implemented")
}
func (UnimplementedTesterServiceServer) GetMongoInfo(context.Context, *GetMongoInfoRequest) (*GetMongoInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMongoInfo not implemented")
}
func (UnimplementedTesterServiceServer) GetBtcDiff(context.Context, *GetBtcDiffRequest) (*GetBtcDiffResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBtcDiff not implemented")
}
func (UnimplementedTesterServiceServer) GetTxsMempoolInfo(context.Context, *GetTxsMempoolInfoRequest) (*GetTxsMempoolInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTxsMempoolInfo not implemented")
}
func (UnimplementedTesterServiceServer) GetSlarkRegistrationCaptchas(context.Context, *GetSlarkRegistrationCaptchasRequest) (*GetSlarkRegistrationCaptchasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSlarkRegistrationCaptchas not implemented")
}
func (UnimplementedTesterServiceServer) GetSlarkLoginCaptchas(context.Context, *GetSlarkLoginCaptchasRequest) (*GetSlarkLoginCaptchasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSlarkLoginCaptchas not implemented")
}
func (UnimplementedTesterServiceServer) UploadApp(context.Context, *UploadAppRequest) (*UploadAppResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadApp not implemented")
}
func (UnimplementedTesterServiceServer) GetUploadedApps(context.Context, *GetUploadedAppsRequest) (*GetUploadedAppsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUploadedApps not implemented")
}
func (UnimplementedTesterServiceServer) GetMessageNotificationConfig(context.Context, *GetMessageNotificationConfigRequest) (*GetMessageNotificationConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMessageNotificationConfig not implemented")
}
func (UnimplementedTesterServiceServer) UpdateMessageNotificationConfig(context.Context, *UpdateMessageNotificationConfigRequest) (*UpdateMessageNotificationConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMessageNotificationConfig not implemented")
}
func (UnimplementedTesterServiceServer) SendMessageNotification(context.Context, *SendMessageNotificationRequest) (*SendMessageNotificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessageNotification not implemented")
}
func (UnimplementedTesterServiceServer) GetMessageNotificationLogs(context.Context, *GetMessageNotificationLogsRequest) (*GetMessageNotificationLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMessageNotificationLogs not implemented")
}
func (UnimplementedTesterServiceServer) GetPrivacyEmailAccounts(context.Context, *GetPrivacyEmailAccountsRequest) (*GetPrivacyEmailAccountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPrivacyEmailAccounts not implemented")
}
func (UnimplementedTesterServiceServer) mustEmbedUnimplementedTesterServiceServer() {}
func (UnimplementedTesterServiceServer) testEmbeddedByValue()                       {}

// UnsafeTesterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TesterServiceServer will
// result in compilation errors.
type UnsafeTesterServiceServer interface {
	mustEmbedUnimplementedTesterServiceServer()
}

func RegisterTesterServiceServer(s grpc.ServiceRegistrar, srv TesterServiceServer) {
	// If the following call pancis, it indicates UnimplementedTesterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TesterService_ServiceDesc, srv)
}

func _TesterService_UpdateAPITestcase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAPITestcaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TesterServiceServer).UpdateAPITestcase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TesterService_UpdateAPITestcase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TesterServiceServer).UpdateAPITestcase(ctx, req.(*UpdateAPITestcaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TesterService_GetApps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TesterServiceServer).GetApps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TesterService_GetApps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TesterServiceServer).GetApps(ctx, req.(*GetAppsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TesterService_GetAPITestcases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAPITestcasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TesterServiceServer).GetAPITestcases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TesterService_GetAPITestcases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TesterServiceServer).GetAPITestcases(ctx, req.(*GetAPITestcasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TesterService_GetMysqlInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMysqlInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TesterServiceServer).GetMysqlInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TesterService_GetMysqlInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TesterServiceServer).GetMysqlInfo(ctx, req.(*GetMysqlInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TesterService_GetMongoInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMongoInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TesterServiceServer).GetMongoInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TesterService_GetMongoInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TesterServiceServer).GetMongoInfo(ctx, req.(*GetMongoInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TesterService_GetBtcDiff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBtcDiffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TesterServiceServer).GetBtcDiff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TesterService_GetBtcDiff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TesterServiceServer).GetBtcDiff(ctx, req.(*GetBtcDiffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TesterService_GetTxsMempoolInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTxsMempoolInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TesterServiceServer).GetTxsMempoolInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TesterService_GetTxsMempoolInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TesterServiceServer).GetTxsMempoolInfo(ctx, req.(*GetTxsMempoolInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TesterService_GetSlarkRegistrationCaptchas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSlarkRegistrationCaptchasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TesterServiceServer).GetSlarkRegistrationCaptchas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TesterService_GetSlarkRegistrationCaptchas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TesterServiceServer).GetSlarkRegistrationCaptchas(ctx, req.(*GetSlarkRegistrationCaptchasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TesterService_GetSlarkLoginCaptchas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSlarkLoginCaptchasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TesterServiceServer).GetSlarkLoginCaptchas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TesterService_GetSlarkLoginCaptchas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TesterServiceServer).GetSlarkLoginCaptchas(ctx, req.(*GetSlarkLoginCaptchasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TesterService_UploadApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TesterServiceServer).UploadApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TesterService_UploadApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TesterServiceServer).UploadApp(ctx, req.(*UploadAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TesterService_GetUploadedApps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUploadedAppsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TesterServiceServer).GetUploadedApps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TesterService_GetUploadedApps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TesterServiceServer).GetUploadedApps(ctx, req.(*GetUploadedAppsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TesterService_GetMessageNotificationConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessageNotificationConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TesterServiceServer).GetMessageNotificationConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TesterService_GetMessageNotificationConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TesterServiceServer).GetMessageNotificationConfig(ctx, req.(*GetMessageNotificationConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TesterService_UpdateMessageNotificationConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMessageNotificationConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TesterServiceServer).UpdateMessageNotificationConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TesterService_UpdateMessageNotificationConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TesterServiceServer).UpdateMessageNotificationConfig(ctx, req.(*UpdateMessageNotificationConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TesterService_SendMessageNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TesterServiceServer).SendMessageNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TesterService_SendMessageNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TesterServiceServer).SendMessageNotification(ctx, req.(*SendMessageNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TesterService_GetMessageNotificationLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessageNotificationLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TesterServiceServer).GetMessageNotificationLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TesterService_GetMessageNotificationLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TesterServiceServer).GetMessageNotificationLogs(ctx, req.(*GetMessageNotificationLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TesterService_GetPrivacyEmailAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPrivacyEmailAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TesterServiceServer).GetPrivacyEmailAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TesterService_GetPrivacyEmailAccounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TesterServiceServer).GetPrivacyEmailAccounts(ctx, req.(*GetPrivacyEmailAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TesterService_ServiceDesc is the grpc.ServiceDesc for TesterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TesterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tester_api.TesterService",
	HandlerType: (*TesterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateAPITestcase",
			Handler:    _TesterService_UpdateAPITestcase_Handler,
		},
		{
			MethodName: "GetApps",
			Handler:    _TesterService_GetApps_Handler,
		},
		{
			MethodName: "GetAPITestcases",
			Handler:    _TesterService_GetAPITestcases_Handler,
		},
		{
			MethodName: "GetMysqlInfo",
			Handler:    _TesterService_GetMysqlInfo_Handler,
		},
		{
			MethodName: "GetMongoInfo",
			Handler:    _TesterService_GetMongoInfo_Handler,
		},
		{
			MethodName: "GetBtcDiff",
			Handler:    _TesterService_GetBtcDiff_Handler,
		},
		{
			MethodName: "GetTxsMempoolInfo",
			Handler:    _TesterService_GetTxsMempoolInfo_Handler,
		},
		{
			MethodName: "GetSlarkRegistrationCaptchas",
			Handler:    _TesterService_GetSlarkRegistrationCaptchas_Handler,
		},
		{
			MethodName: "GetSlarkLoginCaptchas",
			Handler:    _TesterService_GetSlarkLoginCaptchas_Handler,
		},
		{
			MethodName: "UploadApp",
			Handler:    _TesterService_UploadApp_Handler,
		},
		{
			MethodName: "GetUploadedApps",
			Handler:    _TesterService_GetUploadedApps_Handler,
		},
		{
			MethodName: "GetMessageNotificationConfig",
			Handler:    _TesterService_GetMessageNotificationConfig_Handler,
		},
		{
			MethodName: "UpdateMessageNotificationConfig",
			Handler:    _TesterService_UpdateMessageNotificationConfig_Handler,
		},
		{
			MethodName: "SendMessageNotification",
			Handler:    _TesterService_SendMessageNotification_Handler,
		},
		{
			MethodName: "GetMessageNotificationLogs",
			Handler:    _TesterService_GetMessageNotificationLogs_Handler,
		},
		{
			MethodName: "GetPrivacyEmailAccounts",
			Handler:    _TesterService_GetPrivacyEmailAccounts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/tester.proto",
}
