pipeline {
    agent {
        label 's2'
    }

    stages {
        stage('Deploy') {
            steps {
                configFileProvider([configFile(fileId: 'bookManager-Config.json', targetLocation: 'backend/conf-release.json', variable: 'BACKEND_CONFIG')]) {
                    sh """
                        docker-compose down
                        docker stop -s SIGTERM book-manage-nginx && docker rm book-manage-nginx || echo 0
                        docker stop -s SIGTERM book-manage-backend && docker rm book-manage-backend || echo 0
                        docker stop -s SIGTERM book-manage-ui && docker rm book-manage-ui || echo 0
                        docker-compose up -d
                    """
                }
            }
        }
    }
    post {
        cleanup {
            sh """
                docker system prune -f
            """
            cleanWs()
        }
    }
}