// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDefinitionComment = "definition_comment"

// DefinitionComment mapped from table <definition_comment>
type DefinitionComment struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt    time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt    int64     `gorm:"column:deleted_at;not null;comment:Coding style" json:"deleted_at"`        // Coding style
	DefinitionID int64     `gorm:"column:definition_id;not null;comment:definition id" json:"definition_id"` // definition id
	Content      string    `gorm:"column:content;not null" json:"content"`
}

// TableName DefinitionComment's table name
func (*DefinitionComment) TableName() string {
	return TableNameDefinitionComment
}
