// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProgressBackup = "progress_backup"

// ProgressBackup mapped from table <progress_backup>
type ProgressBackup struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:primary id" json:"id"`                       // primary id
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:create time" json:"created_at"` // create time
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:update time" json:"updated_at"` // update time
	DeletedAt int64     `gorm:"column:deleted_at;not null;comment:soft delete time" json:"deleted_at"`                      // soft delete time
	Timestamp int64     `gorm:"column:timestamp;not null;comment:backup timestamp" json:"timestamp"`                        // backup timestamp
	UserID    int64     `gorm:"column:user_id;not null;comment:user id on slark" json:"user_id"`                            // user id on slark
	Version   int32     `gorm:"column:version;not null;default:1;comment:data format version" json:"version"`               // data format version
	Resource  string    `gorm:"column:resource;not null;comment:data path on aws s3" json:"resource"`                       // data path on aws s3
}

// TableName ProgressBackup's table name
func (*ProgressBackup) TableName() string {
	return TableNameProgressBackup
}
