// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRelatedBook = "related_book"

// RelatedBook mapped from table <related_book>
type RelatedBook struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt int64     `gorm:"column:deleted_at;not null;comment:Coding style" json:"deleted_at"` // Coding style
	ItemID    int64     `gorm:"column:item_id;not null" json:"item_id"`
	ItemType  string    `gorm:"column:item_type;not null" json:"item_type"`
	BookID    int64     `gorm:"column:book_id;not null" json:"book_id"`
	SortValue int32     `gorm:"column:sort_value;not null" json:"sort_value"`
}

// TableName RelatedBook's table name
func (*RelatedBook) TableName() string {
	return TableNameRelatedBook
}
