// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePost = "post"

// Post mapped from table <post>
type Post struct {
	ID         int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:primary id" json:"id"` // primary id
	SiteID     int64  `gorm:"column:site_id;not null;comment:site id" json:"site_id"`               // site id
	CategoryID int64  `gorm:"column:category_id;not null;comment:category id" json:"category_id"`   // category id
	Title      string `gorm:"column:title;not null;comment:title" json:"title"`                     // title
	PostedAt   int64  `gorm:"column:posted_at;not null;comment:posted at" json:"posted_at"`         // posted at
	PostedBy   int64  `gorm:"column:posted_by;not null;comment:posted by" json:"posted_by"`         // posted by
	Content    string `gorm:"column:content;not null;comment:content" json:"content"`               // content
	Image      string `gorm:"column:image;comment:image url" json:"image"`                          // image url
	State      int32  `gorm:"column:state;not null;comment:state" json:"state"`                     // state
	Views      int64  `gorm:"column:views;not null;comment:views" json:"views"`                     // views
	Replies    int64  `gorm:"column:replies;not null;comment:replies" json:"replies"`               // replies
	Thumbups   int64  `gorm:"column:thumbups;not null;comment:thumbups" json:"thumbups"`            // thumbups
	Activity   int64  `gorm:"column:activity;not null;comment:activity" json:"activity"`            // activity
}

// TableName Post's table name
func (*Post) TableName() string {
	return TableNamePost
}
