// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSiteAdmin = "site_admin"

// SiteAdmin mapped from table <site_admin>
type SiteAdmin struct {
	ID     int64 `gorm:"column:id;primaryKey;autoIncrement:true;comment:primary id" json:"id"` // primary id
	SiteID int64 `gorm:"column:site_id;not null;comment:site id" json:"site_id"`               // site id
	UserID int64 `gorm:"column:user_id;not null;comment:admin user id" json:"user_id"`         // admin user id
}

// TableName SiteAdmin's table name
func (*SiteAdmin) TableName() string {
	return TableNameSiteAdmin
}
