// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/device.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceEmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DebugMessage  *structpb.Value        `protobuf:"bytes,3,opt,name=debugMessage,proto3" json:"debugMessage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceEmptyResponse) Reset() {
	*x = DeviceEmptyResponse{}
	mi := &file_api_device_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceEmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceEmptyResponse) ProtoMessage() {}

func (x *DeviceEmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceEmptyResponse.ProtoReflect.Descriptor instead.
func (*DeviceEmptyResponse) Descriptor() ([]byte, []int) {
	return file_api_device_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceEmptyResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeviceEmptyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeviceEmptyResponse) GetDebugMessage() *structpb.Value {
	if x != nil {
		return x.DebugMessage
	}
	return nil
}

type DeviceRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DeviceID         string                 `protobuf:"bytes,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	Platform         string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	DeviceModel      string                 `protobuf:"bytes,3,opt,name=deviceModel,proto3" json:"deviceModel,omitempty"`
	ResolutionWidth  int32                  `protobuf:"varint,4,opt,name=resolutionWidth,proto3" json:"resolutionWidth,omitempty"`
	ResolutionHeight int32                  `protobuf:"varint,5,opt,name=resolutionHeight,proto3" json:"resolutionHeight,omitempty"`
	ScreenDensity    float32                `protobuf:"fixed32,6,opt,name=screenDensity,proto3" json:"screenDensity,omitempty"`
	Rom              float32                `protobuf:"fixed32,7,opt,name=rom,proto3" json:"rom,omitempty"`
	Ram              float32                `protobuf:"fixed32,8,opt,name=ram,proto3" json:"ram,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeviceRequest) Reset() {
	*x = DeviceRequest{}
	mi := &file_api_device_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceRequest) ProtoMessage() {}

func (x *DeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceRequest.ProtoReflect.Descriptor instead.
func (*DeviceRequest) Descriptor() ([]byte, []int) {
	return file_api_device_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceRequest) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

func (x *DeviceRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *DeviceRequest) GetDeviceModel() string {
	if x != nil {
		return x.DeviceModel
	}
	return ""
}

func (x *DeviceRequest) GetResolutionWidth() int32 {
	if x != nil {
		return x.ResolutionWidth
	}
	return 0
}

func (x *DeviceRequest) GetResolutionHeight() int32 {
	if x != nil {
		return x.ResolutionHeight
	}
	return 0
}

func (x *DeviceRequest) GetScreenDensity() float32 {
	if x != nil {
		return x.ScreenDensity
	}
	return 0
}

func (x *DeviceRequest) GetRom() float32 {
	if x != nil {
		return x.Rom
	}
	return 0
}

func (x *DeviceRequest) GetRam() float32 {
	if x != nil {
		return x.Ram
	}
	return 0
}

var File_api_device_proto protoreflect.FileDescriptor

const file_api_device_proto_rawDesc = "" +
	"\n" +
	"\x10api/device.proto\x12\tslark_api\x1a\x1cgoogle/protobuf/struct.proto\"\x7f\n" +
	"\x13DeviceEmptyResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12:\n" +
	"\fdebugMessage\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\fdebugMessage\"\x89\x02\n" +
	"\rDeviceRequest\x12\x1a\n" +
	"\bdeviceID\x18\x01 \x01(\tR\bdeviceID\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12 \n" +
	"\vdeviceModel\x18\x03 \x01(\tR\vdeviceModel\x12(\n" +
	"\x0fresolutionWidth\x18\x04 \x01(\x05R\x0fresolutionWidth\x12*\n" +
	"\x10resolutionHeight\x18\x05 \x01(\x05R\x10resolutionHeight\x12$\n" +
	"\rscreenDensity\x18\x06 \x01(\x02R\rscreenDensity\x12\x10\n" +
	"\x03rom\x18\a \x01(\x02R\x03rom\x12\x10\n" +
	"\x03ram\x18\b \x01(\x02R\x03ram2]\n" +
	"\rDeviceService\x12L\n" +
	"\x10UploadDeviceInfo\x12\x18.slark_api.DeviceRequest\x1a\x1e.slark_api.DeviceEmptyResponseB\aZ\x05./apib\x06proto3"

var (
	file_api_device_proto_rawDescOnce sync.Once
	file_api_device_proto_rawDescData []byte
)

func file_api_device_proto_rawDescGZIP() []byte {
	file_api_device_proto_rawDescOnce.Do(func() {
		file_api_device_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_device_proto_rawDesc), len(file_api_device_proto_rawDesc)))
	})
	return file_api_device_proto_rawDescData
}

var file_api_device_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_device_proto_goTypes = []any{
	(*DeviceEmptyResponse)(nil), // 0: slark_api.DeviceEmptyResponse
	(*DeviceRequest)(nil),       // 1: slark_api.DeviceRequest
	(*structpb.Value)(nil),      // 2: google.protobuf.Value
}
var file_api_device_proto_depIdxs = []int32{
	2, // 0: slark_api.DeviceEmptyResponse.debugMessage:type_name -> google.protobuf.Value
	1, // 1: slark_api.DeviceService.UploadDeviceInfo:input_type -> slark_api.DeviceRequest
	0, // 2: slark_api.DeviceService.UploadDeviceInfo:output_type -> slark_api.DeviceEmptyResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_device_proto_init() }
func file_api_device_proto_init() {
	if File_api_device_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_device_proto_rawDesc), len(file_api_device_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_device_proto_goTypes,
		DependencyIndexes: file_api_device_proto_depIdxs,
		MessageInfos:      file_api_device_proto_msgTypes,
	}.Build()
	File_api_device_proto = out.File
	file_api_device_proto_goTypes = nil
	file_api_device_proto_depIdxs = nil
}
