// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: api/user.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserService_LoginByPhone_FullMethodName                 = "/slark_api.UserService/LoginByPhone"
	UserService_LoginByEmail_FullMethodName                 = "/slark_api.UserService/LoginByEmail"
	UserService_LoginBySession_FullMethodName               = "/slark_api.UserService/LoginBySession"
	UserService_LoginByApple_FullMethodName                 = "/slark_api.UserService/LoginByApple"
	UserService_RegisterByEmail_FullMethodName              = "/slark_api.UserService/RegisterByEmail"
	UserService_RegisterByEmailCaptcha_FullMethodName       = "/slark_api.UserService/RegisterByEmailCaptcha"
	UserService_SendRegistrationEmailCaptcha_FullMethodName = "/slark_api.UserService/SendRegistrationEmailCaptcha"
	UserService_LogOutBySession_FullMethodName              = "/slark_api.UserService/LogOutBySession"
	UserService_CheckLogin_FullMethodName                   = "/slark_api.UserService/CheckLogin"
	UserService_LoginInfo_FullMethodName                    = "/slark_api.UserService/LoginInfo"
	UserService_QRLogin_FullMethodName                      = "/slark_api.UserService/QRLogin"
	UserService_SendLoginEmailCode_FullMethodName           = "/slark_api.UserService/SendLoginEmailCode"
	UserService_LoginByEmailCode_FullMethodName             = "/slark_api.UserService/LoginByEmailCode"
	UserService_UpdateNickname_FullMethodName               = "/slark_api.UserService/UpdateNickname"
	UserService_Unregister_FullMethodName                   = "/slark_api.UserService/Unregister"
	UserService_RandomNickname_FullMethodName               = "/slark_api.UserService/RandomNickname"
	UserService_GetUserInfo_FullMethodName                  = "/slark_api.UserService/GetUserInfo"
	UserService_ValidateUserIDs_FullMethodName              = "/slark_api.UserService/ValidateUserIDs"
	UserService_CheckRegistration_FullMethodName            = "/slark_api.UserService/CheckRegistration"
	UserService_CreateSecondaryPassword_FullMethodName      = "/slark_api.UserService/CreateSecondaryPassword"
	UserService_UpdateSecondaryPassword_FullMethodName      = "/slark_api.UserService/UpdateSecondaryPassword"
	UserService_LoginBySecondaryPassword_FullMethodName     = "/slark_api.UserService/LoginBySecondaryPassword"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	LoginByPhone(ctx context.Context, in *PhoneLoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	LoginByEmail(ctx context.Context, in *EmailLoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	LoginBySession(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LoginResponse, error)
	LoginByApple(ctx context.Context, in *LoginByAppleRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	RegisterByEmail(ctx context.Context, in *RegisterByEmailRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	RegisterByEmailCaptcha(ctx context.Context, in *RegisterByEmailCaptchaRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	SendRegistrationEmailCaptcha(ctx context.Context, in *SendRegistrationEmailCaptchaRequest, opts ...grpc.CallOption) (*SendRegistrationEmailCaptchaResponse, error)
	LogOutBySession(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*EmptyResponse, error)
	CheckLogin(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*EmptyResponse, error)
	LoginInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LoginResponse, error)
	QRLogin(ctx context.Context, in *QRLoginRequest, opts ...grpc.CallOption) (*QRLoginResponse, error)
	SendLoginEmailCode(ctx context.Context, in *SendLoginEmailCodeRequest, opts ...grpc.CallOption) (*SendLoginEmailCodeResponse, error)
	LoginByEmailCode(ctx context.Context, in *LoginByEmailCodeRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	UpdateNickname(ctx context.Context, in *UpdateNicknameRequest, opts ...grpc.CallOption) (*UpdateNicknameResponse, error)
	Unregister(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UnregisterResponse, error)
	RandomNickname(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RandomNicknameResponse, error)
	GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error)
	ValidateUserIDs(ctx context.Context, in *ValidateUserIDsRequest, opts ...grpc.CallOption) (*ValidateUserIDsResponse, error)
	CheckRegistration(ctx context.Context, in *CheckRegistrationRequest, opts ...grpc.CallOption) (*CheckRegistrationResponse, error)
	CreateSecondaryPassword(ctx context.Context, in *CreateSecondaryPasswordRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	UpdateSecondaryPassword(ctx context.Context, in *UpdateSecondaryPasswordRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	LoginBySecondaryPassword(ctx context.Context, in *LoginBySecondaryPasswordRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) LoginByPhone(ctx context.Context, in *PhoneLoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, UserService_LoginByPhone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) LoginByEmail(ctx context.Context, in *EmailLoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, UserService_LoginByEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) LoginBySession(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, UserService_LoginBySession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) LoginByApple(ctx context.Context, in *LoginByAppleRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, UserService_LoginByApple_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) RegisterByEmail(ctx context.Context, in *RegisterByEmailRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, UserService_RegisterByEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) RegisterByEmailCaptcha(ctx context.Context, in *RegisterByEmailCaptchaRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, UserService_RegisterByEmailCaptcha_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SendRegistrationEmailCaptcha(ctx context.Context, in *SendRegistrationEmailCaptchaRequest, opts ...grpc.CallOption) (*SendRegistrationEmailCaptchaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendRegistrationEmailCaptchaResponse)
	err := c.cc.Invoke(ctx, UserService_SendRegistrationEmailCaptcha_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) LogOutBySession(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, UserService_LogOutBySession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CheckLogin(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, UserService_CheckLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) LoginInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, UserService_LoginInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) QRLogin(ctx context.Context, in *QRLoginRequest, opts ...grpc.CallOption) (*QRLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QRLoginResponse)
	err := c.cc.Invoke(ctx, UserService_QRLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SendLoginEmailCode(ctx context.Context, in *SendLoginEmailCodeRequest, opts ...grpc.CallOption) (*SendLoginEmailCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendLoginEmailCodeResponse)
	err := c.cc.Invoke(ctx, UserService_SendLoginEmailCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) LoginByEmailCode(ctx context.Context, in *LoginByEmailCodeRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, UserService_LoginByEmailCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateNickname(ctx context.Context, in *UpdateNicknameRequest, opts ...grpc.CallOption) (*UpdateNicknameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateNicknameResponse)
	err := c.cc.Invoke(ctx, UserService_UpdateNickname_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Unregister(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UnregisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterResponse)
	err := c.cc.Invoke(ctx, UserService_Unregister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) RandomNickname(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RandomNicknameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RandomNicknameResponse)
	err := c.cc.Invoke(ctx, UserService_RandomNickname_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserInfoResponse)
	err := c.cc.Invoke(ctx, UserService_GetUserInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ValidateUserIDs(ctx context.Context, in *ValidateUserIDsRequest, opts ...grpc.CallOption) (*ValidateUserIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateUserIDsResponse)
	err := c.cc.Invoke(ctx, UserService_ValidateUserIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CheckRegistration(ctx context.Context, in *CheckRegistrationRequest, opts ...grpc.CallOption) (*CheckRegistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckRegistrationResponse)
	err := c.cc.Invoke(ctx, UserService_CheckRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreateSecondaryPassword(ctx context.Context, in *CreateSecondaryPasswordRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, UserService_CreateSecondaryPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateSecondaryPassword(ctx context.Context, in *UpdateSecondaryPasswordRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, UserService_UpdateSecondaryPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) LoginBySecondaryPassword(ctx context.Context, in *LoginBySecondaryPasswordRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, UserService_LoginBySecondaryPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility.
type UserServiceServer interface {
	LoginByPhone(context.Context, *PhoneLoginRequest) (*LoginResponse, error)
	LoginByEmail(context.Context, *EmailLoginRequest) (*LoginResponse, error)
	LoginBySession(context.Context, *Empty) (*LoginResponse, error)
	LoginByApple(context.Context, *LoginByAppleRequest) (*LoginResponse, error)
	RegisterByEmail(context.Context, *RegisterByEmailRequest) (*LoginResponse, error)
	RegisterByEmailCaptcha(context.Context, *RegisterByEmailCaptchaRequest) (*LoginResponse, error)
	SendRegistrationEmailCaptcha(context.Context, *SendRegistrationEmailCaptchaRequest) (*SendRegistrationEmailCaptchaResponse, error)
	LogOutBySession(context.Context, *Empty) (*EmptyResponse, error)
	CheckLogin(context.Context, *Empty) (*EmptyResponse, error)
	LoginInfo(context.Context, *Empty) (*LoginResponse, error)
	QRLogin(context.Context, *QRLoginRequest) (*QRLoginResponse, error)
	SendLoginEmailCode(context.Context, *SendLoginEmailCodeRequest) (*SendLoginEmailCodeResponse, error)
	LoginByEmailCode(context.Context, *LoginByEmailCodeRequest) (*LoginResponse, error)
	UpdateNickname(context.Context, *UpdateNicknameRequest) (*UpdateNicknameResponse, error)
	Unregister(context.Context, *Empty) (*UnregisterResponse, error)
	RandomNickname(context.Context, *Empty) (*RandomNicknameResponse, error)
	GetUserInfo(context.Context, *GetUserInfoRequest) (*GetUserInfoResponse, error)
	ValidateUserIDs(context.Context, *ValidateUserIDsRequest) (*ValidateUserIDsResponse, error)
	CheckRegistration(context.Context, *CheckRegistrationRequest) (*CheckRegistrationResponse, error)
	CreateSecondaryPassword(context.Context, *CreateSecondaryPasswordRequest) (*EmptyResponse, error)
	UpdateSecondaryPassword(context.Context, *UpdateSecondaryPasswordRequest) (*EmptyResponse, error)
	LoginBySecondaryPassword(context.Context, *LoginBySecondaryPasswordRequest) (*LoginResponse, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) LoginByPhone(context.Context, *PhoneLoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginByPhone not implemented")
}
func (UnimplementedUserServiceServer) LoginByEmail(context.Context, *EmailLoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginByEmail not implemented")
}
func (UnimplementedUserServiceServer) LoginBySession(context.Context, *Empty) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginBySession not implemented")
}
func (UnimplementedUserServiceServer) LoginByApple(context.Context, *LoginByAppleRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginByApple not implemented")
}
func (UnimplementedUserServiceServer) RegisterByEmail(context.Context, *RegisterByEmailRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterByEmail not implemented")
}
func (UnimplementedUserServiceServer) RegisterByEmailCaptcha(context.Context, *RegisterByEmailCaptchaRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterByEmailCaptcha not implemented")
}
func (UnimplementedUserServiceServer) SendRegistrationEmailCaptcha(context.Context, *SendRegistrationEmailCaptchaRequest) (*SendRegistrationEmailCaptchaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendRegistrationEmailCaptcha not implemented")
}
func (UnimplementedUserServiceServer) LogOutBySession(context.Context, *Empty) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogOutBySession not implemented")
}
func (UnimplementedUserServiceServer) CheckLogin(context.Context, *Empty) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckLogin not implemented")
}
func (UnimplementedUserServiceServer) LoginInfo(context.Context, *Empty) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginInfo not implemented")
}
func (UnimplementedUserServiceServer) QRLogin(context.Context, *QRLoginRequest) (*QRLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QRLogin not implemented")
}
func (UnimplementedUserServiceServer) SendLoginEmailCode(context.Context, *SendLoginEmailCodeRequest) (*SendLoginEmailCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendLoginEmailCode not implemented")
}
func (UnimplementedUserServiceServer) LoginByEmailCode(context.Context, *LoginByEmailCodeRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginByEmailCode not implemented")
}
func (UnimplementedUserServiceServer) UpdateNickname(context.Context, *UpdateNicknameRequest) (*UpdateNicknameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNickname not implemented")
}
func (UnimplementedUserServiceServer) Unregister(context.Context, *Empty) (*UnregisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unregister not implemented")
}
func (UnimplementedUserServiceServer) RandomNickname(context.Context, *Empty) (*RandomNicknameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RandomNickname not implemented")
}
func (UnimplementedUserServiceServer) GetUserInfo(context.Context, *GetUserInfoRequest) (*GetUserInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (UnimplementedUserServiceServer) ValidateUserIDs(context.Context, *ValidateUserIDsRequest) (*ValidateUserIDsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateUserIDs not implemented")
}
func (UnimplementedUserServiceServer) CheckRegistration(context.Context, *CheckRegistrationRequest) (*CheckRegistrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckRegistration not implemented")
}
func (UnimplementedUserServiceServer) CreateSecondaryPassword(context.Context, *CreateSecondaryPasswordRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSecondaryPassword not implemented")
}
func (UnimplementedUserServiceServer) UpdateSecondaryPassword(context.Context, *UpdateSecondaryPasswordRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSecondaryPassword not implemented")
}
func (UnimplementedUserServiceServer) LoginBySecondaryPassword(context.Context, *LoginBySecondaryPasswordRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginBySecondaryPassword not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}
func (UnimplementedUserServiceServer) testEmbeddedByValue()                     {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	// If the following call pancis, it indicates UnimplementedUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_LoginByPhone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PhoneLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).LoginByPhone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_LoginByPhone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).LoginByPhone(ctx, req.(*PhoneLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_LoginByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).LoginByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_LoginByEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).LoginByEmail(ctx, req.(*EmailLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_LoginBySession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).LoginBySession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_LoginBySession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).LoginBySession(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_LoginByApple_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginByAppleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).LoginByApple(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_LoginByApple_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).LoginByApple(ctx, req.(*LoginByAppleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_RegisterByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterByEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).RegisterByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_RegisterByEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).RegisterByEmail(ctx, req.(*RegisterByEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_RegisterByEmailCaptcha_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterByEmailCaptchaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).RegisterByEmailCaptcha(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_RegisterByEmailCaptcha_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).RegisterByEmailCaptcha(ctx, req.(*RegisterByEmailCaptchaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SendRegistrationEmailCaptcha_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRegistrationEmailCaptchaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SendRegistrationEmailCaptcha(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_SendRegistrationEmailCaptcha_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SendRegistrationEmailCaptcha(ctx, req.(*SendRegistrationEmailCaptchaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_LogOutBySession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).LogOutBySession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_LogOutBySession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).LogOutBySession(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CheckLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CheckLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_CheckLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CheckLogin(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_LoginInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).LoginInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_LoginInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).LoginInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_QRLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QRLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).QRLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_QRLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).QRLogin(ctx, req.(*QRLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SendLoginEmailCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendLoginEmailCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SendLoginEmailCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_SendLoginEmailCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SendLoginEmailCode(ctx, req.(*SendLoginEmailCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_LoginByEmailCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginByEmailCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).LoginByEmailCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_LoginByEmailCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).LoginByEmailCode(ctx, req.(*LoginByEmailCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateNickname_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNicknameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateNickname(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdateNickname_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateNickname(ctx, req.(*UpdateNicknameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Unregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Unregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_Unregister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Unregister(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_RandomNickname_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).RandomNickname(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_RandomNickname_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).RandomNickname(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetUserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserInfo(ctx, req.(*GetUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ValidateUserIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateUserIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ValidateUserIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_ValidateUserIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ValidateUserIDs(ctx, req.(*ValidateUserIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CheckRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CheckRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_CheckRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CheckRegistration(ctx, req.(*CheckRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreateSecondaryPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSecondaryPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateSecondaryPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_CreateSecondaryPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateSecondaryPassword(ctx, req.(*CreateSecondaryPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateSecondaryPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSecondaryPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateSecondaryPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdateSecondaryPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateSecondaryPassword(ctx, req.(*UpdateSecondaryPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_LoginBySecondaryPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginBySecondaryPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).LoginBySecondaryPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_LoginBySecondaryPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).LoginBySecondaryPassword(ctx, req.(*LoginBySecondaryPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "slark_api.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoginByPhone",
			Handler:    _UserService_LoginByPhone_Handler,
		},
		{
			MethodName: "LoginByEmail",
			Handler:    _UserService_LoginByEmail_Handler,
		},
		{
			MethodName: "LoginBySession",
			Handler:    _UserService_LoginBySession_Handler,
		},
		{
			MethodName: "LoginByApple",
			Handler:    _UserService_LoginByApple_Handler,
		},
		{
			MethodName: "RegisterByEmail",
			Handler:    _UserService_RegisterByEmail_Handler,
		},
		{
			MethodName: "RegisterByEmailCaptcha",
			Handler:    _UserService_RegisterByEmailCaptcha_Handler,
		},
		{
			MethodName: "SendRegistrationEmailCaptcha",
			Handler:    _UserService_SendRegistrationEmailCaptcha_Handler,
		},
		{
			MethodName: "LogOutBySession",
			Handler:    _UserService_LogOutBySession_Handler,
		},
		{
			MethodName: "CheckLogin",
			Handler:    _UserService_CheckLogin_Handler,
		},
		{
			MethodName: "LoginInfo",
			Handler:    _UserService_LoginInfo_Handler,
		},
		{
			MethodName: "QRLogin",
			Handler:    _UserService_QRLogin_Handler,
		},
		{
			MethodName: "SendLoginEmailCode",
			Handler:    _UserService_SendLoginEmailCode_Handler,
		},
		{
			MethodName: "LoginByEmailCode",
			Handler:    _UserService_LoginByEmailCode_Handler,
		},
		{
			MethodName: "UpdateNickname",
			Handler:    _UserService_UpdateNickname_Handler,
		},
		{
			MethodName: "Unregister",
			Handler:    _UserService_Unregister_Handler,
		},
		{
			MethodName: "RandomNickname",
			Handler:    _UserService_RandomNickname_Handler,
		},
		{
			MethodName: "GetUserInfo",
			Handler:    _UserService_GetUserInfo_Handler,
		},
		{
			MethodName: "ValidateUserIDs",
			Handler:    _UserService_ValidateUserIDs_Handler,
		},
		{
			MethodName: "CheckRegistration",
			Handler:    _UserService_CheckRegistration_Handler,
		},
		{
			MethodName: "CreateSecondaryPassword",
			Handler:    _UserService_CreateSecondaryPassword_Handler,
		},
		{
			MethodName: "UpdateSecondaryPassword",
			Handler:    _UserService_UpdateSecondaryPassword_Handler,
		},
		{
			MethodName: "LoginBySecondaryPassword",
			Handler:    _UserService_LoginBySecondaryPassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/user.proto",
}

const (
	TestService_GetRegistrationEmailCaptchas_FullMethodName = "/slark_api.TestService/GetRegistrationEmailCaptchas"
	TestService_GetLoginEmailCaptchas_FullMethodName        = "/slark_api.TestService/GetLoginEmailCaptchas"
)

// TestServiceClient is the client API for TestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TestServiceClient interface {
	GetRegistrationEmailCaptchas(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetRegistrationEmailCaptchasResponse, error)
	GetLoginEmailCaptchas(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetLoginEmailCaptchasResponse, error)
}

type testServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTestServiceClient(cc grpc.ClientConnInterface) TestServiceClient {
	return &testServiceClient{cc}
}

func (c *testServiceClient) GetRegistrationEmailCaptchas(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetRegistrationEmailCaptchasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRegistrationEmailCaptchasResponse)
	err := c.cc.Invoke(ctx, TestService_GetRegistrationEmailCaptchas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testServiceClient) GetLoginEmailCaptchas(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetLoginEmailCaptchasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLoginEmailCaptchasResponse)
	err := c.cc.Invoke(ctx, TestService_GetLoginEmailCaptchas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestServiceServer is the server API for TestService service.
// All implementations must embed UnimplementedTestServiceServer
// for forward compatibility.
type TestServiceServer interface {
	GetRegistrationEmailCaptchas(context.Context, *Empty) (*GetRegistrationEmailCaptchasResponse, error)
	GetLoginEmailCaptchas(context.Context, *Empty) (*GetLoginEmailCaptchasResponse, error)
	mustEmbedUnimplementedTestServiceServer()
}

// UnimplementedTestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTestServiceServer struct{}

func (UnimplementedTestServiceServer) GetRegistrationEmailCaptchas(context.Context, *Empty) (*GetRegistrationEmailCaptchasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRegistrationEmailCaptchas not implemented")
}
func (UnimplementedTestServiceServer) GetLoginEmailCaptchas(context.Context, *Empty) (*GetLoginEmailCaptchasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLoginEmailCaptchas not implemented")
}
func (UnimplementedTestServiceServer) mustEmbedUnimplementedTestServiceServer() {}
func (UnimplementedTestServiceServer) testEmbeddedByValue()                     {}

// UnsafeTestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TestServiceServer will
// result in compilation errors.
type UnsafeTestServiceServer interface {
	mustEmbedUnimplementedTestServiceServer()
}

func RegisterTestServiceServer(s grpc.ServiceRegistrar, srv TestServiceServer) {
	// If the following call pancis, it indicates UnimplementedTestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TestService_ServiceDesc, srv)
}

func _TestService_GetRegistrationEmailCaptchas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).GetRegistrationEmailCaptchas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TestService_GetRegistrationEmailCaptchas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).GetRegistrationEmailCaptchas(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestService_GetLoginEmailCaptchas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).GetLoginEmailCaptchas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TestService_GetLoginEmailCaptchas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).GetLoginEmailCaptchas(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// TestService_ServiceDesc is the grpc.ServiceDesc for TestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "slark_api.TestService",
	HandlerType: (*TestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRegistrationEmailCaptchas",
			Handler:    _TestService_GetRegistrationEmailCaptchas_Handler,
		},
		{
			MethodName: "GetLoginEmailCaptchas",
			Handler:    _TestService_GetLoginEmailCaptchas_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/user.proto",
}
