// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/user.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginBySecondaryPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty" validate:"required"`               // @gotags: validate:"required"
	PasswordHash  string                 `protobuf:"bytes,2,opt,name=passwordHash,proto3" json:"passwordHash,omitempty" validate:"required"` // @gotags: validate:"required"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginBySecondaryPasswordRequest) Reset() {
	*x = LoginBySecondaryPasswordRequest{}
	mi := &file_api_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginBySecondaryPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginBySecondaryPasswordRequest) ProtoMessage() {}

func (x *LoginBySecondaryPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginBySecondaryPasswordRequest.ProtoReflect.Descriptor instead.
func (*LoginBySecondaryPasswordRequest) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{0}
}

func (x *LoginBySecondaryPasswordRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginBySecondaryPasswordRequest) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

type UpdateSecondaryPasswordRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OldPasswordHash string                 `protobuf:"bytes,1,opt,name=oldPasswordHash,proto3" json:"oldPasswordHash,omitempty" validate:"required"` // @gotags: validate:"required"
	NewPasswordHash string                 `protobuf:"bytes,2,opt,name=newPasswordHash,proto3" json:"newPasswordHash,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateSecondaryPasswordRequest) Reset() {
	*x = UpdateSecondaryPasswordRequest{}
	mi := &file_api_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSecondaryPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSecondaryPasswordRequest) ProtoMessage() {}

func (x *UpdateSecondaryPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSecondaryPasswordRequest.ProtoReflect.Descriptor instead.
func (*UpdateSecondaryPasswordRequest) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateSecondaryPasswordRequest) GetOldPasswordHash() string {
	if x != nil {
		return x.OldPasswordHash
	}
	return ""
}

func (x *UpdateSecondaryPasswordRequest) GetNewPasswordHash() string {
	if x != nil {
		return x.NewPasswordHash
	}
	return ""
}

type CreateSecondaryPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PasswordHash  string                 `protobuf:"bytes,1,opt,name=passwordHash,proto3" json:"passwordHash,omitempty" validate:"required"` // @gotags: validate:"required"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSecondaryPasswordRequest) Reset() {
	*x = CreateSecondaryPasswordRequest{}
	mi := &file_api_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecondaryPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecondaryPasswordRequest) ProtoMessage() {}

func (x *CreateSecondaryPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSecondaryPasswordRequest.ProtoReflect.Descriptor instead.
func (*CreateSecondaryPasswordRequest) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSecondaryPasswordRequest) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

type CheckRegistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRegistrationRequest) Reset() {
	*x = CheckRegistrationRequest{}
	mi := &file_api_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRegistrationRequest) ProtoMessage() {}

func (x *CheckRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRegistrationRequest.ProtoReflect.Descriptor instead.
func (*CheckRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{3}
}

func (x *CheckRegistrationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type CheckRegistrationResponse struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Code          int32                           `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                          `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DebugMessage  *structpb.Value                 `protobuf:"bytes,3,opt,name=debugMessage,proto3" json:"debugMessage,omitempty"`
	Oracle        string                          `protobuf:"bytes,4,opt,name=oracle,proto3" json:"oracle,omitempty"`
	Data          *CheckRegistrationResponse_Data `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRegistrationResponse) Reset() {
	*x = CheckRegistrationResponse{}
	mi := &file_api_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRegistrationResponse) ProtoMessage() {}

func (x *CheckRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRegistrationResponse.ProtoReflect.Descriptor instead.
func (*CheckRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{4}
}

func (x *CheckRegistrationResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CheckRegistrationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CheckRegistrationResponse) GetDebugMessage() *structpb.Value {
	if x != nil {
		return x.DebugMessage
	}
	return nil
}

func (x *CheckRegistrationResponse) GetOracle() string {
	if x != nil {
		return x.Oracle
	}
	return ""
}

func (x *CheckRegistrationResponse) GetData() *CheckRegistrationResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type ValidateUserIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIDs       []int64                `protobuf:"varint,1,rep,packed,name=userIDs,proto3" json:"userIDs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateUserIDsRequest) Reset() {
	*x = ValidateUserIDsRequest{}
	mi := &file_api_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateUserIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateUserIDsRequest) ProtoMessage() {}

func (x *ValidateUserIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateUserIDsRequest.ProtoReflect.Descriptor instead.
func (*ValidateUserIDsRequest) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{5}
}

func (x *ValidateUserIDsRequest) GetUserIDs() []int64 {
	if x != nil {
		return x.UserIDs
	}
	return nil
}

type ValidateUserIDsResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Code          int32                         `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DebugMessage  *structpb.Value               `protobuf:"bytes,3,opt,name=debugMessage,proto3" json:"debugMessage,omitempty"`
	Oracle        string                        `protobuf:"bytes,4,opt,name=oracle,proto3" json:"oracle,omitempty"`
	Data          *ValidateUserIDsResponse_Data `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateUserIDsResponse) Reset() {
	*x = ValidateUserIDsResponse{}
	mi := &file_api_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateUserIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateUserIDsResponse) ProtoMessage() {}

func (x *ValidateUserIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateUserIDsResponse.ProtoReflect.Descriptor instead.
func (*ValidateUserIDsResponse) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{6}
}

func (x *ValidateUserIDsResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ValidateUserIDsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ValidateUserIDsResponse) GetDebugMessage() *structpb.Value {
	if x != nil {
		return x.DebugMessage
	}
	return nil
}

func (x *ValidateUserIDsResponse) GetOracle() string {
	if x != nil {
		return x.Oracle
	}
	return ""
}

func (x *ValidateUserIDsResponse) GetData() *ValidateUserIDsResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetUserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" validate:"required"` // @gotags: validate:"required"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoRequest) Reset() {
	*x = GetUserInfoRequest{}
	mi := &file_api_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRequest) ProtoMessage() {}

func (x *GetUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserInfoRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUserInfoResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Code          int32                     `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DebugMessage  *structpb.Value           `protobuf:"bytes,3,opt,name=debugMessage,proto3" json:"debugMessage,omitempty"`
	Oracle        string                    `protobuf:"bytes,4,opt,name=oracle,proto3" json:"oracle,omitempty"`
	Data          *GetUserInfoResponse_Data `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoResponse) Reset() {
	*x = GetUserInfoResponse{}
	mi := &file_api_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResponse) ProtoMessage() {}

func (x *GetUserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResponse.ProtoReflect.Descriptor instead.
func (*GetUserInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserInfoResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetUserInfoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetUserInfoResponse) GetDebugMessage() *structpb.Value {
	if x != nil {
		return x.DebugMessage
	}
	return nil
}

func (x *GetUserInfoResponse) GetOracle() string {
	if x != nil {
		return x.Oracle
	}
	return ""
}

func (x *GetUserInfoResponse) GetData() *GetUserInfoResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{9}
}

type EmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DebugMessage  *structpb.Value        `protobuf:"bytes,3,opt,name=debugMessage,proto3" json:"debugMessage,omitempty"`
	Oracle        string                 `protobuf:"bytes,4,opt,name=oracle,proto3" json:"oracle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	mi := &file_api_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{10}
}

func (x *EmptyResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *EmptyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EmptyResponse) GetDebugMessage() *structpb.Value {
	if x != nil {
		return x.DebugMessage
	}
	return nil
}

func (x *EmptyResponse) GetOracle() string {
	if x != nil {
		return x.Oracle
	}
	return ""
}

type PhoneLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty" validate:"required"`               // @gotags: validate:"required"
	PasswordHash  string                 `protobuf:"bytes,2,opt,name=passwordHash,proto3" json:"passwordHash,omitempty" validate:"required"` // @gotags: validate:"required"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhoneLoginRequest) Reset() {
	*x = PhoneLoginRequest{}
	mi := &file_api_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhoneLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhoneLoginRequest) ProtoMessage() {}

func (x *PhoneLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhoneLoginRequest.ProtoReflect.Descriptor instead.
func (*PhoneLoginRequest) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{11}
}

func (x *PhoneLoginRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *PhoneLoginRequest) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

type EmailLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty" validate:"required"`               // @gotags: validate:"required"
	PasswordHash  string                 `protobuf:"bytes,2,opt,name=passwordHash,proto3" json:"passwordHash,omitempty" validate:"required"` // @gotags: validate:"required"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailLoginRequest) Reset() {
	*x = EmailLoginRequest{}
	mi := &file_api_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailLoginRequest) ProtoMessage() {}

func (x *EmailLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailLoginRequest.ProtoReflect.Descriptor instead.
func (*EmailLoginRequest) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{12}
}

func (x *EmailLoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *EmailLoginRequest) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DebugMessage  *structpb.Value        `protobuf:"bytes,3,opt,name=debugMessage,proto3" json:"debugMessage,omitempty"`
	Oracle        string                 `protobuf:"bytes,4,opt,name=oracle,proto3" json:"oracle,omitempty"`
	Data          *LoginResponse_Data    `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_api_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{13}
}

func (x *LoginResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LoginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoginResponse) GetDebugMessage() *structpb.Value {
	if x != nil {
		return x.DebugMessage
	}
	return nil
}

func (x *LoginResponse) GetOracle() string {
	if x != nil {
		return x.Oracle
	}
	return ""
}

func (x *LoginResponse) GetData() *LoginResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type RegisterByEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty" validate:"required"`               // @gotags: validate:"required"
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty" validate:"required"`         // @gotags: validate:"required"
	PasswordHash  string                 `protobuf:"bytes,3,opt,name=passwordHash,proto3" json:"passwordHash,omitempty" validate:"required"` // @gotags: validate:"required"
	Captcha       string                 `protobuf:"bytes,4,opt,name=captcha,proto3" json:"captcha,omitempty" validate:"required"`           // @gotags: validate:"required"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterByEmailRequest) Reset() {
	*x = RegisterByEmailRequest{}
	mi := &file_api_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterByEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterByEmailRequest) ProtoMessage() {}

func (x *RegisterByEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterByEmailRequest.ProtoReflect.Descriptor instead.
func (*RegisterByEmailRequest) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{14}
}

func (x *RegisterByEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterByEmailRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *RegisterByEmailRequest) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *RegisterByEmailRequest) GetCaptcha() string {
	if x != nil {
		return x.Captcha
	}
	return ""
}

type RegisterByEmailCaptchaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty" validate:"required"`     // @gotags: validate:"required"
	Captcha       string                 `protobuf:"bytes,2,opt,name=captcha,proto3" json:"captcha,omitempty" validate:"required"` // @gotags: validate:"required"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterByEmailCaptchaRequest) Reset() {
	*x = RegisterByEmailCaptchaRequest{}
	mi := &file_api_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterByEmailCaptchaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterByEmailCaptchaRequest) ProtoMessage() {}

func (x *RegisterByEmailCaptchaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterByEmailCaptchaRequest.ProtoReflect.Descriptor instead.
func (*RegisterByEmailCaptchaRequest) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{15}
}

func (x *RegisterByEmailCaptchaRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterByEmailCaptchaRequest) GetCaptcha() string {
	if x != nil {
		return x.Captcha
	}
	return ""
}

type LoginByAppleRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Email          string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty" validate:"required"`                   // @gotags: validate:"required"
	UserIdentifier string                 `protobuf:"bytes,2,opt,name=userIdentifier,proto3" json:"userIdentifier,omitempty" validate:"required"` // @gotags: validate:"required"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LoginByAppleRequest) Reset() {
	*x = LoginByAppleRequest{}
	mi := &file_api_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginByAppleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginByAppleRequest) ProtoMessage() {}

func (x *LoginByAppleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginByAppleRequest.ProtoReflect.Descriptor instead.
func (*LoginByAppleRequest) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{16}
}

func (x *LoginByAppleRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginByAppleRequest) GetUserIdentifier() string {
	if x != nil {
		return x.UserIdentifier
	}
	return ""
}

type SendRegistrationEmailCaptchaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty" validate:"required"` // @gotags: validate:"required"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRegistrationEmailCaptchaRequest) Reset() {
	*x = SendRegistrationEmailCaptchaRequest{}
	mi := &file_api_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRegistrationEmailCaptchaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRegistrationEmailCaptchaRequest) ProtoMessage() {}

func (x *SendRegistrationEmailCaptchaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRegistrationEmailCaptchaRequest.ProtoReflect.Descriptor instead.
func (*SendRegistrationEmailCaptchaRequest) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{17}
}

func (x *SendRegistrationEmailCaptchaRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type SendRegistrationEmailCaptchaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DebugMessage  *structpb.Value        `protobuf:"bytes,3,opt,name=debugMessage,proto3" json:"debugMessage,omitempty"`
	Oracle        string                 `protobuf:"bytes,4,opt,name=oracle,proto3" json:"oracle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRegistrationEmailCaptchaResponse) Reset() {
	*x = SendRegistrationEmailCaptchaResponse{}
	mi := &file_api_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRegistrationEmailCaptchaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRegistrationEmailCaptchaResponse) ProtoMessage() {}

func (x *SendRegistrationEmailCaptchaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRegistrationEmailCaptchaResponse.ProtoReflect.Descriptor instead.
func (*SendRegistrationEmailCaptchaResponse) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{18}
}

func (x *SendRegistrationEmailCaptchaResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SendRegistrationEmailCaptchaResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendRegistrationEmailCaptchaResponse) GetDebugMessage() *structpb.Value {
	if x != nil {
		return x.DebugMessage
	}
	return nil
}

func (x *SendRegistrationEmailCaptchaResponse) GetOracle() string {
	if x != nil {
		return x.Oracle
	}
	return ""
}

type QRLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty" validate:"required"` // @gotags: validate:"required"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QRLoginRequest) Reset() {
	*x = QRLoginRequest{}
	mi := &file_api_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QRLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QRLoginRequest) ProtoMessage() {}

func (x *QRLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QRLoginRequest.ProtoReflect.Descriptor instead.
func (*QRLoginRequest) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{19}
}

func (x *QRLoginRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type QRLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DebugMessage  *structpb.Value        `protobuf:"bytes,3,opt,name=debugMessage,proto3" json:"debugMessage,omitempty"`
	Oracle        string                 `protobuf:"bytes,4,opt,name=oracle,proto3" json:"oracle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QRLoginResponse) Reset() {
	*x = QRLoginResponse{}
	mi := &file_api_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QRLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QRLoginResponse) ProtoMessage() {}

func (x *QRLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QRLoginResponse.ProtoReflect.Descriptor instead.
func (*QRLoginResponse) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{20}
}

func (x *QRLoginResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *QRLoginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *QRLoginResponse) GetDebugMessage() *structpb.Value {
	if x != nil {
		return x.DebugMessage
	}
	return nil
}

func (x *QRLoginResponse) GetOracle() string {
	if x != nil {
		return x.Oracle
	}
	return ""
}

type SendLoginEmailCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty" validate:"required"` // @gotags: validate:"required"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendLoginEmailCodeRequest) Reset() {
	*x = SendLoginEmailCodeRequest{}
	mi := &file_api_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendLoginEmailCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendLoginEmailCodeRequest) ProtoMessage() {}

func (x *SendLoginEmailCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendLoginEmailCodeRequest.ProtoReflect.Descriptor instead.
func (*SendLoginEmailCodeRequest) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{21}
}

func (x *SendLoginEmailCodeRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type SendLoginEmailCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DebugMessage  *structpb.Value        `protobuf:"bytes,3,opt,name=debugMessage,proto3" json:"debugMessage,omitempty"`
	Oracle        string                 `protobuf:"bytes,4,opt,name=oracle,proto3" json:"oracle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendLoginEmailCodeResponse) Reset() {
	*x = SendLoginEmailCodeResponse{}
	mi := &file_api_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendLoginEmailCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendLoginEmailCodeResponse) ProtoMessage() {}

func (x *SendLoginEmailCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendLoginEmailCodeResponse.ProtoReflect.Descriptor instead.
func (*SendLoginEmailCodeResponse) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{22}
}

func (x *SendLoginEmailCodeResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SendLoginEmailCodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendLoginEmailCodeResponse) GetDebugMessage() *structpb.Value {
	if x != nil {
		return x.DebugMessage
	}
	return nil
}

func (x *SendLoginEmailCodeResponse) GetOracle() string {
	if x != nil {
		return x.Oracle
	}
	return ""
}

type LoginByEmailCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty" validate:"required"` // @gotags: validate:"required"
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty" validate:"required"`   // @gotags: validate:"required"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginByEmailCodeRequest) Reset() {
	*x = LoginByEmailCodeRequest{}
	mi := &file_api_user_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginByEmailCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginByEmailCodeRequest) ProtoMessage() {}

func (x *LoginByEmailCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginByEmailCodeRequest.ProtoReflect.Descriptor instead.
func (*LoginByEmailCodeRequest) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{23}
}

func (x *LoginByEmailCodeRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginByEmailCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type UpdateNicknameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty" validate:"required"` // @gotags: validate:"required"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNicknameRequest) Reset() {
	*x = UpdateNicknameRequest{}
	mi := &file_api_user_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNicknameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNicknameRequest) ProtoMessage() {}

func (x *UpdateNicknameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNicknameRequest.ProtoReflect.Descriptor instead.
func (*UpdateNicknameRequest) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateNicknameRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type UpdateNicknameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DebugMessage  *structpb.Value        `protobuf:"bytes,3,opt,name=debugMessage,proto3" json:"debugMessage,omitempty"`
	Oracle        string                 `protobuf:"bytes,4,opt,name=oracle,proto3" json:"oracle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNicknameResponse) Reset() {
	*x = UpdateNicknameResponse{}
	mi := &file_api_user_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNicknameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNicknameResponse) ProtoMessage() {}

func (x *UpdateNicknameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNicknameResponse.ProtoReflect.Descriptor instead.
func (*UpdateNicknameResponse) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateNicknameResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateNicknameResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateNicknameResponse) GetDebugMessage() *structpb.Value {
	if x != nil {
		return x.DebugMessage
	}
	return nil
}

func (x *UpdateNicknameResponse) GetOracle() string {
	if x != nil {
		return x.Oracle
	}
	return ""
}

type UnregisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DebugMessage  *structpb.Value        `protobuf:"bytes,3,opt,name=debugMessage,proto3" json:"debugMessage,omitempty"`
	Oracle        string                 `protobuf:"bytes,4,opt,name=oracle,proto3" json:"oracle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterResponse) Reset() {
	*x = UnregisterResponse{}
	mi := &file_api_user_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterResponse) ProtoMessage() {}

func (x *UnregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterResponse.ProtoReflect.Descriptor instead.
func (*UnregisterResponse) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{26}
}

func (x *UnregisterResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UnregisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UnregisterResponse) GetDebugMessage() *structpb.Value {
	if x != nil {
		return x.DebugMessage
	}
	return nil
}

func (x *UnregisterResponse) GetOracle() string {
	if x != nil {
		return x.Oracle
	}
	return ""
}

type RandomNicknameResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Code          int32                        `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DebugMessage  *structpb.Value              `protobuf:"bytes,3,opt,name=debugMessage,proto3" json:"debugMessage,omitempty"`
	Oracle        string                       `protobuf:"bytes,4,opt,name=oracle,proto3" json:"oracle,omitempty"`
	Data          *RandomNicknameResponse_Data `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RandomNicknameResponse) Reset() {
	*x = RandomNicknameResponse{}
	mi := &file_api_user_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RandomNicknameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandomNicknameResponse) ProtoMessage() {}

func (x *RandomNicknameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandomNicknameResponse.ProtoReflect.Descriptor instead.
func (*RandomNicknameResponse) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{27}
}

func (x *RandomNicknameResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RandomNicknameResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RandomNicknameResponse) GetDebugMessage() *structpb.Value {
	if x != nil {
		return x.DebugMessage
	}
	return nil
}

func (x *RandomNicknameResponse) GetOracle() string {
	if x != nil {
		return x.Oracle
	}
	return ""
}

func (x *RandomNicknameResponse) GetData() *RandomNicknameResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetRegistrationEmailCaptchasResponse struct {
	state         protoimpl.MessageState                     `protogen:"open.v1"`
	Code          int32                                      `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                                     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DebugMessage  *structpb.Value                            `protobuf:"bytes,3,opt,name=debugMessage,proto3" json:"debugMessage,omitempty"`
	Oracle        string                                     `protobuf:"bytes,4,opt,name=oracle,proto3" json:"oracle,omitempty"`
	Data          *GetRegistrationEmailCaptchasResponse_Data `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRegistrationEmailCaptchasResponse) Reset() {
	*x = GetRegistrationEmailCaptchasResponse{}
	mi := &file_api_user_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRegistrationEmailCaptchasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegistrationEmailCaptchasResponse) ProtoMessage() {}

func (x *GetRegistrationEmailCaptchasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegistrationEmailCaptchasResponse.ProtoReflect.Descriptor instead.
func (*GetRegistrationEmailCaptchasResponse) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{28}
}

func (x *GetRegistrationEmailCaptchasResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetRegistrationEmailCaptchasResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetRegistrationEmailCaptchasResponse) GetDebugMessage() *structpb.Value {
	if x != nil {
		return x.DebugMessage
	}
	return nil
}

func (x *GetRegistrationEmailCaptchasResponse) GetOracle() string {
	if x != nil {
		return x.Oracle
	}
	return ""
}

func (x *GetRegistrationEmailCaptchasResponse) GetData() *GetRegistrationEmailCaptchasResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetLoginEmailCaptchasResponse struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Code          int32                               `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                              `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DebugMessage  *structpb.Value                     `protobuf:"bytes,3,opt,name=debugMessage,proto3" json:"debugMessage,omitempty"`
	Oracle        string                              `protobuf:"bytes,4,opt,name=oracle,proto3" json:"oracle,omitempty"`
	Data          *GetLoginEmailCaptchasResponse_Data `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoginEmailCaptchasResponse) Reset() {
	*x = GetLoginEmailCaptchasResponse{}
	mi := &file_api_user_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoginEmailCaptchasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoginEmailCaptchasResponse) ProtoMessage() {}

func (x *GetLoginEmailCaptchasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoginEmailCaptchasResponse.ProtoReflect.Descriptor instead.
func (*GetLoginEmailCaptchasResponse) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{29}
}

func (x *GetLoginEmailCaptchasResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetLoginEmailCaptchasResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetLoginEmailCaptchasResponse) GetDebugMessage() *structpb.Value {
	if x != nil {
		return x.DebugMessage
	}
	return nil
}

func (x *GetLoginEmailCaptchasResponse) GetOracle() string {
	if x != nil {
		return x.Oracle
	}
	return ""
}

func (x *GetLoginEmailCaptchasResponse) GetData() *GetLoginEmailCaptchasResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type CheckRegistrationResponse_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRegistrationResponse_Data) Reset() {
	*x = CheckRegistrationResponse_Data{}
	mi := &file_api_user_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRegistrationResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRegistrationResponse_Data) ProtoMessage() {}

func (x *CheckRegistrationResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRegistrationResponse_Data.ProtoReflect.Descriptor instead.
func (*CheckRegistrationResponse_Data) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{4, 0}
}

func (x *CheckRegistrationResponse_Data) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CheckRegistrationResponse_Data) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type ValidateUserIDsResponse_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []bool                 `protobuf:"varint,1,rep,packed,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateUserIDsResponse_Data) Reset() {
	*x = ValidateUserIDsResponse_Data{}
	mi := &file_api_user_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateUserIDsResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateUserIDsResponse_Data) ProtoMessage() {}

func (x *ValidateUserIDsResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateUserIDsResponse_Data.ProtoReflect.Descriptor instead.
func (*ValidateUserIDsResponse_Data) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{6, 0}
}

func (x *ValidateUserIDsResponse_Data) GetList() []bool {
	if x != nil {
		return x.List
	}
	return nil
}

type GetUserInfoResponse_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoResponse_Data) Reset() {
	*x = GetUserInfoResponse_Data{}
	mi := &file_api_user_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResponse_Data) ProtoMessage() {}

func (x *GetUserInfoResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResponse_Data.ProtoReflect.Descriptor instead.
func (*GetUserInfoResponse_Data) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{8, 0}
}

func (x *GetUserInfoResponse_Data) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetUserInfoResponse_Data) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GetUserInfoResponse_Data) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type LoginResponse_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int64                  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse_Data) Reset() {
	*x = LoginResponse_Data{}
	mi := &file_api_user_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse_Data) ProtoMessage() {}

func (x *LoginResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse_Data.ProtoReflect.Descriptor instead.
func (*LoginResponse_Data) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{13, 0}
}

func (x *LoginResponse_Data) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *LoginResponse_Data) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *LoginResponse_Data) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginResponse_Data) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type RandomNicknameResponse_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RandomNicknameResponse_Data) Reset() {
	*x = RandomNicknameResponse_Data{}
	mi := &file_api_user_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RandomNicknameResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandomNicknameResponse_Data) ProtoMessage() {}

func (x *RandomNicknameResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandomNicknameResponse_Data.ProtoReflect.Descriptor instead.
func (*RandomNicknameResponse_Data) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{27, 0}
}

func (x *RandomNicknameResponse_Data) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type GetRegistrationEmailCaptchasResponse_EmailCaptcha struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRegistrationEmailCaptchasResponse_EmailCaptcha) Reset() {
	*x = GetRegistrationEmailCaptchasResponse_EmailCaptcha{}
	mi := &file_api_user_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRegistrationEmailCaptchasResponse_EmailCaptcha) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegistrationEmailCaptchasResponse_EmailCaptcha) ProtoMessage() {}

func (x *GetRegistrationEmailCaptchasResponse_EmailCaptcha) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegistrationEmailCaptchasResponse_EmailCaptcha.ProtoReflect.Descriptor instead.
func (*GetRegistrationEmailCaptchasResponse_EmailCaptcha) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{28, 0}
}

func (x *GetRegistrationEmailCaptchasResponse_EmailCaptcha) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetRegistrationEmailCaptchasResponse_EmailCaptcha) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type GetRegistrationEmailCaptchasResponse_Data struct {
	state         protoimpl.MessageState                               `protogen:"open.v1"`
	List          []*GetRegistrationEmailCaptchasResponse_EmailCaptcha `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRegistrationEmailCaptchasResponse_Data) Reset() {
	*x = GetRegistrationEmailCaptchasResponse_Data{}
	mi := &file_api_user_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRegistrationEmailCaptchasResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegistrationEmailCaptchasResponse_Data) ProtoMessage() {}

func (x *GetRegistrationEmailCaptchasResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegistrationEmailCaptchasResponse_Data.ProtoReflect.Descriptor instead.
func (*GetRegistrationEmailCaptchasResponse_Data) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{28, 1}
}

func (x *GetRegistrationEmailCaptchasResponse_Data) GetList() []*GetRegistrationEmailCaptchasResponse_EmailCaptcha {
	if x != nil {
		return x.List
	}
	return nil
}

type GetLoginEmailCaptchasResponse_EmailCaptcha struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoginEmailCaptchasResponse_EmailCaptcha) Reset() {
	*x = GetLoginEmailCaptchasResponse_EmailCaptcha{}
	mi := &file_api_user_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoginEmailCaptchasResponse_EmailCaptcha) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoginEmailCaptchasResponse_EmailCaptcha) ProtoMessage() {}

func (x *GetLoginEmailCaptchasResponse_EmailCaptcha) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoginEmailCaptchasResponse_EmailCaptcha.ProtoReflect.Descriptor instead.
func (*GetLoginEmailCaptchasResponse_EmailCaptcha) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{29, 0}
}

func (x *GetLoginEmailCaptchasResponse_EmailCaptcha) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetLoginEmailCaptchasResponse_EmailCaptcha) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type GetLoginEmailCaptchasResponse_Data struct {
	state         protoimpl.MessageState                        `protogen:"open.v1"`
	List          []*GetLoginEmailCaptchasResponse_EmailCaptcha `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoginEmailCaptchasResponse_Data) Reset() {
	*x = GetLoginEmailCaptchasResponse_Data{}
	mi := &file_api_user_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoginEmailCaptchasResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoginEmailCaptchasResponse_Data) ProtoMessage() {}

func (x *GetLoginEmailCaptchasResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoginEmailCaptchasResponse_Data.ProtoReflect.Descriptor instead.
func (*GetLoginEmailCaptchasResponse_Data) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{29, 1}
}

func (x *GetLoginEmailCaptchasResponse_Data) GetList() []*GetLoginEmailCaptchasResponse_EmailCaptcha {
	if x != nil {
		return x.List
	}
	return nil
}

var File_api_user_proto protoreflect.FileDescriptor

const file_api_user_proto_rawDesc = "" +
	"\n" +
	"\x0eapi/user.proto\x12\tslark_api\x1a\x1cgoogle/protobuf/struct.proto\"[\n" +
	"\x1fLoginBySecondaryPasswordRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\"\n" +
	"\fpasswordHash\x18\x02 \x01(\tR\fpasswordHash\"t\n" +
	"\x1eUpdateSecondaryPasswordRequest\x12(\n" +
	"\x0foldPasswordHash\x18\x01 \x01(\tR\x0foldPasswordHash\x12(\n" +
	"\x0fnewPasswordHash\x18\x02 \x01(\tR\x0fnewPasswordHash\"D\n" +
	"\x1eCreateSecondaryPasswordRequest\x12\"\n" +
	"\fpasswordHash\x18\x01 \x01(\tR\fpasswordHash\"0\n" +
	"\x18CheckRegistrationRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"\x90\x02\n" +
	"\x19CheckRegistrationResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12:\n" +
	"\fdebugMessage\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\fdebugMessage\x12\x16\n" +
	"\x06oracle\x18\x04 \x01(\tR\x06oracle\x12=\n" +
	"\x04data\x18\x05 \x01(\v2).slark_api.CheckRegistrationResponse.DataR\x04data\x1a2\n" +
	"\x04Data\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\"2\n" +
	"\x16ValidateUserIDsRequest\x12\x18\n" +
	"\auserIDs\x18\x01 \x03(\x03R\auserIDs\"\xf4\x01\n" +
	"\x17ValidateUserIDsResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12:\n" +
	"\fdebugMessage\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\fdebugMessage\x12\x16\n" +
	"\x06oracle\x18\x04 \x01(\tR\x06oracle\x12;\n" +
	"\x04data\x18\x05 \x01(\v2'.slark_api.ValidateUserIDsResponse.DataR\x04data\x1a\x1a\n" +
	"\x04Data\x12\x12\n" +
	"\x04list\x18\x01 \x03(\bR\x04list\"$\n" +
	"\x12GetUserInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x9a\x02\n" +
	"\x13GetUserInfoResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12:\n" +
	"\fdebugMessage\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\fdebugMessage\x12\x16\n" +
	"\x06oracle\x18\x04 \x01(\tR\x06oracle\x127\n" +
	"\x04data\x18\x05 \x01(\v2#.slark_api.GetUserInfoResponse.DataR\x04data\x1aH\n" +
	"\x04Data\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"\a\n" +
	"\x05Empty\"\x91\x01\n" +
	"\rEmptyResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12:\n" +
	"\fdebugMessage\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\fdebugMessage\x12\x16\n" +
	"\x06oracle\x18\x04 \x01(\tR\x06oracle\"M\n" +
	"\x11PhoneLoginRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\"\n" +
	"\fpasswordHash\x18\x02 \x01(\tR\fpasswordHash\"M\n" +
	"\x11EmailLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\"\n" +
	"\fpasswordHash\x18\x02 \x01(\tR\fpasswordHash\"\xac\x02\n" +
	"\rLoginResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12:\n" +
	"\fdebugMessage\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\fdebugMessage\x12\x16\n" +
	"\x06oracle\x18\x04 \x01(\tR\x06oracle\x121\n" +
	"\x04data\x18\x05 \x01(\v2\x1d.slark_api.LoginResponse.DataR\x04data\x1af\n" +
	"\x04Data\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x03R\x06userID\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\"\x88\x01\n" +
	"\x16RegisterByEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\"\n" +
	"\fpasswordHash\x18\x03 \x01(\tR\fpasswordHash\x12\x18\n" +
	"\acaptcha\x18\x04 \x01(\tR\acaptcha\"O\n" +
	"\x1dRegisterByEmailCaptchaRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x18\n" +
	"\acaptcha\x18\x02 \x01(\tR\acaptcha\"S\n" +
	"\x13LoginByAppleRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12&\n" +
	"\x0euserIdentifier\x18\x02 \x01(\tR\x0euserIdentifier\";\n" +
	"#SendRegistrationEmailCaptchaRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"\xa8\x01\n" +
	"$SendRegistrationEmailCaptchaResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12:\n" +
	"\fdebugMessage\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\fdebugMessage\x12\x16\n" +
	"\x06oracle\x18\x04 \x01(\tR\x06oracle\"&\n" +
	"\x0eQRLoginRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x93\x01\n" +
	"\x0fQRLoginResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12:\n" +
	"\fdebugMessage\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\fdebugMessage\x12\x16\n" +
	"\x06oracle\x18\x04 \x01(\tR\x06oracle\"1\n" +
	"\x19SendLoginEmailCodeRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"\x9e\x01\n" +
	"\x1aSendLoginEmailCodeResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12:\n" +
	"\fdebugMessage\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\fdebugMessage\x12\x16\n" +
	"\x06oracle\x18\x04 \x01(\tR\x06oracle\"C\n" +
	"\x17LoginByEmailCodeRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"3\n" +
	"\x15UpdateNicknameRequest\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\"\x9a\x01\n" +
	"\x16UpdateNicknameResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12:\n" +
	"\fdebugMessage\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\fdebugMessage\x12\x16\n" +
	"\x06oracle\x18\x04 \x01(\tR\x06oracle\"\x96\x01\n" +
	"\x12UnregisterResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12:\n" +
	"\fdebugMessage\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\fdebugMessage\x12\x16\n" +
	"\x06oracle\x18\x04 \x01(\tR\x06oracle\"\xfa\x01\n" +
	"\x16RandomNicknameResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12:\n" +
	"\fdebugMessage\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\fdebugMessage\x12\x16\n" +
	"\x06oracle\x18\x04 \x01(\tR\x06oracle\x12:\n" +
	"\x04data\x18\x05 \x01(\v2&.slark_api.RandomNicknameResponse.DataR\x04data\x1a\"\n" +
	"\x04Data\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\"\x86\x03\n" +
	"$GetRegistrationEmailCaptchasResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12:\n" +
	"\fdebugMessage\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\fdebugMessage\x12\x16\n" +
	"\x06oracle\x18\x04 \x01(\tR\x06oracle\x12H\n" +
	"\x04data\x18\x05 \x01(\v24.slark_api.GetRegistrationEmailCaptchasResponse.DataR\x04data\x1a8\n" +
	"\fEmailCaptcha\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x1aX\n" +
	"\x04Data\x12P\n" +
	"\x04list\x18\x01 \x03(\v2<.slark_api.GetRegistrationEmailCaptchasResponse.EmailCaptchaR\x04list\"\xf1\x02\n" +
	"\x1dGetLoginEmailCaptchasResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12:\n" +
	"\fdebugMessage\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\fdebugMessage\x12\x16\n" +
	"\x06oracle\x18\x04 \x01(\tR\x06oracle\x12A\n" +
	"\x04data\x18\x05 \x01(\v2-.slark_api.GetLoginEmailCaptchasResponse.DataR\x04data\x1a8\n" +
	"\fEmailCaptcha\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x1aQ\n" +
	"\x04Data\x12I\n" +
	"\x04list\x18\x01 \x03(\v25.slark_api.GetLoginEmailCaptchasResponse.EmailCaptchaR\x04list2\x84\x0e\n" +
	"\vUserService\x12F\n" +
	"\fLoginByPhone\x12\x1c.slark_api.PhoneLoginRequest\x1a\x18.slark_api.LoginResponse\x12F\n" +
	"\fLoginByEmail\x12\x1c.slark_api.EmailLoginRequest\x1a\x18.slark_api.LoginResponse\x12<\n" +
	"\x0eLoginBySession\x12\x10.slark_api.Empty\x1a\x18.slark_api.LoginResponse\x12H\n" +
	"\fLoginByApple\x12\x1e.slark_api.LoginByAppleRequest\x1a\x18.slark_api.LoginResponse\x12N\n" +
	"\x0fRegisterByEmail\x12!.slark_api.RegisterByEmailRequest\x1a\x18.slark_api.LoginResponse\x12\\\n" +
	"\x16RegisterByEmailCaptcha\x12(.slark_api.RegisterByEmailCaptchaRequest\x1a\x18.slark_api.LoginResponse\x12\x7f\n" +
	"\x1cSendRegistrationEmailCaptcha\x12..slark_api.SendRegistrationEmailCaptchaRequest\x1a/.slark_api.SendRegistrationEmailCaptchaResponse\x12=\n" +
	"\x0fLogOutBySession\x12\x10.slark_api.Empty\x1a\x18.slark_api.EmptyResponse\x128\n" +
	"\n" +
	"CheckLogin\x12\x10.slark_api.Empty\x1a\x18.slark_api.EmptyResponse\x127\n" +
	"\tLoginInfo\x12\x10.slark_api.Empty\x1a\x18.slark_api.LoginResponse\x12@\n" +
	"\aQRLogin\x12\x19.slark_api.QRLoginRequest\x1a\x1a.slark_api.QRLoginResponse\x12a\n" +
	"\x12SendLoginEmailCode\x12$.slark_api.SendLoginEmailCodeRequest\x1a%.slark_api.SendLoginEmailCodeResponse\x12P\n" +
	"\x10LoginByEmailCode\x12\".slark_api.LoginByEmailCodeRequest\x1a\x18.slark_api.LoginResponse\x12U\n" +
	"\x0eUpdateNickname\x12 .slark_api.UpdateNicknameRequest\x1a!.slark_api.UpdateNicknameResponse\x12=\n" +
	"\n" +
	"Unregister\x12\x10.slark_api.Empty\x1a\x1d.slark_api.UnregisterResponse\x12E\n" +
	"\x0eRandomNickname\x12\x10.slark_api.Empty\x1a!.slark_api.RandomNicknameResponse\x12L\n" +
	"\vGetUserInfo\x12\x1d.slark_api.GetUserInfoRequest\x1a\x1e.slark_api.GetUserInfoResponse\x12X\n" +
	"\x0fValidateUserIDs\x12!.slark_api.ValidateUserIDsRequest\x1a\".slark_api.ValidateUserIDsResponse\x12^\n" +
	"\x11CheckRegistration\x12#.slark_api.CheckRegistrationRequest\x1a$.slark_api.CheckRegistrationResponse\x12^\n" +
	"\x17CreateSecondaryPassword\x12).slark_api.CreateSecondaryPasswordRequest\x1a\x18.slark_api.EmptyResponse\x12^\n" +
	"\x17UpdateSecondaryPassword\x12).slark_api.UpdateSecondaryPasswordRequest\x1a\x18.slark_api.EmptyResponse\x12`\n" +
	"\x18LoginBySecondaryPassword\x12*.slark_api.LoginBySecondaryPasswordRequest\x1a\x18.slark_api.LoginResponse2\xc5\x01\n" +
	"\vTestService\x12a\n" +
	"\x1cGetRegistrationEmailCaptchas\x12\x10.slark_api.Empty\x1a/.slark_api.GetRegistrationEmailCaptchasResponse\x12S\n" +
	"\x15GetLoginEmailCaptchas\x12\x10.slark_api.Empty\x1a(.slark_api.GetLoginEmailCaptchasResponseB\aZ\x05./apib\x06proto3"

var (
	file_api_user_proto_rawDescOnce sync.Once
	file_api_user_proto_rawDescData []byte
)

func file_api_user_proto_rawDescGZIP() []byte {
	file_api_user_proto_rawDescOnce.Do(func() {
		file_api_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_user_proto_rawDesc), len(file_api_user_proto_rawDesc)))
	})
	return file_api_user_proto_rawDescData
}

var file_api_user_proto_msgTypes = make([]protoimpl.MessageInfo, 39)
var file_api_user_proto_goTypes = []any{
	(*LoginBySecondaryPasswordRequest)(nil),                   // 0: slark_api.LoginBySecondaryPasswordRequest
	(*UpdateSecondaryPasswordRequest)(nil),                    // 1: slark_api.UpdateSecondaryPasswordRequest
	(*CreateSecondaryPasswordRequest)(nil),                    // 2: slark_api.CreateSecondaryPasswordRequest
	(*CheckRegistrationRequest)(nil),                          // 3: slark_api.CheckRegistrationRequest
	(*CheckRegistrationResponse)(nil),                         // 4: slark_api.CheckRegistrationResponse
	(*ValidateUserIDsRequest)(nil),                            // 5: slark_api.ValidateUserIDsRequest
	(*ValidateUserIDsResponse)(nil),                           // 6: slark_api.ValidateUserIDsResponse
	(*GetUserInfoRequest)(nil),                                // 7: slark_api.GetUserInfoRequest
	(*GetUserInfoResponse)(nil),                               // 8: slark_api.GetUserInfoResponse
	(*Empty)(nil),                                             // 9: slark_api.Empty
	(*EmptyResponse)(nil),                                     // 10: slark_api.EmptyResponse
	(*PhoneLoginRequest)(nil),                                 // 11: slark_api.PhoneLoginRequest
	(*EmailLoginRequest)(nil),                                 // 12: slark_api.EmailLoginRequest
	(*LoginResponse)(nil),                                     // 13: slark_api.LoginResponse
	(*RegisterByEmailRequest)(nil),                            // 14: slark_api.RegisterByEmailRequest
	(*RegisterByEmailCaptchaRequest)(nil),                     // 15: slark_api.RegisterByEmailCaptchaRequest
	(*LoginByAppleRequest)(nil),                               // 16: slark_api.LoginByAppleRequest
	(*SendRegistrationEmailCaptchaRequest)(nil),               // 17: slark_api.SendRegistrationEmailCaptchaRequest
	(*SendRegistrationEmailCaptchaResponse)(nil),              // 18: slark_api.SendRegistrationEmailCaptchaResponse
	(*QRLoginRequest)(nil),                                    // 19: slark_api.QRLoginRequest
	(*QRLoginResponse)(nil),                                   // 20: slark_api.QRLoginResponse
	(*SendLoginEmailCodeRequest)(nil),                         // 21: slark_api.SendLoginEmailCodeRequest
	(*SendLoginEmailCodeResponse)(nil),                        // 22: slark_api.SendLoginEmailCodeResponse
	(*LoginByEmailCodeRequest)(nil),                           // 23: slark_api.LoginByEmailCodeRequest
	(*UpdateNicknameRequest)(nil),                             // 24: slark_api.UpdateNicknameRequest
	(*UpdateNicknameResponse)(nil),                            // 25: slark_api.UpdateNicknameResponse
	(*UnregisterResponse)(nil),                                // 26: slark_api.UnregisterResponse
	(*RandomNicknameResponse)(nil),                            // 27: slark_api.RandomNicknameResponse
	(*GetRegistrationEmailCaptchasResponse)(nil),              // 28: slark_api.GetRegistrationEmailCaptchasResponse
	(*GetLoginEmailCaptchasResponse)(nil),                     // 29: slark_api.GetLoginEmailCaptchasResponse
	(*CheckRegistrationResponse_Data)(nil),                    // 30: slark_api.CheckRegistrationResponse.Data
	(*ValidateUserIDsResponse_Data)(nil),                      // 31: slark_api.ValidateUserIDsResponse.Data
	(*GetUserInfoResponse_Data)(nil),                          // 32: slark_api.GetUserInfoResponse.Data
	(*LoginResponse_Data)(nil),                                // 33: slark_api.LoginResponse.Data
	(*RandomNicknameResponse_Data)(nil),                       // 34: slark_api.RandomNicknameResponse.Data
	(*GetRegistrationEmailCaptchasResponse_EmailCaptcha)(nil), // 35: slark_api.GetRegistrationEmailCaptchasResponse.EmailCaptcha
	(*GetRegistrationEmailCaptchasResponse_Data)(nil),         // 36: slark_api.GetRegistrationEmailCaptchasResponse.Data
	(*GetLoginEmailCaptchasResponse_EmailCaptcha)(nil),        // 37: slark_api.GetLoginEmailCaptchasResponse.EmailCaptcha
	(*GetLoginEmailCaptchasResponse_Data)(nil),                // 38: slark_api.GetLoginEmailCaptchasResponse.Data
	(*structpb.Value)(nil),                                    // 39: google.protobuf.Value
}
var file_api_user_proto_depIdxs = []int32{
	39, // 0: slark_api.CheckRegistrationResponse.debugMessage:type_name -> google.protobuf.Value
	30, // 1: slark_api.CheckRegistrationResponse.data:type_name -> slark_api.CheckRegistrationResponse.Data
	39, // 2: slark_api.ValidateUserIDsResponse.debugMessage:type_name -> google.protobuf.Value
	31, // 3: slark_api.ValidateUserIDsResponse.data:type_name -> slark_api.ValidateUserIDsResponse.Data
	39, // 4: slark_api.GetUserInfoResponse.debugMessage:type_name -> google.protobuf.Value
	32, // 5: slark_api.GetUserInfoResponse.data:type_name -> slark_api.GetUserInfoResponse.Data
	39, // 6: slark_api.EmptyResponse.debugMessage:type_name -> google.protobuf.Value
	39, // 7: slark_api.LoginResponse.debugMessage:type_name -> google.protobuf.Value
	33, // 8: slark_api.LoginResponse.data:type_name -> slark_api.LoginResponse.Data
	39, // 9: slark_api.SendRegistrationEmailCaptchaResponse.debugMessage:type_name -> google.protobuf.Value
	39, // 10: slark_api.QRLoginResponse.debugMessage:type_name -> google.protobuf.Value
	39, // 11: slark_api.SendLoginEmailCodeResponse.debugMessage:type_name -> google.protobuf.Value
	39, // 12: slark_api.UpdateNicknameResponse.debugMessage:type_name -> google.protobuf.Value
	39, // 13: slark_api.UnregisterResponse.debugMessage:type_name -> google.protobuf.Value
	39, // 14: slark_api.RandomNicknameResponse.debugMessage:type_name -> google.protobuf.Value
	34, // 15: slark_api.RandomNicknameResponse.data:type_name -> slark_api.RandomNicknameResponse.Data
	39, // 16: slark_api.GetRegistrationEmailCaptchasResponse.debugMessage:type_name -> google.protobuf.Value
	36, // 17: slark_api.GetRegistrationEmailCaptchasResponse.data:type_name -> slark_api.GetRegistrationEmailCaptchasResponse.Data
	39, // 18: slark_api.GetLoginEmailCaptchasResponse.debugMessage:type_name -> google.protobuf.Value
	38, // 19: slark_api.GetLoginEmailCaptchasResponse.data:type_name -> slark_api.GetLoginEmailCaptchasResponse.Data
	35, // 20: slark_api.GetRegistrationEmailCaptchasResponse.Data.list:type_name -> slark_api.GetRegistrationEmailCaptchasResponse.EmailCaptcha
	37, // 21: slark_api.GetLoginEmailCaptchasResponse.Data.list:type_name -> slark_api.GetLoginEmailCaptchasResponse.EmailCaptcha
	11, // 22: slark_api.UserService.LoginByPhone:input_type -> slark_api.PhoneLoginRequest
	12, // 23: slark_api.UserService.LoginByEmail:input_type -> slark_api.EmailLoginRequest
	9,  // 24: slark_api.UserService.LoginBySession:input_type -> slark_api.Empty
	16, // 25: slark_api.UserService.LoginByApple:input_type -> slark_api.LoginByAppleRequest
	14, // 26: slark_api.UserService.RegisterByEmail:input_type -> slark_api.RegisterByEmailRequest
	15, // 27: slark_api.UserService.RegisterByEmailCaptcha:input_type -> slark_api.RegisterByEmailCaptchaRequest
	17, // 28: slark_api.UserService.SendRegistrationEmailCaptcha:input_type -> slark_api.SendRegistrationEmailCaptchaRequest
	9,  // 29: slark_api.UserService.LogOutBySession:input_type -> slark_api.Empty
	9,  // 30: slark_api.UserService.CheckLogin:input_type -> slark_api.Empty
	9,  // 31: slark_api.UserService.LoginInfo:input_type -> slark_api.Empty
	19, // 32: slark_api.UserService.QRLogin:input_type -> slark_api.QRLoginRequest
	21, // 33: slark_api.UserService.SendLoginEmailCode:input_type -> slark_api.SendLoginEmailCodeRequest
	23, // 34: slark_api.UserService.LoginByEmailCode:input_type -> slark_api.LoginByEmailCodeRequest
	24, // 35: slark_api.UserService.UpdateNickname:input_type -> slark_api.UpdateNicknameRequest
	9,  // 36: slark_api.UserService.Unregister:input_type -> slark_api.Empty
	9,  // 37: slark_api.UserService.RandomNickname:input_type -> slark_api.Empty
	7,  // 38: slark_api.UserService.GetUserInfo:input_type -> slark_api.GetUserInfoRequest
	5,  // 39: slark_api.UserService.ValidateUserIDs:input_type -> slark_api.ValidateUserIDsRequest
	3,  // 40: slark_api.UserService.CheckRegistration:input_type -> slark_api.CheckRegistrationRequest
	2,  // 41: slark_api.UserService.CreateSecondaryPassword:input_type -> slark_api.CreateSecondaryPasswordRequest
	1,  // 42: slark_api.UserService.UpdateSecondaryPassword:input_type -> slark_api.UpdateSecondaryPasswordRequest
	0,  // 43: slark_api.UserService.LoginBySecondaryPassword:input_type -> slark_api.LoginBySecondaryPasswordRequest
	9,  // 44: slark_api.TestService.GetRegistrationEmailCaptchas:input_type -> slark_api.Empty
	9,  // 45: slark_api.TestService.GetLoginEmailCaptchas:input_type -> slark_api.Empty
	13, // 46: slark_api.UserService.LoginByPhone:output_type -> slark_api.LoginResponse
	13, // 47: slark_api.UserService.LoginByEmail:output_type -> slark_api.LoginResponse
	13, // 48: slark_api.UserService.LoginBySession:output_type -> slark_api.LoginResponse
	13, // 49: slark_api.UserService.LoginByApple:output_type -> slark_api.LoginResponse
	13, // 50: slark_api.UserService.RegisterByEmail:output_type -> slark_api.LoginResponse
	13, // 51: slark_api.UserService.RegisterByEmailCaptcha:output_type -> slark_api.LoginResponse
	18, // 52: slark_api.UserService.SendRegistrationEmailCaptcha:output_type -> slark_api.SendRegistrationEmailCaptchaResponse
	10, // 53: slark_api.UserService.LogOutBySession:output_type -> slark_api.EmptyResponse
	10, // 54: slark_api.UserService.CheckLogin:output_type -> slark_api.EmptyResponse
	13, // 55: slark_api.UserService.LoginInfo:output_type -> slark_api.LoginResponse
	20, // 56: slark_api.UserService.QRLogin:output_type -> slark_api.QRLoginResponse
	22, // 57: slark_api.UserService.SendLoginEmailCode:output_type -> slark_api.SendLoginEmailCodeResponse
	13, // 58: slark_api.UserService.LoginByEmailCode:output_type -> slark_api.LoginResponse
	25, // 59: slark_api.UserService.UpdateNickname:output_type -> slark_api.UpdateNicknameResponse
	26, // 60: slark_api.UserService.Unregister:output_type -> slark_api.UnregisterResponse
	27, // 61: slark_api.UserService.RandomNickname:output_type -> slark_api.RandomNicknameResponse
	8,  // 62: slark_api.UserService.GetUserInfo:output_type -> slark_api.GetUserInfoResponse
	6,  // 63: slark_api.UserService.ValidateUserIDs:output_type -> slark_api.ValidateUserIDsResponse
	4,  // 64: slark_api.UserService.CheckRegistration:output_type -> slark_api.CheckRegistrationResponse
	10, // 65: slark_api.UserService.CreateSecondaryPassword:output_type -> slark_api.EmptyResponse
	10, // 66: slark_api.UserService.UpdateSecondaryPassword:output_type -> slark_api.EmptyResponse
	13, // 67: slark_api.UserService.LoginBySecondaryPassword:output_type -> slark_api.LoginResponse
	28, // 68: slark_api.TestService.GetRegistrationEmailCaptchas:output_type -> slark_api.GetRegistrationEmailCaptchasResponse
	29, // 69: slark_api.TestService.GetLoginEmailCaptchas:output_type -> slark_api.GetLoginEmailCaptchasResponse
	46, // [46:70] is the sub-list for method output_type
	22, // [22:46] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_api_user_proto_init() }
func file_api_user_proto_init() {
	if File_api_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_user_proto_rawDesc), len(file_api_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_user_proto_goTypes,
		DependencyIndexes: file_api_user_proto_depIdxs,
		MessageInfos:      file_api_user_proto_msgTypes,
	}.Build()
	File_api_user_proto = out.File
	file_api_user_proto_goTypes = nil
	file_api_user_proto_depIdxs = nil
}
