// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAPIKey = "api_key"

// APIKey mapped from table <api_key>
type APIKey struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt  time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt  int64     `gorm:"column:deleted_at;not null;comment:Coding style" json:"deleted_at"` // Coding style
	App        string    `gorm:"column:app;not null" json:"app"`
	KeyID      string    `gorm:"column:key_id;not null" json:"key_id"`
	Name       string    `gorm:"column:name;not null" json:"name"`
	Permission string    `gorm:"column:permission;not null" json:"permission"`
}

// TableName APIKey's table name
func (*APIKey) TableName() string {
	return TableNameAPIKey
}
