// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.28.0--dev
// source: api/invoker.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AdminService_GetSites_FullMethodName        = "/invoker_api.AdminService/GetSites"
	AdminService_AddSite_FullMethodName         = "/invoker_api.AdminService/AddSite"
	AdminService_EditSite_FullMethodName        = "/invoker_api.AdminService/EditSite"
	AdminService_DeleteSite_FullMethodName      = "/invoker_api.AdminService/DeleteSite"
	AdminService_GetSiteAdmins_FullMethodName   = "/invoker_api.AdminService/GetSiteAdmins"
	AdminService_AddSiteAdmin_FullMethodName    = "/invoker_api.AdminService/AddSiteAdmin"
	AdminService_DeleteSiteAdmin_FullMethodName = "/invoker_api.AdminService/DeleteSiteAdmin"
	AdminService_GetStorageInfo_FullMethodName  = "/invoker_api.AdminService/GetStorageInfo"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminServiceClient interface {
	GetSites(ctx context.Context, in *GetSitesRequest, opts ...grpc.CallOption) (*GetSitesResponse, error)
	AddSite(ctx context.Context, in *AddSiteRequest, opts ...grpc.CallOption) (*AddSiteResponse, error)
	EditSite(ctx context.Context, in *EditSiteRequest, opts ...grpc.CallOption) (*EditSiteResponse, error)
	DeleteSite(ctx context.Context, in *DeleteSiteRequest, opts ...grpc.CallOption) (*DeleteSiteResponse, error)
	GetSiteAdmins(ctx context.Context, in *GetSiteAdminsRequest, opts ...grpc.CallOption) (*GetSiteAdminsResponse, error)
	AddSiteAdmin(ctx context.Context, in *AddSiteAdminRequest, opts ...grpc.CallOption) (*AddSiteAdminResponse, error)
	DeleteSiteAdmin(ctx context.Context, in *DeleteSiteAdminRequest, opts ...grpc.CallOption) (*DeleteSiteAdminResponse, error)
	GetStorageInfo(ctx context.Context, in *GetStorageInfoRequest, opts ...grpc.CallOption) (*GetStorageInfoResponse, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) GetSites(ctx context.Context, in *GetSitesRequest, opts ...grpc.CallOption) (*GetSitesResponse, error) {
	out := new(GetSitesResponse)
	err := c.cc.Invoke(ctx, AdminService_GetSites_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) AddSite(ctx context.Context, in *AddSiteRequest, opts ...grpc.CallOption) (*AddSiteResponse, error) {
	out := new(AddSiteResponse)
	err := c.cc.Invoke(ctx, AdminService_AddSite_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) EditSite(ctx context.Context, in *EditSiteRequest, opts ...grpc.CallOption) (*EditSiteResponse, error) {
	out := new(EditSiteResponse)
	err := c.cc.Invoke(ctx, AdminService_EditSite_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) DeleteSite(ctx context.Context, in *DeleteSiteRequest, opts ...grpc.CallOption) (*DeleteSiteResponse, error) {
	out := new(DeleteSiteResponse)
	err := c.cc.Invoke(ctx, AdminService_DeleteSite_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetSiteAdmins(ctx context.Context, in *GetSiteAdminsRequest, opts ...grpc.CallOption) (*GetSiteAdminsResponse, error) {
	out := new(GetSiteAdminsResponse)
	err := c.cc.Invoke(ctx, AdminService_GetSiteAdmins_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) AddSiteAdmin(ctx context.Context, in *AddSiteAdminRequest, opts ...grpc.CallOption) (*AddSiteAdminResponse, error) {
	out := new(AddSiteAdminResponse)
	err := c.cc.Invoke(ctx, AdminService_AddSiteAdmin_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) DeleteSiteAdmin(ctx context.Context, in *DeleteSiteAdminRequest, opts ...grpc.CallOption) (*DeleteSiteAdminResponse, error) {
	out := new(DeleteSiteAdminResponse)
	err := c.cc.Invoke(ctx, AdminService_DeleteSiteAdmin_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetStorageInfo(ctx context.Context, in *GetStorageInfoRequest, opts ...grpc.CallOption) (*GetStorageInfoResponse, error) {
	out := new(GetStorageInfoResponse)
	err := c.cc.Invoke(ctx, AdminService_GetStorageInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility
type AdminServiceServer interface {
	GetSites(context.Context, *GetSitesRequest) (*GetSitesResponse, error)
	AddSite(context.Context, *AddSiteRequest) (*AddSiteResponse, error)
	EditSite(context.Context, *EditSiteRequest) (*EditSiteResponse, error)
	DeleteSite(context.Context, *DeleteSiteRequest) (*DeleteSiteResponse, error)
	GetSiteAdmins(context.Context, *GetSiteAdminsRequest) (*GetSiteAdminsResponse, error)
	AddSiteAdmin(context.Context, *AddSiteAdminRequest) (*AddSiteAdminResponse, error)
	DeleteSiteAdmin(context.Context, *DeleteSiteAdminRequest) (*DeleteSiteAdminResponse, error)
	GetStorageInfo(context.Context, *GetStorageInfoRequest) (*GetStorageInfoResponse, error)
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAdminServiceServer struct {
}

func (UnimplementedAdminServiceServer) GetSites(context.Context, *GetSitesRequest) (*GetSitesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSites not implemented")
}
func (UnimplementedAdminServiceServer) AddSite(context.Context, *AddSiteRequest) (*AddSiteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSite not implemented")
}
func (UnimplementedAdminServiceServer) EditSite(context.Context, *EditSiteRequest) (*EditSiteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditSite not implemented")
}
func (UnimplementedAdminServiceServer) DeleteSite(context.Context, *DeleteSiteRequest) (*DeleteSiteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSite not implemented")
}
func (UnimplementedAdminServiceServer) GetSiteAdmins(context.Context, *GetSiteAdminsRequest) (*GetSiteAdminsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSiteAdmins not implemented")
}
func (UnimplementedAdminServiceServer) AddSiteAdmin(context.Context, *AddSiteAdminRequest) (*AddSiteAdminResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSiteAdmin not implemented")
}
func (UnimplementedAdminServiceServer) DeleteSiteAdmin(context.Context, *DeleteSiteAdminRequest) (*DeleteSiteAdminResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSiteAdmin not implemented")
}
func (UnimplementedAdminServiceServer) GetStorageInfo(context.Context, *GetStorageInfoRequest) (*GetStorageInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStorageInfo not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_GetSites_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSitesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetSites(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetSites_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetSites(ctx, req.(*GetSitesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_AddSite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSiteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).AddSite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_AddSite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).AddSite(ctx, req.(*AddSiteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_EditSite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditSiteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).EditSite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_EditSite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).EditSite(ctx, req.(*EditSiteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_DeleteSite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSiteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).DeleteSite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_DeleteSite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).DeleteSite(ctx, req.(*DeleteSiteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetSiteAdmins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSiteAdminsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetSiteAdmins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetSiteAdmins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetSiteAdmins(ctx, req.(*GetSiteAdminsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_AddSiteAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSiteAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).AddSiteAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_AddSiteAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).AddSiteAdmin(ctx, req.(*AddSiteAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_DeleteSiteAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSiteAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).DeleteSiteAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_DeleteSiteAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).DeleteSiteAdmin(ctx, req.(*DeleteSiteAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetStorageInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStorageInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetStorageInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetStorageInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetStorageInfo(ctx, req.(*GetStorageInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "invoker_api.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSites",
			Handler:    _AdminService_GetSites_Handler,
		},
		{
			MethodName: "AddSite",
			Handler:    _AdminService_AddSite_Handler,
		},
		{
			MethodName: "EditSite",
			Handler:    _AdminService_EditSite_Handler,
		},
		{
			MethodName: "DeleteSite",
			Handler:    _AdminService_DeleteSite_Handler,
		},
		{
			MethodName: "GetSiteAdmins",
			Handler:    _AdminService_GetSiteAdmins_Handler,
		},
		{
			MethodName: "AddSiteAdmin",
			Handler:    _AdminService_AddSiteAdmin_Handler,
		},
		{
			MethodName: "DeleteSiteAdmin",
			Handler:    _AdminService_DeleteSiteAdmin_Handler,
		},
		{
			MethodName: "GetStorageInfo",
			Handler:    _AdminService_GetStorageInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/invoker.proto",
}

const (
	SiteService_GetSiteList_FullMethodName            = "/invoker_api.SiteService/GetSiteList"
	SiteService_GetSite_FullMethodName                = "/invoker_api.SiteService/GetSite"
	SiteService_GetCategoryList_FullMethodName        = "/invoker_api.SiteService/GetCategoryList"
	SiteService_GetCategory_FullMethodName            = "/invoker_api.SiteService/GetCategory"
	SiteService_AddCategory_FullMethodName            = "/invoker_api.SiteService/AddCategory"
	SiteService_EditCategory_FullMethodName           = "/invoker_api.SiteService/EditCategory"
	SiteService_DeleteCategory_FullMethodName         = "/invoker_api.SiteService/DeleteCategory"
	SiteService_GetPostList_FullMethodName            = "/invoker_api.SiteService/GetPostList"
	SiteService_GetPostDetail_FullMethodName          = "/invoker_api.SiteService/GetPostDetail"
	SiteService_AddPost_FullMethodName                = "/invoker_api.SiteService/AddPost"
	SiteService_EditPost_FullMethodName               = "/invoker_api.SiteService/EditPost"
	SiteService_DeletePost_FullMethodName             = "/invoker_api.SiteService/DeletePost"
	SiteService_GetComments_FullMethodName            = "/invoker_api.SiteService/GetComments"
	SiteService_AddComment_FullMethodName             = "/invoker_api.SiteService/AddComment"
	SiteService_EditComment_FullMethodName            = "/invoker_api.SiteService/EditComment"
	SiteService_DeleteComment_FullMethodName          = "/invoker_api.SiteService/DeleteComment"
	SiteService_AggregatedSitePage_FullMethodName     = "/invoker_api.SiteService/AggregatedSitePage"
	SiteService_AggregatedCategoryPage_FullMethodName = "/invoker_api.SiteService/AggregatedCategoryPage"
	SiteService_AggregatedPostPage_FullMethodName     = "/invoker_api.SiteService/AggregatedPostPage"
	SiteService_AggregatedSearchPage_FullMethodName   = "/invoker_api.SiteService/AggregatedSearchPage"
	SiteService_SearchPostComment_FullMethodName      = "/invoker_api.SiteService/SearchPostComment"
)

// SiteServiceClient is the client API for SiteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SiteServiceClient interface {
	GetSiteList(ctx context.Context, in *GetSiteListRequest, opts ...grpc.CallOption) (*GetSiteListResponse, error)
	GetSite(ctx context.Context, in *GetSiteRequest, opts ...grpc.CallOption) (*GetSiteResponse, error)
	GetCategoryList(ctx context.Context, in *GetCategoryListRequest, opts ...grpc.CallOption) (*GetCategoryListResponse, error)
	GetCategory(ctx context.Context, in *GetCategoryRequest, opts ...grpc.CallOption) (*GetCategoryResponse, error)
	AddCategory(ctx context.Context, in *AddCategoryRequest, opts ...grpc.CallOption) (*AddCategoryResponse, error)
	EditCategory(ctx context.Context, in *EditCategoryRequest, opts ...grpc.CallOption) (*EditCategoryResponse, error)
	DeleteCategory(ctx context.Context, in *DeleteCategoryRequest, opts ...grpc.CallOption) (*DeleteCategoryResponse, error)
	GetPostList(ctx context.Context, in *GetPostListRequest, opts ...grpc.CallOption) (*GetPostListResponse, error)
	GetPostDetail(ctx context.Context, in *GetPostDetailRequest, opts ...grpc.CallOption) (*GetPostDetailResponse, error)
	AddPost(ctx context.Context, in *AddPostRequest, opts ...grpc.CallOption) (*AddPostResponse, error)
	EditPost(ctx context.Context, in *EditPostRequest, opts ...grpc.CallOption) (*EditPostResponse, error)
	DeletePost(ctx context.Context, in *DeletePostRequest, opts ...grpc.CallOption) (*DeletePostResponse, error)
	GetComments(ctx context.Context, in *GetCommentsRequest, opts ...grpc.CallOption) (*GetCommentsResponse, error)
	AddComment(ctx context.Context, in *AddCommentRequest, opts ...grpc.CallOption) (*AddCommentResponse, error)
	EditComment(ctx context.Context, in *EditCommentRequest, opts ...grpc.CallOption) (*EditCommentResponse, error)
	DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*DeleteCommentResponse, error)
	AggregatedSitePage(ctx context.Context, in *AggregatedSitePageRequest, opts ...grpc.CallOption) (*AggregatedSitePageResponse, error)
	AggregatedCategoryPage(ctx context.Context, in *AggregatedCategoryPageRequest, opts ...grpc.CallOption) (*AggregatedCategoryPageResponse, error)
	AggregatedPostPage(ctx context.Context, in *AggregatedPostPageRequest, opts ...grpc.CallOption) (*AggregatedPostPageResponse, error)
	AggregatedSearchPage(ctx context.Context, in *AggregatedSearchPageRequest, opts ...grpc.CallOption) (*AggregatedSearchPageResponse, error)
	SearchPostComment(ctx context.Context, in *SearchPostCommentRequest, opts ...grpc.CallOption) (*SearchPostCommentResponse, error)
}

type siteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSiteServiceClient(cc grpc.ClientConnInterface) SiteServiceClient {
	return &siteServiceClient{cc}
}

func (c *siteServiceClient) GetSiteList(ctx context.Context, in *GetSiteListRequest, opts ...grpc.CallOption) (*GetSiteListResponse, error) {
	out := new(GetSiteListResponse)
	err := c.cc.Invoke(ctx, SiteService_GetSiteList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siteServiceClient) GetSite(ctx context.Context, in *GetSiteRequest, opts ...grpc.CallOption) (*GetSiteResponse, error) {
	out := new(GetSiteResponse)
	err := c.cc.Invoke(ctx, SiteService_GetSite_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siteServiceClient) GetCategoryList(ctx context.Context, in *GetCategoryListRequest, opts ...grpc.CallOption) (*GetCategoryListResponse, error) {
	out := new(GetCategoryListResponse)
	err := c.cc.Invoke(ctx, SiteService_GetCategoryList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siteServiceClient) GetCategory(ctx context.Context, in *GetCategoryRequest, opts ...grpc.CallOption) (*GetCategoryResponse, error) {
	out := new(GetCategoryResponse)
	err := c.cc.Invoke(ctx, SiteService_GetCategory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siteServiceClient) AddCategory(ctx context.Context, in *AddCategoryRequest, opts ...grpc.CallOption) (*AddCategoryResponse, error) {
	out := new(AddCategoryResponse)
	err := c.cc.Invoke(ctx, SiteService_AddCategory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siteServiceClient) EditCategory(ctx context.Context, in *EditCategoryRequest, opts ...grpc.CallOption) (*EditCategoryResponse, error) {
	out := new(EditCategoryResponse)
	err := c.cc.Invoke(ctx, SiteService_EditCategory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siteServiceClient) DeleteCategory(ctx context.Context, in *DeleteCategoryRequest, opts ...grpc.CallOption) (*DeleteCategoryResponse, error) {
	out := new(DeleteCategoryResponse)
	err := c.cc.Invoke(ctx, SiteService_DeleteCategory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siteServiceClient) GetPostList(ctx context.Context, in *GetPostListRequest, opts ...grpc.CallOption) (*GetPostListResponse, error) {
	out := new(GetPostListResponse)
	err := c.cc.Invoke(ctx, SiteService_GetPostList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siteServiceClient) GetPostDetail(ctx context.Context, in *GetPostDetailRequest, opts ...grpc.CallOption) (*GetPostDetailResponse, error) {
	out := new(GetPostDetailResponse)
	err := c.cc.Invoke(ctx, SiteService_GetPostDetail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siteServiceClient) AddPost(ctx context.Context, in *AddPostRequest, opts ...grpc.CallOption) (*AddPostResponse, error) {
	out := new(AddPostResponse)
	err := c.cc.Invoke(ctx, SiteService_AddPost_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siteServiceClient) EditPost(ctx context.Context, in *EditPostRequest, opts ...grpc.CallOption) (*EditPostResponse, error) {
	out := new(EditPostResponse)
	err := c.cc.Invoke(ctx, SiteService_EditPost_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siteServiceClient) DeletePost(ctx context.Context, in *DeletePostRequest, opts ...grpc.CallOption) (*DeletePostResponse, error) {
	out := new(DeletePostResponse)
	err := c.cc.Invoke(ctx, SiteService_DeletePost_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siteServiceClient) GetComments(ctx context.Context, in *GetCommentsRequest, opts ...grpc.CallOption) (*GetCommentsResponse, error) {
	out := new(GetCommentsResponse)
	err := c.cc.Invoke(ctx, SiteService_GetComments_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siteServiceClient) AddComment(ctx context.Context, in *AddCommentRequest, opts ...grpc.CallOption) (*AddCommentResponse, error) {
	out := new(AddCommentResponse)
	err := c.cc.Invoke(ctx, SiteService_AddComment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siteServiceClient) EditComment(ctx context.Context, in *EditCommentRequest, opts ...grpc.CallOption) (*EditCommentResponse, error) {
	out := new(EditCommentResponse)
	err := c.cc.Invoke(ctx, SiteService_EditComment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siteServiceClient) DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*DeleteCommentResponse, error) {
	out := new(DeleteCommentResponse)
	err := c.cc.Invoke(ctx, SiteService_DeleteComment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siteServiceClient) AggregatedSitePage(ctx context.Context, in *AggregatedSitePageRequest, opts ...grpc.CallOption) (*AggregatedSitePageResponse, error) {
	out := new(AggregatedSitePageResponse)
	err := c.cc.Invoke(ctx, SiteService_AggregatedSitePage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siteServiceClient) AggregatedCategoryPage(ctx context.Context, in *AggregatedCategoryPageRequest, opts ...grpc.CallOption) (*AggregatedCategoryPageResponse, error) {
	out := new(AggregatedCategoryPageResponse)
	err := c.cc.Invoke(ctx, SiteService_AggregatedCategoryPage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siteServiceClient) AggregatedPostPage(ctx context.Context, in *AggregatedPostPageRequest, opts ...grpc.CallOption) (*AggregatedPostPageResponse, error) {
	out := new(AggregatedPostPageResponse)
	err := c.cc.Invoke(ctx, SiteService_AggregatedPostPage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siteServiceClient) AggregatedSearchPage(ctx context.Context, in *AggregatedSearchPageRequest, opts ...grpc.CallOption) (*AggregatedSearchPageResponse, error) {
	out := new(AggregatedSearchPageResponse)
	err := c.cc.Invoke(ctx, SiteService_AggregatedSearchPage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siteServiceClient) SearchPostComment(ctx context.Context, in *SearchPostCommentRequest, opts ...grpc.CallOption) (*SearchPostCommentResponse, error) {
	out := new(SearchPostCommentResponse)
	err := c.cc.Invoke(ctx, SiteService_SearchPostComment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SiteServiceServer is the server API for SiteService service.
// All implementations must embed UnimplementedSiteServiceServer
// for forward compatibility
type SiteServiceServer interface {
	GetSiteList(context.Context, *GetSiteListRequest) (*GetSiteListResponse, error)
	GetSite(context.Context, *GetSiteRequest) (*GetSiteResponse, error)
	GetCategoryList(context.Context, *GetCategoryListRequest) (*GetCategoryListResponse, error)
	GetCategory(context.Context, *GetCategoryRequest) (*GetCategoryResponse, error)
	AddCategory(context.Context, *AddCategoryRequest) (*AddCategoryResponse, error)
	EditCategory(context.Context, *EditCategoryRequest) (*EditCategoryResponse, error)
	DeleteCategory(context.Context, *DeleteCategoryRequest) (*DeleteCategoryResponse, error)
	GetPostList(context.Context, *GetPostListRequest) (*GetPostListResponse, error)
	GetPostDetail(context.Context, *GetPostDetailRequest) (*GetPostDetailResponse, error)
	AddPost(context.Context, *AddPostRequest) (*AddPostResponse, error)
	EditPost(context.Context, *EditPostRequest) (*EditPostResponse, error)
	DeletePost(context.Context, *DeletePostRequest) (*DeletePostResponse, error)
	GetComments(context.Context, *GetCommentsRequest) (*GetCommentsResponse, error)
	AddComment(context.Context, *AddCommentRequest) (*AddCommentResponse, error)
	EditComment(context.Context, *EditCommentRequest) (*EditCommentResponse, error)
	DeleteComment(context.Context, *DeleteCommentRequest) (*DeleteCommentResponse, error)
	AggregatedSitePage(context.Context, *AggregatedSitePageRequest) (*AggregatedSitePageResponse, error)
	AggregatedCategoryPage(context.Context, *AggregatedCategoryPageRequest) (*AggregatedCategoryPageResponse, error)
	AggregatedPostPage(context.Context, *AggregatedPostPageRequest) (*AggregatedPostPageResponse, error)
	AggregatedSearchPage(context.Context, *AggregatedSearchPageRequest) (*AggregatedSearchPageResponse, error)
	SearchPostComment(context.Context, *SearchPostCommentRequest) (*SearchPostCommentResponse, error)
	mustEmbedUnimplementedSiteServiceServer()
}

// UnimplementedSiteServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSiteServiceServer struct {
}

func (UnimplementedSiteServiceServer) GetSiteList(context.Context, *GetSiteListRequest) (*GetSiteListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSiteList not implemented")
}
func (UnimplementedSiteServiceServer) GetSite(context.Context, *GetSiteRequest) (*GetSiteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSite not implemented")
}
func (UnimplementedSiteServiceServer) GetCategoryList(context.Context, *GetCategoryListRequest) (*GetCategoryListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCategoryList not implemented")
}
func (UnimplementedSiteServiceServer) GetCategory(context.Context, *GetCategoryRequest) (*GetCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCategory not implemented")
}
func (UnimplementedSiteServiceServer) AddCategory(context.Context, *AddCategoryRequest) (*AddCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCategory not implemented")
}
func (UnimplementedSiteServiceServer) EditCategory(context.Context, *EditCategoryRequest) (*EditCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditCategory not implemented")
}
func (UnimplementedSiteServiceServer) DeleteCategory(context.Context, *DeleteCategoryRequest) (*DeleteCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCategory not implemented")
}
func (UnimplementedSiteServiceServer) GetPostList(context.Context, *GetPostListRequest) (*GetPostListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostList not implemented")
}
func (UnimplementedSiteServiceServer) GetPostDetail(context.Context, *GetPostDetailRequest) (*GetPostDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostDetail not implemented")
}
func (UnimplementedSiteServiceServer) AddPost(context.Context, *AddPostRequest) (*AddPostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPost not implemented")
}
func (UnimplementedSiteServiceServer) EditPost(context.Context, *EditPostRequest) (*EditPostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditPost not implemented")
}
func (UnimplementedSiteServiceServer) DeletePost(context.Context, *DeletePostRequest) (*DeletePostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePost not implemented")
}
func (UnimplementedSiteServiceServer) GetComments(context.Context, *GetCommentsRequest) (*GetCommentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetComments not implemented")
}
func (UnimplementedSiteServiceServer) AddComment(context.Context, *AddCommentRequest) (*AddCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddComment not implemented")
}
func (UnimplementedSiteServiceServer) EditComment(context.Context, *EditCommentRequest) (*EditCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditComment not implemented")
}
func (UnimplementedSiteServiceServer) DeleteComment(context.Context, *DeleteCommentRequest) (*DeleteCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteComment not implemented")
}
func (UnimplementedSiteServiceServer) AggregatedSitePage(context.Context, *AggregatedSitePageRequest) (*AggregatedSitePageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AggregatedSitePage not implemented")
}
func (UnimplementedSiteServiceServer) AggregatedCategoryPage(context.Context, *AggregatedCategoryPageRequest) (*AggregatedCategoryPageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AggregatedCategoryPage not implemented")
}
func (UnimplementedSiteServiceServer) AggregatedPostPage(context.Context, *AggregatedPostPageRequest) (*AggregatedPostPageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AggregatedPostPage not implemented")
}
func (UnimplementedSiteServiceServer) AggregatedSearchPage(context.Context, *AggregatedSearchPageRequest) (*AggregatedSearchPageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AggregatedSearchPage not implemented")
}
func (UnimplementedSiteServiceServer) SearchPostComment(context.Context, *SearchPostCommentRequest) (*SearchPostCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchPostComment not implemented")
}
func (UnimplementedSiteServiceServer) mustEmbedUnimplementedSiteServiceServer() {}

// UnsafeSiteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SiteServiceServer will
// result in compilation errors.
type UnsafeSiteServiceServer interface {
	mustEmbedUnimplementedSiteServiceServer()
}

func RegisterSiteServiceServer(s grpc.ServiceRegistrar, srv SiteServiceServer) {
	s.RegisterService(&SiteService_ServiceDesc, srv)
}

func _SiteService_GetSiteList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSiteListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServiceServer).GetSiteList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SiteService_GetSiteList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServiceServer).GetSiteList(ctx, req.(*GetSiteListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SiteService_GetSite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSiteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServiceServer).GetSite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SiteService_GetSite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServiceServer).GetSite(ctx, req.(*GetSiteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SiteService_GetCategoryList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoryListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServiceServer).GetCategoryList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SiteService_GetCategoryList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServiceServer).GetCategoryList(ctx, req.(*GetCategoryListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SiteService_GetCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServiceServer).GetCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SiteService_GetCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServiceServer).GetCategory(ctx, req.(*GetCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SiteService_AddCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServiceServer).AddCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SiteService_AddCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServiceServer).AddCategory(ctx, req.(*AddCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SiteService_EditCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServiceServer).EditCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SiteService_EditCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServiceServer).EditCategory(ctx, req.(*EditCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SiteService_DeleteCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServiceServer).DeleteCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SiteService_DeleteCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServiceServer).DeleteCategory(ctx, req.(*DeleteCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SiteService_GetPostList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServiceServer).GetPostList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SiteService_GetPostList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServiceServer).GetPostList(ctx, req.(*GetPostListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SiteService_GetPostDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServiceServer).GetPostDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SiteService_GetPostDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServiceServer).GetPostDetail(ctx, req.(*GetPostDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SiteService_AddPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServiceServer).AddPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SiteService_AddPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServiceServer).AddPost(ctx, req.(*AddPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SiteService_EditPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServiceServer).EditPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SiteService_EditPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServiceServer).EditPost(ctx, req.(*EditPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SiteService_DeletePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServiceServer).DeletePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SiteService_DeletePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServiceServer).DeletePost(ctx, req.(*DeletePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SiteService_GetComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServiceServer).GetComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SiteService_GetComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServiceServer).GetComments(ctx, req.(*GetCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SiteService_AddComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServiceServer).AddComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SiteService_AddComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServiceServer).AddComment(ctx, req.(*AddCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SiteService_EditComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServiceServer).EditComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SiteService_EditComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServiceServer).EditComment(ctx, req.(*EditCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SiteService_DeleteComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServiceServer).DeleteComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SiteService_DeleteComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServiceServer).DeleteComment(ctx, req.(*DeleteCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SiteService_AggregatedSitePage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AggregatedSitePageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServiceServer).AggregatedSitePage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SiteService_AggregatedSitePage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServiceServer).AggregatedSitePage(ctx, req.(*AggregatedSitePageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SiteService_AggregatedCategoryPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AggregatedCategoryPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServiceServer).AggregatedCategoryPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SiteService_AggregatedCategoryPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServiceServer).AggregatedCategoryPage(ctx, req.(*AggregatedCategoryPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SiteService_AggregatedPostPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AggregatedPostPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServiceServer).AggregatedPostPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SiteService_AggregatedPostPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServiceServer).AggregatedPostPage(ctx, req.(*AggregatedPostPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SiteService_AggregatedSearchPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AggregatedSearchPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServiceServer).AggregatedSearchPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SiteService_AggregatedSearchPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServiceServer).AggregatedSearchPage(ctx, req.(*AggregatedSearchPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SiteService_SearchPostComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchPostCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServiceServer).SearchPostComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SiteService_SearchPostComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServiceServer).SearchPostComment(ctx, req.(*SearchPostCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SiteService_ServiceDesc is the grpc.ServiceDesc for SiteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SiteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "invoker_api.SiteService",
	HandlerType: (*SiteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSiteList",
			Handler:    _SiteService_GetSiteList_Handler,
		},
		{
			MethodName: "GetSite",
			Handler:    _SiteService_GetSite_Handler,
		},
		{
			MethodName: "GetCategoryList",
			Handler:    _SiteService_GetCategoryList_Handler,
		},
		{
			MethodName: "GetCategory",
			Handler:    _SiteService_GetCategory_Handler,
		},
		{
			MethodName: "AddCategory",
			Handler:    _SiteService_AddCategory_Handler,
		},
		{
			MethodName: "EditCategory",
			Handler:    _SiteService_EditCategory_Handler,
		},
		{
			MethodName: "DeleteCategory",
			Handler:    _SiteService_DeleteCategory_Handler,
		},
		{
			MethodName: "GetPostList",
			Handler:    _SiteService_GetPostList_Handler,
		},
		{
			MethodName: "GetPostDetail",
			Handler:    _SiteService_GetPostDetail_Handler,
		},
		{
			MethodName: "AddPost",
			Handler:    _SiteService_AddPost_Handler,
		},
		{
			MethodName: "EditPost",
			Handler:    _SiteService_EditPost_Handler,
		},
		{
			MethodName: "DeletePost",
			Handler:    _SiteService_DeletePost_Handler,
		},
		{
			MethodName: "GetComments",
			Handler:    _SiteService_GetComments_Handler,
		},
		{
			MethodName: "AddComment",
			Handler:    _SiteService_AddComment_Handler,
		},
		{
			MethodName: "EditComment",
			Handler:    _SiteService_EditComment_Handler,
		},
		{
			MethodName: "DeleteComment",
			Handler:    _SiteService_DeleteComment_Handler,
		},
		{
			MethodName: "AggregatedSitePage",
			Handler:    _SiteService_AggregatedSitePage_Handler,
		},
		{
			MethodName: "AggregatedCategoryPage",
			Handler:    _SiteService_AggregatedCategoryPage_Handler,
		},
		{
			MethodName: "AggregatedPostPage",
			Handler:    _SiteService_AggregatedPostPage_Handler,
		},
		{
			MethodName: "AggregatedSearchPage",
			Handler:    _SiteService_AggregatedSearchPage_Handler,
		},
		{
			MethodName: "SearchPostComment",
			Handler:    _SiteService_SearchPostComment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/invoker.proto",
}

const (
	UserService_ThumbupPost_FullMethodName    = "/invoker_api.UserService/ThumbupPost"
	UserService_ThumbupComment_FullMethodName = "/invoker_api.UserService/ThumbupComment"
	UserService_PostHistory_FullMethodName    = "/invoker_api.UserService/PostHistory"
	UserService_CommentHistory_FullMethodName = "/invoker_api.UserService/CommentHistory"
	UserService_ThumbupHistory_FullMethodName = "/invoker_api.UserService/ThumbupHistory"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	ThumbupPost(ctx context.Context, in *ThumbupPostRequest, opts ...grpc.CallOption) (*ThumbupPostResponse, error)
	ThumbupComment(ctx context.Context, in *ThumbupCommentRequest, opts ...grpc.CallOption) (*ThumbupCommentResponse, error)
	PostHistory(ctx context.Context, in *PostHistoryRequest, opts ...grpc.CallOption) (*PostHistoryResponse, error)
	CommentHistory(ctx context.Context, in *CommentHistoryRequest, opts ...grpc.CallOption) (*CommentHistoryResponse, error)
	ThumbupHistory(ctx context.Context, in *ThumbupHistoryRequest, opts ...grpc.CallOption) (*ThumbupHistoryResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) ThumbupPost(ctx context.Context, in *ThumbupPostRequest, opts ...grpc.CallOption) (*ThumbupPostResponse, error) {
	out := new(ThumbupPostResponse)
	err := c.cc.Invoke(ctx, UserService_ThumbupPost_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ThumbupComment(ctx context.Context, in *ThumbupCommentRequest, opts ...grpc.CallOption) (*ThumbupCommentResponse, error) {
	out := new(ThumbupCommentResponse)
	err := c.cc.Invoke(ctx, UserService_ThumbupComment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) PostHistory(ctx context.Context, in *PostHistoryRequest, opts ...grpc.CallOption) (*PostHistoryResponse, error) {
	out := new(PostHistoryResponse)
	err := c.cc.Invoke(ctx, UserService_PostHistory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CommentHistory(ctx context.Context, in *CommentHistoryRequest, opts ...grpc.CallOption) (*CommentHistoryResponse, error) {
	out := new(CommentHistoryResponse)
	err := c.cc.Invoke(ctx, UserService_CommentHistory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ThumbupHistory(ctx context.Context, in *ThumbupHistoryRequest, opts ...grpc.CallOption) (*ThumbupHistoryResponse, error) {
	out := new(ThumbupHistoryResponse)
	err := c.cc.Invoke(ctx, UserService_ThumbupHistory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility
type UserServiceServer interface {
	ThumbupPost(context.Context, *ThumbupPostRequest) (*ThumbupPostResponse, error)
	ThumbupComment(context.Context, *ThumbupCommentRequest) (*ThumbupCommentResponse, error)
	PostHistory(context.Context, *PostHistoryRequest) (*PostHistoryResponse, error)
	CommentHistory(context.Context, *CommentHistoryRequest) (*CommentHistoryResponse, error)
	ThumbupHistory(context.Context, *ThumbupHistoryRequest) (*ThumbupHistoryResponse, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (UnimplementedUserServiceServer) ThumbupPost(context.Context, *ThumbupPostRequest) (*ThumbupPostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ThumbupPost not implemented")
}
func (UnimplementedUserServiceServer) ThumbupComment(context.Context, *ThumbupCommentRequest) (*ThumbupCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ThumbupComment not implemented")
}
func (UnimplementedUserServiceServer) PostHistory(context.Context, *PostHistoryRequest) (*PostHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostHistory not implemented")
}
func (UnimplementedUserServiceServer) CommentHistory(context.Context, *CommentHistoryRequest) (*CommentHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommentHistory not implemented")
}
func (UnimplementedUserServiceServer) ThumbupHistory(context.Context, *ThumbupHistoryRequest) (*ThumbupHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ThumbupHistory not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_ThumbupPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ThumbupPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ThumbupPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_ThumbupPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ThumbupPost(ctx, req.(*ThumbupPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ThumbupComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ThumbupCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ThumbupComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_ThumbupComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ThumbupComment(ctx, req.(*ThumbupCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_PostHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).PostHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_PostHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).PostHistory(ctx, req.(*PostHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CommentHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CommentHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_CommentHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CommentHistory(ctx, req.(*CommentHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ThumbupHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ThumbupHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ThumbupHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_ThumbupHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ThumbupHistory(ctx, req.(*ThumbupHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "invoker_api.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ThumbupPost",
			Handler:    _UserService_ThumbupPost_Handler,
		},
		{
			MethodName: "ThumbupComment",
			Handler:    _UserService_ThumbupComment_Handler,
		},
		{
			MethodName: "PostHistory",
			Handler:    _UserService_PostHistory_Handler,
		},
		{
			MethodName: "CommentHistory",
			Handler:    _UserService_CommentHistory_Handler,
		},
		{
			MethodName: "ThumbupHistory",
			Handler:    _UserService_ThumbupHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/invoker.proto",
}
