// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGatewayNode = "gateway_node"

// GatewayNode mapped from table <gateway_node>
type GatewayNode struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt int64     `gorm:"column:deleted_at;not null" json:"deleted_at"`
	Name      string    `gorm:"column:name;not null" json:"name"`
	Ipv4      string    `gorm:"column:ipv4;not null" json:"ipv4"`
	RPCPort   int32     `gorm:"column:rpc_port;not null" json:"rpc_port"`
}

// TableName GatewayNode's table name
func (*GatewayNode) TableName() string {
	return TableNameGatewayNode
}
