// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProtoStatisticHourly = "proto_statistic_hourly"

// ProtoStatisticHourly mapped from table <proto_statistic_hourly>
type ProtoStatisticHourly struct {
	ID                     int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt              time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt              time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt              int64     `gorm:"column:deleted_at;not null" json:"deleted_at"`
	Timestamp              int64     `gorm:"column:timestamp;not null" json:"timestamp"`
	GatewayNode            string    `gorm:"column:gateway_node;not null" json:"gateway_node"`
	Application            string    `gorm:"column:application;not null" json:"application"`
	Service                string    `gorm:"column:service;not null" json:"service"`
	Path                   string    `gorm:"column:path;not null" json:"path"`
	Hit                    int64     `gorm:"column:hit;not null" json:"hit"`
	SuccessHit             int64     `gorm:"column:success_hit;not null" json:"success_hit"`
	ProxySuccessHit        int64     `gorm:"column:proxy_success_hit;not null" json:"proxy_success_hit"`
	DurationAverage        int64     `gorm:"column:duration_average;not null" json:"duration_average"`
	DurationMin            int64     `gorm:"column:duration_min;not null" json:"duration_min"`
	DurationMax            int64     `gorm:"column:duration_max;not null" json:"duration_max"`
	ServiceDurationAverage int64     `gorm:"column:service_duration_average;not null" json:"service_duration_average"`
	ServiceDurationMin     int64     `gorm:"column:service_duration_min;not null" json:"service_duration_min"`
	ServiceDurationMax     int64     `gorm:"column:service_duration_max;not null" json:"service_duration_max"`
}

// TableName ProtoStatisticHourly's table name
func (*ProtoStatisticHourly) TableName() string {
	return TableNameProtoStatisticHourly
}
